H-uru/Plasma

Sources/Plasma/CoreLib/plFormat.cpp
Sources/Plasma/CoreLib/plString.cpp
Sources/Plasma/CoreLib/plString.h

The important one here is the fix for the string literal constructors.  A string literal's size includes its nul-terminator :(

plString fixes

---

CMakeLists.txt

Fixes the warning encountered when generating build files with CMake 3.1.
See [CMP0054](http://www.cmake.org/cmake/help/v3.1/policy/CMP0054.html) for more information.

Fix CMake 3.1 warning regarding quoted arguments in conditionals.

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp

Check whether we got anything back from FindItemByName instead of just handing off an empty item to AddItemsToCloset.

Fix crash when user tries to add a clothing item which doesn't exist.

---

Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/NucleusLib/pnUtils/pnUtArray.h
Sources/Plasma/PubUtilLib/plDrawable/plMorphSequence.cpp
Sources/Plasma/PubUtilLib/plDrawable/plMorphSequenceSDLMod.cpp
Sources/Plasma/PubUtilLib/plFile/plSecureStream.cpp
Sources/Plasma/PubUtilLib/plGLight/plPerspDirSlave.cpp
Sources/Plasma/PubUtilLib/plGLight/plShadowSlave.cpp
cmake/CompilerChecks.cmake

Fixes for MinGW and clang with HS_DEBUGGING enabled.

Some cross-platform code cleanups.

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommandsNet.cpp
Sources/Plasma/FeatureLib/pfPython/cyAccountManagement.cpp
Sources/Plasma/PubUtilLib/plGImage/plJPEG.cpp

Also fixes the use of libjpeg-6b (or libjpeg-turbo built with the jpeg-62 API, which is the default on Debian, sadly).

Some fixes for compiler errors found on GCC/Linux

---

Sources/Plasma/CoreLib/hsThread_Win.cpp
Sources/Plasma/PubUtilLib/plInterp/plController.cpp

This fixes some Coverity defects (which Clang also warns about)

Clean up some incorrect uses of operator delete

---

CMakeLists.txt
Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/HeadSpin.h

Previously, `hsAssert()` would be completely ignored on anything other than Windows, even when `HS_DEBUGGING` was properly defined.  This makes it actually print the error message, and then abort afterwards for `HS_DEBUGGING` mode.  Release mode will still silently ignore asserts as before.
EDIT: Also included @dpogue's `DebugIsDebuggerPresent` fix for Linux, and a `DebugBreak` equivalent for all Unixes.

Make hsAssert useful on Linux / Mac

---

Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/plFormat.cpp
Sources/Plasma/CoreLib/plFormat.h
Sources/Plasma/CoreLib/plString.cpp
Sources/Tests/CoreTests/CMakeLists.txt
Sources/Tests/CoreTests/test_plFormat.cpp
Sources/Tests/CoreTests/test_plString.cpp

This PR:
- Significantly extend the coverage of the plString tests
- Adds tests for plFormat
- Fixes several bugs discovered while writing tests in both plString and plFormat
It currently passes all tests on:
- MSVC 2013
- GCC 5.1 (Arch x86_64)
- Clang 3.6 (Arch x86_64, using libstdc++ since GTest 1.6 doesn't work with libc++)
- (EDIT) Clang 3.6 with libc++ works with GTest 1.7.  I'll submit that as a separate PR

String tests

---

Sources/Plasma/PubUtilLib/plPipeline/plGBufferGroup.cpp
Sources/Plasma/PubUtilLib/plPipeline/plGBufferGroup.h

Does what it says. `std::vector` is just better than `hsTArray`.

GBufferGroup hsTArray -> std::vector

---

Sources/Plasma/NucleusLib/pnNetCli/pnNcChannel.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNcCli.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNetCli.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGame.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGateKeeper.cpp

This changes the message object to a pointer within the initialization structs.  Since initialization order is not guaranteed, the messages were getting copied to the init struct before it was fully initialized, even though it got initialized later.  This ensures that the data is always up-to-date by the time it is used, by pointing to the original struct instead of copying it.

Fix static initialization order dependency in MSVC2015

---

Sources/Plasma/FeatureLib/pfPython/cyAccountManagement.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.h

This fixes a crash observed when creating a new avatar. `ARRAY` and friends do not run constructors when the `New` method is used. `ARRAY` is evil anyway, so here's my fix.

Convert NetCommPlayer to std::vector

---

Sources/Plasma/PubUtilLib/plInterp/hsInterp.cpp

Casting the floating point time to an integer causes issues with boundary frame comparisons. So, actually use floats. This makes animations smoother than a baby's arse once again :smile:

Fix Jittering Animations

---

Sources/Plasma/PubUtilLib/plAvatar/plAvatarSDLModifier.cpp

These checks introduced a hidden race condition. If the initial avatar physical update comes in after the initial avatar update (always happens on DirtSand, never happens on MOUL), then the physical update could be rejected if the avatar is sitting on the ground or on a sitting modifier (this adds stages, which count as a task). This results in seeing an avatar sitting at the link in point. Whoops!
I can think of no cases where these checks are actually useful. It's also difficult to determine if we are linking in due to the fact that we're in the grey area between loading the entire age and fading the screen. All flags indicate we're in the age. This is just the best way to fix it(TM)

Remove some checks from AvatarPhysical updates

---

Sources/Plasma/FeatureLib/pfGameScoreMgr/pfGameScoreMgr.cpp
Sources/Plasma/FeatureLib/pfGameScoreMgr/pfGameScoreMgr.h
Sources/Plasma/FeatureLib/pfPython/pyGameScore.cpp
Sources/Plasma/FeatureLib/pfPython/pyGameScore.h
Sources/Plasma/FeatureLib/pfPython/pyGameScoreGlue.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.h
Sources/Plasma/PubUtilLib/plNetGameLib/Intern.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.h

Implements a new message and python bindings for retrieving score leaders from the server. See H-uru/dirtsand#103 for a sample implementation. H-uru/moul-scripts#94 should be merged concurrently.
Required for non-eap Ayoheek.

Implement Leaderboards

---

Sources/Plasma/PubUtilLib/plInterp/plAnimTimeConvert.cpp

Some dumb ass artist has a LayerAnimation set to `kLoop` with `fLoopBegin` == 0 and `fLoopEnd` == 0. This worked in MOUL, but now we use that in our keyframe calculations now. Whoops. Most of the data should be fine since Plasma checked frame times until MOUL. This is just an edge case in Ahnoying, really.

NaN animation time == kaboom

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/PubUtilLib/plAudio/plSound.cpp
Sources/Plasma/PubUtilLib/plAudio/plSound.h
Sources/Plasma/PubUtilLib/plAudio/plWin32Sound.cpp
Sources/Plasma/PubUtilLib/plAudio/plWin32Sound.h

Some fixes and additions to the audio console commands that I'm using to debug why the heek table sound is so loud. Previously, the `Audio.NextDebugPlate` command did not work. I also added `Audio.ShowDebugPlate` so that we wouldn't have to step through tons of useless crap before we get to the one we want.

Fix sound debug

---

Sources/Plasma/FeatureLib/pfCamera/plCameraBrain.cpp

The reason for the previous commit was that coverity indicated view was being passed to up and vice versa. I don't know what they were intending, but the calculation was correct, just the argument naming was wrong. This has all been corrected now.
Test cases: Neighborhood classroom, Palace Alcove Nexus Terminal

Fix weird camera angles caused by 9c49b57

---

Sources/Plasma/PubUtilLib/plAudio/plWin32StaticSound.cpp
Sources/Plasma/PubUtilLib/plAudio/plWin32StreamingSound.cpp

This pull request fixes problems with certain sounds being entirely too loud, for example, the ayoheek drone sound. This reverts commit b3d6afc1c1436f94c7a1591f9aa156dd49948712.
As best as I can remember, that commit was originally intended to fix some crashing issues present in transfused versions of Doobes' Guild of Messengers Pub. We determined that sounds exported in PyPRP ages would cause issues if they were shorter than 4 seconds in length. The real problem here was PyPRP bugs. For future reference: PyPRP should only be pointed to `.wav` files (not `.ogg`). Anything 4 seconds or shorter MUST be a plWin32StaticSound.

Fix loud sound issue

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEditGlue.cpp

Refreshing multiline edit controls is expensive, and there are lots of implicit updates in common operations, such as adding strings, adding colors, and deleting lines. This allows the scripter to manually suppress expensive updates until (s)he is done doing evil things.

Allow python scripts to supress MLEdit updates

---

Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp

If this isn't done, the client will crash on exit if markers have been loaded at some point in the game.

Allow PXPhysicals to change scene nodes

---

Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClient.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp

We now use a standard window for everything and resize the display using the Win32 api for fullscreen mode instead of exclusive fullscreen mode. With the introduction of DWM in Vista, exclusive fullscreen apps are blocked when they are not focused. In other words, fullscreen exclusive mode caused the client's loading processes to be blocked while alt+tabed away. This fixes that issue. Furthermore, we can now bring back #507 without the crashing seen previously.

Fullscreen Window

---

Sources/Plasma/Apps/plPageInfo/plAllCreatables.cpp
Sources/Plasma/Apps/plPageOptimizer/plAllCreatables.cpp

Seems like these two include paths were missed in PR #527. Compiles and both tools seem to run correctly. Client hasn't been tested but it shouldn't affect it.

Fix two pnTimer paths

---

Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.h
Sources/Plasma/PubUtilLib/plPhysX/plSimulationMgr.cpp

PhysX requires all of its actors to have cooked mesh data. This cooked data is unfortunately not compatible with other versions of PhysX outside of the minor branch. The format is also largely unknown. Therefore, it is relevant to allow CWE prps to include an engine agnostic physical format to reduce our dependencies on proprietary libraries.
All PhysX blobs thankfully begin with the magic string NXS\x01, so we now abuse that by adding our own format that begins with the magic string HSP\x01. These blobs are cooked on the fly while already cooked blobs are passed directly on to PhysX.

Implement a generic hull/trimesh collider format

---

Sources/Plasma/PubUtilLib/plGImage/plBitmap.cpp
Sources/Plasma/PubUtilLib/plGImage/plBitmap.h
Sources/Plasma/PubUtilLib/plGImage/plMipmap.cpp
Sources/Plasma/PubUtilLib/plGImage/plMipmap.h
Sources/Tools/MaxComponent/plMiscComponents.cpp
Sources/Tools/MaxConvert/plBitmapCreator.cpp
Sources/Tools/MaxConvert/plBitmapCreator.h
Sources/Tools/MaxConvert/plLayerConverter.cpp
Sources/Tools/MaxConvert/plLayerConverter.h
Sources/Tools/MaxConvert/plLightMapGen.cpp

Using the existing PNG library support, this allows PNG-compressed images as plBitmaps and plMipmaps

Add PNG support to plBitmap and plMipmap.

---

Sources/Plasma/PubUtilLib/plVault/plVaultNodeAccess.cpp

We were inserting an extra separating delim, causing the tokenize to return an extra substring. This confused the note processor causing it to discard the age invite. Oops!

Fix age invites

---

Sources/Plasma/FeatureLib/pfConditional/plObjectInBoxConditionalObject.cpp
Sources/Plasma/FeatureLib/pfConditional/plObjectInBoxConditionalObject.h
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsole/pfGameConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfPython/pySceneObject.cpp
Sources/Plasma/FeatureLib/pfPython/pySceneObject.h
Sources/Plasma/FeatureLib/pfPython/pySceneObjectGlue.cpp
Sources/Plasma/NucleusLib/pnMessage/plServerReplyMsg.h
Sources/Plasma/NucleusLib/pnModifier/plLogicModBase.cpp
Sources/Plasma/NucleusLib/pnModifier/plLogicModBase.h
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.h
Sources/Plasma/PubUtilLib/plModifier/plLogicModifier.cpp
Sources/Plasma/PubUtilLib/plModifier/plLogicModifier.h

The goal behind this changeset is to fix the intermittent issues seen in ages such as Gahreesen and Teledahn in which the avatar falls through the floor when leaving a subworld. This generally happens when the player's ping time is unsatisfactorily high. `plVolumeSensorConditionalObject` acquires an exclusive server lock before triggering the transition, and if this lock takes too long... the player has fallen through the floor. At some point, Cyan introduced the special case `plVolumeSensorConditionalObjectNoArbitration` exactly for this purpose, but it appears to never have been used.
This changeset refactors both VolumeSensor classes and moves the logic into the base class. The NoArbitration variant just sets a flag on the base class. This enables us to toggle which behavior we want in …

Cleanup VolumeSensorConditionalObject

---

Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp
Sources/Plasma/PubUtilLib/plCompression/plZlibStream.h

This changeset fixes the issues with 0-byte files being downloaded from MOULa via the Gehn repair tool. It turned out that we were opening too many concurrent files. Oops! Bonus: a few code cleanups such as `HS_OVERRIDE` and `emplace_back`

Fix 0-byte patch files

---

Sources/Plasma/Apps/plPageInfo/CMakeLists.txt
Sources/Plasma/Apps/plPageOptimizer/CMakeLists.txt
Sources/Plasma/PubUtilLib/plResMgr/plResManager.cpp
Sources/Tools/plResBrowser/CMakeLists.txt

Previously, the client loaded every PRP in the global age specified. Now, we test to ensure that the requested page is listed in the age file. This is relevant considering all of the clothing PRPs going into MOULa. We don't want folks able to bring random clothing files onto Gehn. Please note this code path is only used for global ages.

Fix PageInAge ignoring the .age file

---

Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp

This fixes a crash [reported](https://forum.guildofwriters.org/viewtopic.php?f=117&t=6812) to occur on Windows 7 when linking to Minkata and Ahnonay. We again see issues when reencoding the `c_str` of an `ST::string`. Please note that this changeset converts the second argument of `OnPageLoad` from an `str` to an `unicode` object.

Fix unicode mangling in the OnPageLoad python CB

---

Sources/Plasma/Apps/plPageInfo/CMakeLists.txt
Sources/Plasma/Apps/plPageOptimizer/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPython/pyVaultMarkerGameNodeGlue.cpp
Sources/Plasma/NucleusLib/pnEncryption/plBigNum.cpp
Sources/Plasma/NucleusLib/pnEncryption/plBigNum.h
Sources/Plasma/NucleusLib/pnEncryption/plChallengeHash.cpp
Sources/Plasma/NucleusLib/pnEncryption/plChecksum.cpp
Sources/Plasma/NucleusLib/pnEncryption/plChecksum.h
Sources/Plasma/PubUtilLib/plResMgr/CMakeLists.txt
Sources/Tools/plFontConverter/CMakeLists.txt
Sources/Tools/plResBrowser/CMakeLists.txt

Using OpenSSL 1.1 for the client is still not an option with this change, but this allows us to once again build the tools on Linux systems with newer system OpenSSL libraries.

OpenSSL 1.1 / Linux compile fixes

---

Sources/Tests/gtest-1.8.0/cmake/internal_utils.cmake
Sources/Tests/gtest-1.8.0/include/gtest/gtest-printers.h
Sources/Tests/gtest-1.8.0/include/gtest/internal/gtest-port.h
Sources/Tests/gtest-1.8.0/test/gtest-printers_test.cc
Sources/Tests/gtest-1.8.0/test/gtest_catch_exceptions_test_.cc

This change is ported/copied from zrax/string_theory@2c49e9ce353dd04bd1837c614ec7db7faf53e1f2, and should resolve #556.

Backport (and add to) fixes for latest MSVC 2015/2017 updates

---

Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/hsWindows.h
Sources/Plasma/PubUtilLib/plInputCore/plInputManager.cpp

Quoth @Deledrius 
Windows 10 Fall Creators Update changed the behavior of SetCursorPos, which no longer sends the expected WM_MOUSEMOVE message when recentering the cursor.  This adds a function to detect affected versions of Windows and flags the necessity to manually send our own message.
This workaround currently only detects the known affected version of Win10, in the hope that it will be fixed and no further attention will be required.  If this regression is not fixed, additional Win10 versions can be added.

Add workaround for mouse handling bug in Win10 FCU

---

Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/hsWindows.h
Sources/Plasma/PubUtilLib/plInputCore/plInputManager.cpp

This switches over to using the recently-added `hsGetWindowsVersion` for `DisplaySystemVersion`.  I also modified `hsGetWindowsVersion` to use `RTL_OSVERSIONINFOEXW` instead of `RTL_OSVERSIONINFOW` as it contains necessary information.
`DisplaySystemVersion` no longer parses information for Win95/Win98/WinME as those are not supported and are not needed.

Update Windows version identification.

---

Sources/Plasma/FeatureLib/pfPython/pyImage.cpp
Sources/Plasma/FeatureLib/pfPython/pyImage.h
Sources/Plasma/FeatureLib/pfPython/pyImageGlue.cpp
Sources/Plasma/PubUtilLib/plGImage/plPNG.cpp
Sources/Plasma/PubUtilLib/plGImage/plPNG.h

By default, this addition inserts the client version and a timestamp into every image saved.  Other fields such as Explorer, Current Age, etc. are context-dependent and can be added by the caller.
Localized strings are possible, but as we don't have any translations for them I did not implement it in this changeset.

Add support for saving optional text chunks to PNG images.

---

Sources/Plasma/FeatureLib/pfMoviePlayer/plMoviePlayer.cpp

As I've removed the intro videos in my testing installation to reduce startup time, this is a really irritating assertion and isn't especially useful.  If there's any utility to be had, it's as a notice in the `movie.log` file.

Remove unnecessary assertion.

---

CMakeLists.txt

`set_property(CACHE ...)` must refer to an existing cache variable. This
means it must be created before the properties are set on it. Without
this change, running `cmake` the first time fails on my machine, and
then succeeds when run the second time.

Don't error on a clean CMake build

---

Sources/Plasma/PubUtilLib/plGImage/plPNG.cpp

libpng's support for the `iTXt` chunk ('international textual data') is
optional, and off-by-default before libpng 1.4, which causes a compile
error. This writes an iTXt chunk only if supported, and writes a tEXt
chunk otherwise. (A tEXt chunk is identical but specified to contain
Latin-1 text instead of UTF-8, and has no language tag.)

Support libpng with no iTXt chunk support

---

Sources/Plasma/Apps/plUruLauncher/plClientLauncher.cpp
Sources/Plasma/Apps/plUruLauncher/plClientLauncher.h
Sources/Plasma/Apps/plUruLauncher/winmain.cpp

Fixes an issue in which the `-NoSelfPatch` flag is ignored if a patcher is found in the client manifest. Also addresses the issue of the patcher not exiting correctly in some situations.

Patcher fixes

---

Sources/Plasma/PubUtilLib/plInputCore/plInputManager.cpp

Cursor bug is still present in Windows 10 April 2018 Update 😢

Windows 10 Cursor (Part II)

---

Sources/Plasma/PubUtilLib/plPipeline/GL/plGLDevice.h

This adds the necessary declarations needed for successful compilation
with OpenGL. It doesn't define them - none of the declarations in this
class are defined, it looks like this is all unfinished stub code.

Fix compiling with OpenGL

---

Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/NucleusLib/pnEncryption/CMakeLists.txt
Sources/Plasma/NucleusLib/pnEncryption/plChallengeHash.cpp
Sources/Plasma/NucleusLib/pnEncryption/plChecksum.cpp
Sources/Plasma/NucleusLib/pnEncryption/plChecksum.h
Sources/Plasma/NucleusLib/pnEncryption/plSha0.cpp
Sources/Plasma/NucleusLib/pnEncryption/plSha0.h
Sources/Tests/NucleusTests/pnEncryptionTest/CMakeLists.txt
Sources/Tests/NucleusTests/pnEncryptionTest/test_plMD5Checksum.cpp
Sources/Tests/NucleusTests/pnEncryptionTest/test_plSHA1Checksum.cpp
Sources/Tests/NucleusTests/pnEncryptionTest/test_plSHAChecksum.cpp

Based on H-uru/dirtsand#130 and H-uru/libhsplasma#120, but reworked to fit the stream-based hashing style that Plasma uses for its checksums.

Add a SHA-0 implementation to work around its removal in OpenSSL 1.1.

---

Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/winmain.cpp

If we don't do this, `EVP_get_digestbyname` returns null and the game crashes on startup.

Ensure OpenSSL EVP digests are initialized

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfSurface/plGrabCubeMap.cpp
Sources/Plasma/FeatureLib/pfSurface/plGrabCubeMap.h

Previously, the console command Graphics.Renderer.GrabCubeCam would use the prefix "(null)" due to a copypasta error. Saved cubemaps are now stored in their own directory in the game app data directory and compressed as PNGs instead of lossy JPEGs.

Improve cubemap console commands

---

Sources/Plasma/NucleusLib/pnUtils/pnUtList.h

Intrusive linked lists should never be copied. The copy constructor and operator were effectively disabled previously, but this is a more correct way to ensure copy code is never generated for list elements.

Fix fake deleted methods in pnUtList

---

cmake/FindDirectX.cmake

Older versions of Visual Studio neither provide nor need the wrapper for stdio backwards-compatibility.  This fixes a link error on pre-2015 VS introduced by 0df2b8b98b052e880c3e.
See also:
https://stackoverflow.com/a/32418900
https://msdn.microsoft.com/en-us/library/bb531344.aspx

Don't link against legacy library in older versions of Visual Studio.

---

Sources/Plasma/Apps/plPythonPack/PythonInterface.cpp
Sources/Plasma/CoreLib/plFileSystem.cpp

Any `path` other than "." was failing to check the correct location for sub-directory statistics, returning incorrect results.
Also includes a minor fix for using the full local system path.

plPythonPack fixes.

---

Sources/Plasma/Apps/plPythonPack/PythonInterface.cpp
Sources/Plasma/Apps/plPythonPack/PythonInterface.h
Sources/Plasma/Apps/plPythonPack/main.cpp

Adds a new option to silence non-error output messages.  A new option parser was added to accommodate this, while being backward-compatible with existing option allowances.
Also removes a few vestigial functions which have been left unused for some time.

Add Quiet option to silence output from plPythonPack.

---

appveyor.yml

As suggested by @Hoikas, this causes curl to be built using SSPI on Windows instead of OpenSSL for supporting HTTPS connections.

Use SSPI when building curl in AppVeyor config.

---

Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/CoreLib/hsBitVector.h
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp
Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp
Sources/Plasma/NucleusLib/inc/plProfileManager.cpp
Sources/Plasma/NucleusLib/pnMessage/plMessage.cpp
Sources/Plasma/NucleusLib/pnNetCommon/plSynchedObject.cpp

This changeset attempts to silence and/or fix some of the warnings emitted during compilation. When I began, 406 warnings were being emitted in my build. It is now down to 313 warnings. I avoided fixing uninitialized members to prevent conflicts with #576.

Assorted Warning Cleanup

---

Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/winmain.cpp
Sources/Plasma/NucleusLib/pnEncryption/plChecksum.cpp

In particular, this fixes running the pnEncryption unit tests, which currently do not do the mandatory OpenSSL initialization dance routine.

Move OpenSSL initialization closer to point of use

---

Sources/Plasma/PubUtilLib/plPipeline/DX/plDXEnumerate.h

Additional uses of std::min run into conflicts with Windows headers in plDXEnumerate.cpp.  This excludes the braindead Windows macro.

Fix newly uncovered issue with string_theory 3.0

---

Sources/Plasma/PubUtilLib/plAudio/plVoiceCodec.cpp

Sad. We can always change it back if/when we upgrade to VC++2015...

VC++2013 does not support constexpr scalars.

---

cmake/Find3dsm.cmake

This changes 3dsm_PATH to point to the actual SDK directory, rather than a directory containing the SDK directory.

Don't rely on the Max SDK being in a specific directory name.

---

Sources/Plasma/FeatureLib/pfPython/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPython/Pch.h
Sources/Plasma/FeatureLib/pfPython/cyAccountManagement.cpp
Sources/Plasma/FeatureLib/pfPython/cyAccountManagement.h
Sources/Plasma/FeatureLib/pfPython/cyAccountManagementGlue.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue2.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.h
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.h
Sources/Plasma/FeatureLib/pfPython/plPythonSDLModifier.cpp
Sources/Plasma/FeatureLib/pfPython/pyObjectRef.h
Sources/Plasma/NucleusLib/pnKeyedObject/plKeyImp.h

This was originally intended to be a set of changes to rewrite the glue.py file in C++. However, things got a little out of hand in the associated cleanups, so here they are instead. They include:
- A huge sweep of code style cleanups in plPythonFileMod and plPythonSDLModifier
- Rewriting the instance method calling code in plPythonFileMod to use variadic templates for ease of use
- Cleaning up some of the PyObject* reference management
- A handful of string cleanups
This depends on H-uru/moul-scripts#110

pfPython Cleanups

---

Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/plClientLauncher.cpp

cURL does not follow redirects by default, meaning the Gehn launcher
is currently printing the raw HTML of a 301 response.

Follow redirects when fetching server status.

---

Sources/Plasma/FeatureLib/pfCamera/CMakeLists.txt
Sources/Plasma/PubUtilLib/plAudio/plAudioSystem.cpp
Sources/Plasma/PubUtilLib/plAudio/plAudioSystem.h
Sources/Plasma/PubUtilLib/plAudio/plVoiceChat.h
Sources/Plasma/PubUtilLib/plPipeline/CMakeLists.txt
Sources/Tests/FeatureTests/pfPythonTest/CMakeLists.txt

OpenAL Soft 1.20 changed the ALCdevice and ALCcontext typedefs.
Since the `<alc.h>` header is very small and does not include any other headers, we can just include it directly where necessary instead of trying to forward-declare the types.

Fix compatibility with OpenAL Soft 1.20

---

Sources/Plasma/FeatureLib/pfPython/Pch.h
Sources/Plasma/FeatureLib/pfPython/pyVaultAgeInfoNode.cpp

This fixes an observed issue in the Nexus where the entry for the GreatTreePub was listed as " Watcher's Pub". It also corrects a potential ugly description generation issue when instances are generated by the server with no user name. Previously this would be " (1) Ae'gura" -- this has been changed to "Ae'gura(1)". This issue should never be triggered.

Fix potential whitespace prepend to age descriptions

---

Sources/Plasma/PubUtilLib/plResMgr/plResManager.cpp
Sources/Plasma/PubUtilLib/plResMgr/plResManager.h

This was removed when the page list was converted to an `std::map`. However, not checking for conflicting sequences causes a deadlock on loading an age that had a PRP renamed without changing its sequence suffix.

Restore sequence conflict verification.

---

Sources/Plasma/PubUtilLib/plNetClient/plNetLinkingMgr.cpp

Visual C++ ASan points out these destructors should be virtual. There is still an issue with an out of scope access around `pfGUITextBoxMod::IUpdate` and `plLocalization::StringToLocal` that I wasn't sure how to fix.

ASan-directed Destructor Fixes

---

Sources/Plasma/PubUtilLib/plDrawable/plGBufferGroup.cpp
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXDeviceRefs.cpp
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXTextureRef.h

This fixes issues with the texture and vertex buffer memory display. Previously, they displayed values that indicated underflow.

Fix some stats displays.

---

Sources/Plasma/FeatureLib/pfPython/pyVaultAgeInfoNode.cpp

This fixes the lack of a space between the age's user name ("Adam's") and the age instance name ("Teledahn") if the sequence number is zero introduced in #619.

Fix age description spacing.

---

Sources/Plasma/Apps/plClient/external/CMakeLists.txt

This fixes the current behavior where the `resource.dat` file would always be rebuilt even if it had already been created and the dependencies had not changed, due to use of the wrong output directory in the CMake configuration.
It also adds the existing source groups (containing the scripts and images) as Sources for the custom target so that they are displayed and editable in Visual Studio.

Client Resource build enhancements.

---

Sources/Plasma/PubUtilLib/plClientResMgr/plClientResMgr.cpp
Sources/Plasma/PubUtilLib/plClientResMgr/plClientResMgr.h
Sources/Plasma/PubUtilLib/plPipeline/plDTProgressMgr.h
Sources/Plasma/PubUtilLib/plProgressMgr/plProgressMgr.cpp
Sources/Plasma/PubUtilLib/plProgressMgr/plProgressMgr.h

This fixes a long-standing crash which could occur if using a different `resource.dat` than one the client was hard-coded to expect.  Previously, the number of frames was dictated at compile-time.  This change allows the plProgressMgr to query for the list of resources, find the ones matching the given pattern, and subsequently use that sorted list as the IDs from which it builds and cycles the animation.

Remove hard-coded framecount for linking progress animation.

---

Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp

When linking to Relto, the avatar opens his/her Relto book. In Path of the Shell, the avatar would close the book when linking in to Relto. This corrects the hardcoded link-in animation name such that the correct behavior from PotS is restored.

Fix Relto link-in regression from PotS.

---

Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp

This prevented imagers with one item from updating due to local changes.
This can be easily observed by looking at the Kirel visitor's list. It is more apparent in the new Guild of Messenger's pub where the visitor's list imager is facing the player when they link in.

Ensure NodeSave callbacks go out for all node changes.

---

Sources/Plasma/CoreLib/hsTemplates.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIPopUpMenu.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIPopUpMenu.h

Ensure hsTArray::SetCountAndZero/ExpandAndZero are only used on trivially copyable types where it is safe to do so.  Fixes one use case which was previously unsafe (memsetting a std::wstring)

Make hsTArray::SetCountAndZero safer.

---

Sources/Plasma/FeatureLib/pfPython/pyVaultNodeGlue.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/pnNpCommon.h

The Cyan standard function did not properly handle comparing vault nodes with incompatible types, which is expected to return False. Instead, they tried to return an exception. Unfortunately, they did this incorrectly by returning a value of -1, which was interpreted to be a result of True.
This resulted in interesting things like `node == "Ahnonay"` evaluating to True. See also H-uru/moul-scripts#120

Fix ptVaultNode's richcompare function.

---

README.md
Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plUruLauncher/CMakeLists.txt
prepare_env.ps1

* Update documentation to refer to MSVC 2017 instead of 2015
* Update documentation and prepare_env.ps1 for new devlibs
* Fix apps that link against libcurl to now also link wldap32

Updates for MSVC 2017

---

Sources/Plasma/FeatureLib/pfPython/cyMiscGlue4.cpp

This is to facilitate H-uru/moul-scripts#119.
`PtDebugPrint()` now outputs to a single line and accepts the keyword argument `sep`, which functions in the same manner as Python 3's sep keyword argument. ~~The `end` keyword argument was not added.~~ Known limitation: the `end` argument cannot be used to elide newlines.
I have also fixed a memory leak in which the repr of a PyObject was not decref'd.

Change `PtDebugPrint` to behave more like Py3 `print`.

---

CMakeLists.txt
Sources/Plasma/CoreLib/hsAlignedAllocator.hpp
Sources/Plasma/PubUtilLib/plDrawable/plDrawableSpans.cpp
Sources/Plasma/PubUtilLib/plDrawable/plVisLOSMgr.cpp
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp
Sources/Tools/MaxMain/plMaxNode.cpp

* Compatibility fixes with changed/removed features
* Use C++17's built-in aligned `operator new` instead of platform-specific memory allocation in `hsAlignedAllocator`
TODO: Python 2.7's headers now spit out a bunch of warnings due to the deprecation of the `register` keyword in C++17

Updates for C++17

---

Scripts/Python/kdshPillarRoom.py
Scripts/Python/kdshShadowPath.py
Scripts/Python/kdshTreeRingsSolution.py
Scripts/Python/kdshVault.py
Scripts/Python/minkDayClicks.py
Scripts/Python/minkSymbols.py
Scripts/Python/tldnShroomieBrain.py
Scripts/Python/xCheat.py

This removes all uses of the `exec()` function from the Python scripts. This fixes an observed traceback in Python 3 related to exec statements with side effects. The code is also much cleaner as a result.
cPythScopeSolution - Traceback (most recent call last):
File ".\python\kdshTreeRingsSolution.py", line 241, in OnServerInitComplete
self.InitRings()
File ".\python\kdshTreeRingsSolution.py", line 276, in InitRings
ffcode2 = i + "Ring0" + j + "_0" + str(InitState) + ".animation.skipToEnd()"
NameError: name 'InitState' is not defined

Kill `exec(code)`

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIProgressCtrl.h
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue3.cpp
Sources/Plasma/PubUtilLib/plAvatar/plCoopCoordinator.cpp
Sources/Plasma/PubUtilLib/plMessage/plTimerCallbackMsg.h
Sources/Plasma/PubUtilLib/plModifier/plResponderModifier.cpp
Sources/Tools/MaxComponent/plResponderLink.cpp

This issue was exposed by #601. The Relto bahro pole smokers would intentionally use a negative value as the timer callback ID. While this is strictly speaking not kosher according to the `PtAtTimeCallback` docstring, the implementation gladly accepted signed integers. Additionally, throughout the code, -1 was used as a magic value. Therefore, we fix everyone to use signed integers for timer callback IDs. plPythonFileMod is now correctly passing signed values to the PFM's `OnTimer` method.
Fixes the observed Relto traceback:
(05/17 16:02:38) cPythBahroPoles - Traceback (most recent call last):
(05/17 16:02:38)   File ".\python\psnlBahroPoles.py", line 679, in OnTimer
(05/17 16:02:38)     self.RunState(self.PoleIDMap[ageID], state, 0)
(05/17 16:02:38) KeyError: 429496729

Let the Bahro Smoke in Peace.

---

.github/workflows/linux-ci.yml
README.md
Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/external/CMakeLists.txt
Sources/Plasma/Apps/plClient/external/Linking_Book.svg
Sources/Plasma/Apps/plClient/external/create_resource_dat.py
Sources/Plasma/Apps/plClient/external/render_svg.py
Sources/Plasma/Apps/plClient/external/requirements.txt
appveyor.yml
cmake/FindPythonModule.cmake
requirements.txt

This updates the resource.dat creation to render the SVG assets using a newer, maintained Python module "CairoSVG" instead of relying on the Pycairo/rsvg pair which is no longer actively maintained for Python on Windows.  Also included are a few Python 3.x+ fixes which should allow the scripts and build system to function with the newer interpreter.
This is a foundation for fixes coming in #650.

Update resource-building scripts for future compatibility.

---

Scripts/Python/xPsnlVaultSDL.py

Observed when trying to gain a Guild RFID T-Shirt.

Fix traceback-causing typo in xPsnlVaultSDL.py.

---

appveyor.yml

AppVeyor has a maximum total artifact storage limit, and apparently no way to manually clean out old builds (though they are pruned automatically after 6 months)...
This can be re-enabled when some older builds expire, or if we switch to GH actions

Disable artifacts on AppVeyor build.

---

Scripts/dat/AhnonayCathedral.fni

This fixes white seams visible in the Ahnonay Cathedral by setting the render clear color to black.
Enlarge to see the difference better!

Fix Ahnoying Cathedral Seams

---

Scripts/Python/ki/xKIHelpers.py

This builtin was removed in Python 3.
This is a bit of a rewrite of the function to make it less verbose. Note that it is not possible for `ptVaultNodeRef.getChild()` to return `None`, so that check was removed.

Kill another use of `cmp()`.

---

Sources/Plasma/FeatureLib/pfPython/pyVaultNodeGlue.cpp

The ptVaultNode rich comparison function had logic error that would cause `ptVaultNode` instances to be interpreted as a `PyInt`, raising a seemingly untracable `SystemError`. This fixes that by greatly simplifying the logic by virtue of assuming that the left hand argument of a rich comparison is of type `ptVaultNode`.
This issue was observed when trying to edit user-created marker quests on Py3.

Fix logic error introduced in #642.

---

Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/winmain.cpp
Sources/Plasma/NucleusLib/pnDispatch/plDispatch.cpp

This does **not** make the client build for Win64, but it does resolve some compiler errors about x86-isms. I've confirmed that these changes build successfully on Win32 as well.

Some minor Win64 fixes

---

prepare_env.ps1

By default, this will use the existing folder name "build", but that can
be overridden by calling the script with a `-builddir` option.
Example:
```powershell
.\prepare_env.ps1 -builddir build_vs2019
```
I suppose to really feel like powershell it should be `-Build-Output-Folder`, but `-builddir` is so much nicer 😛

Allow specifying build dir for prepare_env

---

Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore_Mac.cpp

The other platforms all include `<string_theory/format>` but we don't actually need to do any formatting here

Fix missing include for pfPasswordStore on macOS

---

CMakeLists.txt
Sources/Plasma/FeatureLib/pfPasswordStore/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore.cpp
Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore_Apple.cpp
Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore_impl.h
Sources/Plasma/NucleusLib/pnAsyncCoreExe/Pch.h
Sources/Plasma/NucleusLib/pnNetCli/Pch.h
Sources/Plasma/NucleusLib/pnNetProtocol/Pch.h
Sources/Plasma/NucleusLib/pnUtils/Pch.h
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Pch.h
Sources/Plasma/PubUtilLib/plVault/Pch.h

Reasons this is better:
1. Apple renamed their operating system.
2. It's the same character length as `WIN32` and `LINUX`.
`HS_BUILD_FOR_APPLE` covers Apple systems that are technically not macOS, but that's not an intended area of support.

HS_BUILD_FOR_OSX -> HS_BUILD_FOR_MACOS

---

Sources/Plasma/FeatureLib/pfCamera/plVirtualCamNeu.cpp

* The (disabled) extra status logging calls weren't using the right method on plStatusLog to format strings
* The effect plate (which is used to make the camera display black when rendering is turn off) was seemingly incorrectly gated behind the same check for additional logging

pfCamera logging fixes

---

Sources/Plasma/CoreLib/HeadSpin.cpp

This gives us the kernel version and machine architecture.
ex: `Linux 5.7.6-arch1-1 (x86_64)`
Note that on macOS, this will return "Darwin" and the Darwin kernel version, rather than the (more useful) macOS product version. I looked into getting that info as a second item in the returned vector, but the easy way to do it involves private Apple APIs and the less-easy way to do it involves using CoreFoundation to parse plist files and extract values from a dictionary. Not impossible, but not exactly fun either.

Return uname info for DisplaySystemVersion on *nix

---

Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIConstants.py

Adds new Easter Eggs (feathers) and Constants for Fan Ages.
- Adds yellow, raven and dove feathers for GoMePubNew, Chiso, and Veelay respectively.
- Adds proper name constants for Fehnir's House, GoMePubNew, Chiso and Veelay.
- Adds /look comments for GoMePubNew and Chiso.
- Adds GoMePubNew, Chiso and Veelay to "No Invite" list.
- (proposed) Takes out unneeded "The" from some of the Age Name constants to help them display better in areas of the KI. While it does appear to cut off the latter part of the text in lists, this should eliminate instances where the Age name only displays as "The...".

KI Easter Egg Updates/Age Constants

---

Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIConstants.py

Per the feature request submitted to OpenUru (http://forums.openuru.org/viewtopic.php?f=92&p=9831), this implements two dice commands, one generic that expects a common dice notation string, and another that rolls a set of four fate/fudge dice.
The two recommended dice libraries, while promising, require a newer version of Python than the engine currently supports.  Instead, a naïve implementation that only supports a single notation is provided.

Add dice commands to KI chat.

---

.github/workflows/linux-ci.yml

This also fixes the warning about apt not having a stable interface.

Fix Linux-CI failures.

---

Sources/Plasma/FeatureLib/pfCamera/plVirtualCamNeu.cpp
Sources/Plasma/FeatureLib/pfCamera/plVirtualCamNeu.h

The effect plate was effectively unused until #679. Fixing it to not be gated behind the status log introduced a regression in which the spinning dots and intro video were hidden.

Remove pfVirtualCam1 Effect Plate.

---

Sources/Plasma/NucleusLib/pnFactory/plFactory.cpp

What's more useful than `"Invalid class index or nil creator : plFactory::Create()"`?
An error message that gives you some sort of indication what the class index was!

Print the invalid class index in plFactory assert

---

Sources/Plasma/PubUtilLib/plModifier/plLogicModifier.cpp

We have PubUtilLib code depending on FeatureLib code solely for the purpose of printing a slightly nicer debugging message based on what type of conditional is involved. We can avoid the dependency in this scenario if we just print the class name of the conditional instead.
(Note: There's another spot where plLogicModifier depends directly on pfConditional to implement 2 console commands at the bottom of the file. I'm thinking it might be best to add a new message type for propagating those to the conditionals?)

Remove some cross-folder includes from plLogicMod

---

Sources/Plasma/PubUtilLib/plGImage/plFont.cpp

Some font have characters with a negative baseline (usually the underscore character). When multiplied with the (unsigned) stride, this was turning into a value in the vicinity of UINT32_MAX and that gets subtracted from the pointer into the texture image data. In this case, it was going out of bounds and causing the client to segfault.
In reality, `fDestStride` is generally the width of the texture × 4 (bpp), so it's very unlikely that this will ever exceed the capacity of a signed 32-bit int.

Handle font characters with negative baselines

---

Sources/Plasma/CoreLib/hsMatrix44.cpp
Sources/Plasma/CoreLib/hsQuat.h

At some point, `hsQuat::FromMatrix44()` was changed to a static method, but `hsMatrix44::DecompRigid()` was not updated and continued to use it as a member method. This resulted in the quaternion being discarded immediately.
In the interest of preventing these sorts of bugs in the future, I added C++17's `[[nodiscard]]` attribute where it made sense in `hsQuat`.
Required by PhysX 4.1.

Fix `hsMatrix44::DecompRigid()` quat decomposition.

---

Sources/Plasma/CoreLib/hsTemplates.h

Apparently these are in the wrong spot in the header file, and clang complains.
<pre>In file included from <font color="#FFFFFF"><b>/home/dpogue/Coding/Plasma/Sources/Plasma/PubUtilLib/plPipeline/GL/plGLPipeline.cpp:52</b></font>:
/home/dpogue/Coding/Plasma/Sources/Plasma/PubUtilLib/plPipeline/../../CoreLib/hsTemplates.h: In instantiation of ‘<font color="#FFFFFF"><b>hsLargeArray&lt;T&gt;&amp; hsLargeArray&lt;T&gt;::operator=(const hsLargeArray&lt;T&gt;&amp;) [with T = short int]</b></font>’:
<font color="#FFFFFF"><b>/home/dpogue/Coding/Plasma/Sources/Plasma/PubUtilLib/plPipeline/../../PubUtilLib/plPipeline/plCullTree.h:64:7:</b></font>   required from here
<font color="#FFFFFF"><b>/home/dpogue/Coding/Plasma/Sources/Plasma/PubUtilLib/plPipeline/../../CoreLib/hsTemplates.h:1025:29:</b></fon …

Move some hsLargeArray helpers to fix compiling

---

Sources/Plasma/NucleusLib/pnMessage/plCorrectionMsg.h

Fixes a compilation error in clang when initializing a `plCorrectionMsg` from an rvalue.
@dpogue Can you check this with #690?

Fix plCorrectionMsg ctor compilation in clang.

---

Sources/Plasma/PubUtilLib/plNetClient/plLinkEffectsMgr.cpp
Sources/Plasma/PubUtilLib/plNetClient/plLinkEffectsMgr.h

Fixes inconsistent and incorrect spelling for "pseudo" in plLinkEffectsMgr.

Fix typos in plLinkEffectsMgr.

---

CMakeLists.txt
Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/FeatureLib/pfLocalizationMgr/CMakeLists.txt
Sources/Tests/FeatureTests/pfPythonTest/CMakeLists.txt
Sources/Tools/MaxMain/CMakeLists.txt
Sources/Tools/plLocalizationEditor/CMakeLists.txt

As of libexpat 2.2.8, the library was renamed from libexpat to expat. In 2.2.9, this was supposedly reverted back to libexpat; however, in practice, I find that vcpkg builds libexpatMD. Therefore, we now use libexpat's config. However, this is not present in the most recent devlibs bundle with expat 2.2.7, so we fall back on the out of date cmake find module in that case.
This should fix the latest CI failure in #702.

Fix fallout from upstream libexpat library rename.

---

CMakeLists.txt
Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/FeatureLib/pfLocalizationMgr/CMakeLists.txt
Sources/Tests/FeatureTests/pfPythonTest/CMakeLists.txt
Sources/Tools/MaxMain/CMakeLists.txt
Sources/Tools/plLocalizationEditor/CMakeLists.txt
appveyor.yml

(Moved from #701 due to being in the wrong fork and thus duplicating builds)
The vcpkg cache contains old, stale versions of several packages, which do not get updated automatically by vcpkg install. This ensures they get updated before installing new packages.
This now also removes the old manually-created x86-windows-static-dyncrt triplet in favor of the upstream-supported x86-windows-static-md triplet.

Update packages in vcpkg cache

---

Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp

This was observed in a 2x2 DXT1 mipmap produced by Korman. While Korman should probably force such a thing to be uncompressed, the pipeline should also not be able to enter such an obviously invalid state.

Fix an infinite loop in plDXPipeline.

---

Scripts/Python/nxusBookMachine.py

This issue seems to only affect Cyan's server (aka MOULa). Per Susa'n, the Cavern Events Hood [sic] on MOULa will only appear in the Nexus when the Age is occupied. Once the last player leaves the Age, it is removed from the list. Upon further investigation by @cwalther and myself, we determined that the server is incorrectly reporting the owner count of the "b0rked" Neighborhoods as zero. On a quick investigation, we found three affected Neighborhoods currently in the list on MOULa. However, more Neighborhoods are known to be affected.
Per discussion on discord, it makes more sense to NOT filter Neighborhoods in this way in the Nexus. Rather, we should simply allow natural selection to cull inactive Neighborhoods from the list.

Fixed b0rked hoods on MOULa.

---

Scripts/CMakeLists.txt

This makes it easier to find, browse, and edit the files now included in the recently-added Scripts project.

Add source groups for game scripts and associated files.

---

Scripts/Python/xLinkingBookGUIPopup.py

This fixes the issue by which the linking responder in a non-bookshelf book is not properly synchronized to remote players. Previously, On the local machine, the player sees him or herself placing his/her hand on the page and linking out. On the remote machine, an avatar walks up to the linking book and links away without touching the page.
This was especially obvious when Chiso Preniv was released on Gehn and during the big August event on MOULa. Both Cyan and Korman generated Ages are affected by this issue.

Fix non-synchonized link out animation.

---

Sources/Plasma/FeatureLib/pfPython/Pch.h
Sources/Plasma/FeatureLib/pfPython/cyAccountManagement.h
Sources/Plasma/FeatureLib/pfPython/cyAccountManagementGlue.cpp
Sources/Plasma/FeatureLib/pfPython/cyAvatar.h
Sources/Plasma/FeatureLib/pfPython/cyAvatarGlue.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue2.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue3.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue4.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.h
Sources/Plasma/FeatureLib/pfPython/plPythonSDLModifier.h
Sources/Plasma/FeatureLib/pfPython/plPythonSDLModifierGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyDrawControl.h
Sources/Plasma/FeatureLib/pfPython/pyDrawControlGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIDialog.h
Sources/Plasma/FeatureLib/pfPython/pyGUIDialogGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyGlueHelpers.h
Sources/Plasma/FeatureLib/pfPython/pyImage.h
Sources/Plasma/FeatureLib/pfPython/pyImageGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyJournalBook.h
Sources/Plasma/FeatureLib/pfPython/pyJournalBookGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pySpawnPointInfo.h
Sources/Plasma/FeatureLib/pfPython/pySpawnPointInfoGlue.cpp
Sources/Tools/plShaderAssembler/CMakeLists.txt

This fixes two issues when trying to use VLD with the current code:
- Fixes missing target link library for plShaderAssembler, preventing linking.
- Fixes a crash on exit caused by the builtin Plasma python modules, triggering VLD to think all memory had been leaked. You get quite a bit of bonus code cleanup here.

Fix some issues with VLD Usage.

---

Sources/Plasma/FeatureLib/pfPython/pyGlueHelpers.h

Per [bpo-40170](https://bugs.python.org/issue40170), we need to eventually start thinking about `PyTypeObject` as an opaque structure. That means going through and using type specs to initialize types on the heap. This would actually be a good thing because the code is cleaner. But, for now, the quick fix.

Fix `PyTypeObject` helpers for Python 3.9.

---

Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/CoreLib/hsRefCnt.h
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/FeatureLib/pfPython/pyAgeVault.cpp
Sources/Plasma/FeatureLib/pfPython/pyVault.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultAgeInfoNode.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultNode.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultNode.h
Sources/Plasma/FeatureLib/pfPython/pyVaultNodeRef.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultNodeRef.h
Sources/Plasma/FeatureLib/pfPython/pyVaultNodeRefGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultPlayerInfoListNode.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvatarClothing.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.h
Sources/Plasma/PubUtilLib/plVault/plVaultNodeAccess.h

This adds an `hsWeakRef` class which makes (lack of) ownership more clear in several APIs.  Furthermore, construction of an `hsRef` from a raw pointer is now disallowed.  You must either convert it to an `hsWeakRef` (which gets reffed when converted to an `hsRef`, matching the old conversion behavior), or steal it with the APIs added in #625.
In the process, this should plug a couple more leaks, but should be tested to ensure I didn't accidentally plug something that wasn't a leak.

Further work on `hsRef`

---

appveyor.yml

vcpkg was refusing to rebuild/install new packages because it wants the `--recurse` option (in order to rebuild freetype).

Fix CI regression

---

Sources/Plasma/Apps/plClient/external/CMakeLists.txt
Sources/Plasma/Apps/plClient/external/makeres.py
Sources/Plasma/Apps/plClient/external/requirements.txt

This fixes our cairosvg dependency such that `pip install -r requirements.txt` works without undocumented dependencies. Further, some invalid assumptions have been corrected in makeres.py. Namely that: the python executable is named exactly `python` and that `pngcrush` is available when building an external client. This should also fix an issue where CMake would error if `CMAKE_RUNTIME_OUTPUT_DIRECTORY` is a generator expression.

Fix issues with resource.dat generation on Windows.

---

Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore.cpp
Sources/Plasma/PubUtilLib/plAgeLoader/plAgeLoader.cpp
Sources/Plasma/PubUtilLib/plInputCore/plInputInterfaceMgr.cpp

Replace hardcoded backslashes with `plFileName::Join`

Fix Windows-specific path separators

---

Sources/Plasma/FeatureLib/pfAnimation/CMakeLists.txt
Sources/Plasma/FeatureLib/pfAudio/CMakeLists.txt
Sources/Plasma/FeatureLib/pfGameGUIMgr/CMakeLists.txt
Sources/Plasma/FeatureLib/pfLocalizationMgr/CMakeLists.txt
Sources/Plasma/FeatureLib/pfMoviePlayer/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPatcher/CMakeLists.txt
Sources/Plasma/PubUtilLib/plAudio/CMakeLists.txt
Sources/Plasma/PubUtilLib/plDrawable/CMakeLists.txt
Sources/Plasma/PubUtilLib/plGImage/CMakeLists.txt
Sources/Plasma/PubUtilLib/plGLight/CMakeLists.txt
Sources/Plasma/PubUtilLib/plInterp/CMakeLists.txt
Sources/Plasma/PubUtilLib/plIntersect/CMakeLists.txt
Sources/Plasma/PubUtilLib/plMessage/CMakeLists.txt
Sources/Plasma/PubUtilLib/plModifier/CMakeLists.txt
Sources/Plasma/PubUtilLib/plNetClient/CMakeLists.txt
Sources/Plasma/PubUtilLib/plNetCommon/CMakeLists.txt
Sources/Plasma/PubUtilLib/plPipeline/CMakeLists.txt
Sources/Plasma/PubUtilLib/plResMgr/CMakeLists.txt
Sources/Plasma/PubUtilLib/plSDL/CMakeLists.txt
Sources/Plasma/PubUtilLib/plSurface/CMakeLists.txt

This is (very clearly) not all of the linking that needs to be done, but this is what I'd been carrying on my plGLClient branch to make it compile and link on Linux.
It seems better for these to exist on master, imperfect they may be, than to have them mixed in with GL pipeline work.

Add some target_link_libraries

---

Sources/Plasma/FeatureLib/pfPython/pyEnum.cpp
Sources/Plasma/FeatureLib/pfPython/pyGlueHelpers.h

`tp_print` is unused since Python 3.0, and removed in Python 3.9.  There was only one actual use of it, and that class already has a `repr` implementation which will be used instead.

Remove remaining references to tp_print

---

Sources/Tests/CMakeLists.txt

This setting was being overridden in GTest's CMakeLists.txt. While this was generally not too terrible, if the vcpkg toolchain is in use and X_VCPKG_APPLOCAL_DEPS_INSTALL was enabled, then the configure process would fail.

Really don't install gtest.

---

Sources/Plasma/FeatureLib/pfPython/plPythonSDLModifierGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyDynamicTextGlue.cpp

Any strings parsed using "et" have to be freed with `PyMem_Free()` - better to just use the new `PyUnicode_STStringConverter` and avoid the implicit conversion from `char*` to `ST::string`.

Fix string memory leaks in pfPython.

---

Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp

This was exposed by a dynamic triangle mesh in Ahnonay Sphere 2. The actual object in question is some kind of dummy object that never appears in Age -- possibly because it starts falling immediately.

Fix PhysX bounds/geometry mismatch.

---

README.md
prepare_env.ps1

This includes the fix for the OpenAL WINMM.lib path, as well as a bump to Python 3.9.0.
This is probably the final devlibs bundle, as we'll be moving to using vcpkg directly: #774 (and related discussion at #736)

Update devlibs bundle to point to latest zip

---

Sources/Plasma/CoreLib/hsTemplates.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.cpp
Sources/Plasma/NucleusLib/pnKeyedObject/plMsgForwarder.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvatarClothing.cpp
Sources/Plasma/PubUtilLib/plDrawable/plAccessGeometry.cpp
Sources/Plasma/PubUtilLib/plDrawable/plDrawableSpans.cpp
Sources/Plasma/PubUtilLib/plPhysical/plPhysicalSndGroup.cpp
Sources/Plasma/PubUtilLib/plScene/plPageTreeMgr.cpp
Sources/Plasma/PubUtilLib/plSurface/plShader.cpp
Sources/Tools/MaxComponent/plAudioComponents.cpp

This also fixes a bug introduced years ago where a call to ExpandAndZero() was replaced with Expand().  The former automatically adjusts the use count, whereas the latter does not :(.

Add a Resize method to hsTArray which performs Expand() + SetCount().

---

.github/workflows/windows-ci.yml

Fixes two observed issues with the Windows CI:
- Runs the install target as a build step so that `python.39.dll` is properly available in the artifact bundle. Vcpkg is internally using `dumpbin.exe` for this but cannot find that executable if cmake is in install mode.
- Avoid caching the Qt install -- the cache can be poisoned if the Qt server goes down. This happened immediately on the merge of #744, causing the GUI tools to be omitted from the CI build.

Fix some minor Windows-CI Issues.

---

cmake/VcpkgToolchain.cmake
vcpkg.json

This completely fixes `-DUSE_VCPKG=ON` on Linux. One thing to be aware of is that many vcpkg ports have dependencies on system packages. If any of these are missing, the configure may error out with a mysterious message like "Build program Ninja not found" or something similar. In this case, you'd need to check the `vcpkg-manifest-install.log` to see what is missing. I find these packages to be the most common stumbling blocks: `autoconf libtool nasm ninja-build`, but there may be others.
I expect this will also completely fix macOS as well, but I can't afford the Apple Tax.

Fix some issues with vcpkg on Linux.

---

Scripts/Python/tldnShroomieGate.py

The state was being modified regardless of whether the gate had power or not, but should only be changed when power is on (and when the relevant responders are run).
Closes #792.

Fix Shroomie Gate state consistency

---

.github/workflows/windows-ci.yml
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.h
cmake/FindVLD.cmake

This is primarily so that the GitHub NuGet cache will be populated with 64-bit versions of the vcpkg packages. We are **not** expecting 64-bit client builds to work, and we are deliberately not saving them as artifacts.

Win64 CI for NuGet caching

---

cmake/FindLIBSECRET.cmake

Fix several issues with libsecret find module:
* Incorrect test for REQUIRED flag
* Incorrect parameter name for REQUIRED flag
* Typo in PkgConfig_FOUND test
* Incorrect capitalization of pkg-config module name
This was clearly never tested, and I unfortunately didn't notice it until recently because I already had a cached copy of the required variables from before it was reworked (and broken) in 9d48c967

Fix several issues with libsecret find module

---

Sources/Plasma/FeatureLib/pfSurface/plLayerAVI.cpp
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXEnumerate.cpp
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXEnumerate.h

It's not safe to treat an HRESULT as a boolean, and Microsoft provides the `FAILED()` macro to specifically check if the result is an error.
In the case of the DirectX Enumerate, it was actually returning bool but the function declaration said it returned an HRESULT.

Fix some HRESULT -> bool conversions

---

Sources/Plasma/NucleusLib/pnNetCli/pnNcUtils.cpp

This causes a crash in MSVC debug builds...

Fix UB advancing/dereferencing an invalid iterator.

---

Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/hsBounds.cpp
Sources/Plasma/CoreLib/plCmdParser.cpp
Sources/Plasma/CoreLib/plFileSystem.cpp

Fixes a bunch of easy spots where there were comparisons between signed and unsigned integers, or where the wrong size of integer was being used

CoreLib warning fixes

---

Scripts/Python/ercaHrvstr.py

The harvester's position was not being properly fast-forwarded if the Age emptied while it was in-transit.

Fix Er'cana Harvester position (#668)

---

cmake/CompilerChecks.cmake

CMake does not by default enable link-time code generation (read: optimizations). This adds the instrumentation to opt-in to such a thing without manual user intervention. This can be turned off by setting `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF`. While I am skeptical that LTCG will offer any significant performance benefit, it does seem like the produced plClient.exe is smaller (down from ~22,000 KB to ~16,000 KB).

Enable the /LTCG switch where applicable.

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Tools/MaxMain/plPythonMgr.cpp

Note: I have not tested the MaxMain one, and I'm not even sure it's still relevant...

Fix Python 3.x compatibility with a couple of inline Python strings.

---

cmake/CompilerChecks.cmake

The gtest subproject currently uses CMake 2.8 compatibility, which only enables IPO (LTCG) for the Intel compiler, and emits an annoying warning for any other configuration, by default.  This fixes both the warning and the IPO enablement for those targets by forcing policy CMP0069 to NEW.

Fix gtest CMake IPO warning on Linux.

---

Sources/Plasma/PubUtilLib/plAvatar/CMakeLists.txt
Sources/Plasma/PubUtilLib/plAvatar/plPhysicalControllerCore.cpp
Sources/Plasma/PubUtilLib/plAvatar/plPhysicalControllerCore.h
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXSimulation.h

When you touch the linking stone in Minkata, it pages the ground out from under you. Because we were not using the ground's smart pointer, we happily dereferenced freed memory (boom). Amusingly, the ground seems to be freed between `IFindGroundCandidate()` and actually using the ground information. At one point, I tried to properly ref and deref the physical object, but that added a lot of bp considering our use of `std::optional<plControllerHitRecord>`.

Use use-after-free issue in Minkata.

---

Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizationDataMgr.cpp
Sources/Tools/CMakeLists.txt
Sources/Tools/plLocalizationBenchmark/CMakeLists.txt
Sources/Tools/plLocalizationBenchmark/main.cpp

This is a minor performance increase to one of the client init hot paths. The goal was to remove lots of data copying. As a bonus, there is now a benchmarking tool for this in plLocalizationBenchmark. I'm OK with removing this tool, but I would like for it to at least live in the repo history somewhere.
I tested before and after on both the MOULa and GULP (aka "hell") localization data sets -- 100 iterations (not 1000), times in seconds:
```csv
,Before Total,After Total
MOULa,12.4428,11.0254
GULP,34.0057,29.9308
,,
,Before Avg,After Avg
MOULa,0.1244,0.1103
GULP,0.3401,0.2993
```
I did try using `std::unordered_map`, but that seemed to cause a performance regression... likely due to the constant iteration over the maps. The only ways to squeeze more out of this code might be to move to a …

More pfLocalizationMgr optimizations.

---

.github/workflows/ci.yml

At this time, the client does not compile on macOS, so running three simultaneous builds for each PR and push is excessive. We only have 5 concurrent macOS jobs available, due to our usage of the free tier.

Don't run the full CI matrix on macOS.

---

Sources/Plasma/NucleusLib/pnAsyncCoreExe/Private/Nt/pnAceNtSocket.cpp

The implementation assumed that `plNetAddress` could be directly cast to a `sockaddr`, which is no longer true.

Fix a regression from #839 which caused SocketGetAddresses to always fail

---

Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClient.h
Sources/Plasma/FeatureLib/pfConsole/pfConsole.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommandsNet.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleCmd.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/CMakeLists.txt
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGameGUIMgr.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGameGUIMgr.h
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp
Sources/Plasma/FeatureLib/pfPython/cyAnimation.cpp
Sources/Plasma/FeatureLib/pfPython/cyAnimation.h
Sources/Plasma/FeatureLib/pfPython/cyAnimationGlue.cpp
Sources/Plasma/PubUtilLib/plAgeLoader/plAgeLoader.cpp
Sources/Plasma/PubUtilLib/plMessage/plConsoleMsg.h

This eradicates some spin-washing of strings from `ST::string` to `char*` back to `ST::string` by removing some uses of `hsStrcpy` in favor of `ST::string` itself. Note this does not remove all uses of `hsStrcpy`.

Kill some C-string spin-washing.

---

Sources/Plasma/PubUtilLib/plNetClient/plLinkEffectsMgr.h
Sources/Tools/MaxConvert/plDistTree.h
Sources/Tools/MaxMain/plAgeDescInterface.h
Sources/Tools/MaxMain/plCommonObjLib.h
Sources/Tools/MaxPlasmaMtls/Layers/plPlasmaMAXLayer.cpp
Sources/Tools/MaxPlasmaMtls/Materials/plAnimStealthNode.h

Coverity builds seem to work again with the latest cov-build, but PCH and unity builds cause the build output to be about 10x larger (and slower to build)...  These changes fix the build with those features disabled.

Add some missing includes required when PCH/unity builds are disabled.

---

Sources/Plasma/PubUtilLib/plAudio/plVoiceChat.cpp
Sources/Plasma/PubUtilLib/plAudio/plVoiceCodec.h

Fixes a missing `delete` and virtual destructor identified by coverity. I would have used `std::unique_ptr`, but it seemed somewhat out of place in context.

Fix resource leaks around voice chat.

---

Sources/Plasma/PubUtilLib/plAudio/plSoundEvent.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp

* Fix an iterator invalidation issue identified by coverity
* Fix an extra `%` character I noticed in the async logs...

Minor fixes

---

Sources/Plasma/FeatureLib/pfPython/cyAccountManagementGlue.cpp
Sources/Plasma/FeatureLib/pfPython/cyAvatarGlue.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue2.cpp
Sources/Plasma/FeatureLib/pfPython/pyCritterBrainGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyDrawControlGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyDynamicTextGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyEnum.cpp
Sources/Plasma/FeatureLib/pfPython/pyEnum.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlButtonGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEditGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyGameScoreGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyGlueHelpers.h
Sources/Plasma/FeatureLib/pfPython/pyJournalBookGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyMarkerMgrGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyMoviePlayerGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyNetLinkingMgrGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyNotifyGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pySDLGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyStatusLogGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultGlue.cpp

The following issues were corrected:
- Fixed a ~hypothetical~ memory leak when adding the enum object to the module fails. (Apparently this leak is not so hypothetical. VLD says this fixes many leaks.)
- Fixed the failure return for EnumValue_hash to actually indicate failure.
- Avoided copying an std::map.
- Replaced an std::map used only for iteration with a vector of tuples.
- Fixed the code style such that I no longer want to stab my eyes out.
Sorry about the noise from all the semicolon removals 😞

Improve pyEnum.

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIHelpers.py

Commands such as /p, /addbuddy, etc. are case-sensitive to names when they shouldn't be.  This change corrects that problem.  Supplements boq's tab to autocomplete names, which is already case-insensitive as it should be.

Allow case-insensitive matching of player names in KI commands

---

Sources/Plasma/CoreLib/CMakeLists.txt
Sources/Plasma/CoreLib/hsCpuID.h
Sources/Plasma/CoreLib/hsMatrix44.cpp
Sources/Plasma/CoreLib/hsMatrix44.h
Sources/Plasma/CoreLib/hsMatrix44_SSE3.cpp
Sources/Plasma/CoreLib/hsSIMD.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp
cmake/CompilerChecks.cmake

This is needed for clang-tidy to be able to parse files built with MSVC.
If the -m(instruction set) flag is not set when compiling a source file, then intrinsics from that instruction set are not available. This means that when parsing a source file that uses, eg, SSE3, then the file will fail to compile. Unfortunately, we can't just turn on every instruction set we want to use because that will allow the compiler to emit the given instruction set anywhere. This will result in fun-to-debug illegal instruction crashes for our end users.
Anyway, if you have a file that needs to compile with gcc, be sure to jail any SIMD code to its own file and add it to the target using `plasma_target_simd_sources(TARGET [instruction set] [files...])`.

Fix SIMD usage on GCC/clang.

---

Sources/Plasma/PubUtilLib/plGLight/plDirectShadowMaster.cpp
Sources/Plasma/PubUtilLib/plGLight/plDirectShadowMaster.h
Sources/Plasma/PubUtilLib/plGLight/plPointShadowMaster.cpp
Sources/Plasma/PubUtilLib/plGLight/plPointShadowMaster.h
Sources/Plasma/PubUtilLib/plGLight/plShadowMaster.cpp
Sources/Plasma/PubUtilLib/plGLight/plShadowMaster.h

hsPoolVector caters to the specific (ab)use of hsTArray's peculiar allocation quirks to reuse items in a pool separately from tracking its
size.  Unlike hsTArray, this class makes the intent clear to the reader, rather than relying on hidden and non-obvious implementation details.
This is currently only used by plShadowMaster and its children.

Introduce hsPoolVector for plShadowMaster's object pools.

---

.clang-tidy
Sources/Plasma/FeatureLib/pfPython/pyEnum.cpp
Sources/Plasma/PubUtilLib/plMessage/plConnectedToVaultMsg.h
Sources/Plasma/PubUtilLib/plMessage/plSpawnModMsg.h
Sources/Plasma/PubUtilLib/plMessage/plSpawnRequestMsg.h
Sources/Plasma/PubUtilLib/plMessage/plTriggerMsg.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXBufferRefs.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXLightRef.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXRenderTargetRef.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXTextureRef.h
Sources/Tools/MaxComponent/CMakeLists.txt
Sources/Tools/MaxConvert/CMakeLists.txt
Sources/Tools/MaxExport/CMakeLists.txt
Sources/Tools/MaxMain/CMakeLists.txt
Sources/Tools/MaxPlasmaLights/CMakeLists.txt
Sources/Tools/MaxPlasmaMtls/CMakeLists.txt
cmake/PlasmaTargets.cmake
cmake/Sanitizers.cmake

This adds first class support for clang-tidy for Makefile, Ninja, and Visual Studio generators. It is loosely based on the implementation found in DIRTSAND. ~~Currently, only the modernize-use-nullptr check is enabled; modernize-use-override is still complaining about some destructors, which is outside the scope of this PR.~~
To use clang-tidy:
- If using a Visual Studio **solution**, click `Analyze` > `Run Code Analsys` > `On Solution` - this will run clang-tidy now instead of the Microsoft code analysis.
- In other generators, including Visual Studio CMake, build the `tidy` target. Any checks with fixers can be applied by building the `fix` target.
I had to clean up the SIMD/CPUID stuff a bit for clang-tidy+MSVC to not blow up on the CoreLib and plPipeline targets. As a side effect, …

First class clang-tidy support.

---

Sources/Plasma/NucleusLib/pnNetCommon/plSynchedObject.h
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgrSend.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgHandler.cpp
Sources/Plasma/PubUtilLib/plNetMessage/plNetMessage.h
Sources/Plasma/PubUtilLib/plNetMessage/plNetMsgHelpers.cpp
Sources/Plasma/PubUtilLib/plNetMessage/plNetMsgHelpers.h

These amount to a lot of the warnings printed out by the x64 builders, because the warning is issued every time the header is included.

Clean up a handful of size_t warnings in common headers

---

Sources/Plasma/CoreLib/hsPoolVector.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp

The pool vector only calls the createItem code when adding a new element to the pool, but plDXPipeline will explicitly null out items in the pool prior to resetting its use count. This change adds a reset method which also clears the pool (note: per the C++17 standard, clear() will not cause a reallocation of the underlying storage, so this is not a performance regression).

Fix a crash introduced by c19ae73a

---

Sources/Plasma/PubUtilLib/plAudible/plWinAudible.cpp
Sources/Plasma/PubUtilLib/plAudible/plWinAudible.h
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgHandler.cpp
Sources/Plasma/PubUtilLib/plNetCommon/plNetCommonHelpers.h
Sources/Plasma/PubUtilLib/plNetMessage/plNetMessage.h

`plVoicePlayer::PlaybackVoiceMessage` already expects a `size_t`, so no change needed there

Address a few more size_t warnings

---

.clang-tidy
Sources/Plasma/PubUtilLib/plGLight/plPointShadowMaster.cpp
Sources/Plasma/PubUtilLib/plGLight/plPointShadowMaster.h

Slowly increasing the level of checks, enabling:
- bugprone-bool-pointer-implicit-conversion
- bugprone-inaccurate-erase,
- bugprone-unused-raii
These checks required no code changes. I did find that bugprone-parent-virtual-call reveals many issues, some of which are intentional, some of which are bugs. I elected to not include that one for now.

Enable more tidy checks.

---

Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainCritter.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvatarMgr.cpp
Sources/Plasma/PubUtilLib/plInputCore/plSceneInputInterface.cpp
Sources/Plasma/PubUtilLib/plInputCore/plSceneInputInterface.h
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgr.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgrShow.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgrVoice.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgHandler.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetLinkingMgr.cpp
Sources/Plasma/PubUtilLib/plNetTransport/plNetTransport.cpp
Sources/Plasma/PubUtilLib/plNetTransport/plNetTransport.h
Sources/Plasma/PubUtilLib/plNetTransport/plNetTransportMember.h

* Clean up the final use of `qsort` by using a `vector` instead of a raw heap allocation for `plNetTransport::GetMemberListDistSorted`
* Clean up other accessors and vector use in `plNetTransport` for the existing vectors.

plNetTransport vectors

---

Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/FeatureLib/pfConsole/pfDispatchLog.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleEngine.cpp
Sources/Plasma/NucleusLib/pnAsyncCoreExe/Private/Nt/pnAceNt.cpp
Sources/Plasma/NucleusLib/pnNetCli/Intern.h
Sources/Plasma/NucleusLib/pnNetCli/pnNcChannel.cpp
Sources/Plasma/PubUtilLib/plDrawable/plDynaDecalMgr.cpp
Sources/Plasma/PubUtilLib/plDrawable/plDynaDecalMgr.h
Sources/Plasma/PubUtilLib/plGImage/plFont.cpp
Sources/Plasma/PubUtilLib/plStatusLog/plStatusLog.cpp

~~If you stub out font rendering, it is possible to link to Personal with an x64 build with these changes.  I haven't figured out why font rendering explodes in x64 yet, unfortunately :/~~
It's now possible to link to Relto (and a few other ages I tried) without modification.  Is this sufficient to close #34?  Probably not if you include Max plugin support...

Fix some x64 compatibility issues

---

Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp

If a single unpacked Python file has a syntax error, Python will be hosed for an indeterminate time due to the loader not properly processing errors. This fixes that issue. Related: `DisplayPythonOutput()` does nothing - all calls to this method need to be audited (in another PR) for intent and corrections applied where needed.
This issue was discovered when VS Code "helpfully" inserted an invalid `import` statement at the top of a file I was working on.

Fix syntax errors hosing Python.

---

.github/workflows/ci.yml

I removed the `brew update` step since it takes a bunch of time and was causing issues when trying to install packages that already had an older version installed. We install most of our dependencies from vcpkg, so I don't think we need to be picky about running the absolute latest version of things like autoconf and libtool and qt5.
Also (although I swear we tested this previously) the qt path for CMake wasn't getting picked up properly. Now we pass it in as a CMake directive and it works (as evidenced in build logs).

macOS CI fixes

---

Sources/Plasma/PubUtilLib/plAvatar/plAvBrainDrive.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainDrive.h
Sources/Plasma/PubUtilLib/plInputCore/plAvatarInputInterface.cpp

When working on the [clickable URLs in KI chat](https://www.youtube.com/watch?v=wgRlXdGxluA) functionality (see #890), it became apparent that the internal client could not start chatting by pressing the H key. This is problematic because, at this time, all URLs start with H. This fixes that problem and others.
Changed bindings:
- (Internal Client) Open Logs: Ctrl+L (was L)
- (Internal Client) Camera Drive: Ctrl+D (was Shift+C)
- (Internal Client) Flymode: Ctrl+P (was Shift+P)
- (All Clients) Strafe Modifier: Alt (was Z)
Unchanged:
- Flymode Up: U
- Flymode Down: H
The unchanged keys now bind only when they are needed.

Change or fix bindings that conflict with chatting.

---

Scripts/Python/ki/xKIChat.py

Despite all other commands being case-insensitive, /P didn't work.
This fixes the cause.

Fix /p to not be case sensitive

---

.github/workflows/ci.yml
vcpkg.json

Updates:
- asio 1.18.1
- brotli 1.0.9#1
- libffi 3.3#7
- libjpeg-turbo 2.0.6
- libwebm 1.0.0.27#6
- openal-soft 1.21.1
- physx 4.1.1#7 - Debug symbols are now embedded in the static library
- python3 3.9.2#1 - Gained Windows 7 backwards compatibility
- speex 1.2.0#8 - Gained Linux and macOS support
- sqlite3 3.35.2

Update vcpkg submodule and manifest.

---

Sources/Plasma/Apps/plClient/external/render_svg.py
Sources/Plasma/Apps/plClient/external/scalergba.py

See #800: Because CairoSVG does not support `feGaussianBlur`, do the blurring and compositing externally in _render_svg.py_.
It turns out CairoSVG also doesn’t fully support masks (it only applies the alpha of the mask, rather than the product of luminance and alpha as [specified](https://www.w3.org/TR/SVG11/masking.html#Masking)), but that doesn’t matter because the masking needs to be applied after the blurring, so we need to do it externally too anyway.
The result is not a pixel-perfect match for the old rsvg-rendered cursors, but the differences are hardly noticeable. (Mainly, in “poised” cursors, the shadow is a bit lighter in the center and a bit darker between the two rings.)
before:
rsvg:
new:
Probably requires #801 – I only tested it with a locally self-installed CairoSVG 2.5.1 …

Fix cursor shadow rendering with CairoSVG

---

.github/workflows/ci.yml
Scripts/Ports/python3-cairosvg/portfile.cmake
Scripts/Ports/python3-cairosvg/vcpkg.json
Scripts/Triplets/x64-windows-plasma.cmake
Scripts/Triplets/x86-windows-plasma.cmake
Sources/Plasma/Apps/plClient/external/requirements.txt
cmake/VcpkgToolchain.cmake
vcpkg.json

This bumps the resource.dat generation scripts to cairosvg 2.5.1 to fix the garbled microphone icon as mentioned in #796 and #800. Unfortunately, modern cairosvg rely on cairocffi but do not include libcairo-2.dll on Windows. To work around that, I have written a vcpkg overlay port that builds cairo and copies it into the vcpkg python3 tools directory on Windows. Other platforms should simply install cairo from their package manager.
Currently, this will fail CI due to the vcpkg cairo port depending on fontconfig, which has dependencies that fail to build under a static triplet. I could list them all as dynamic in our triplet, but these dependencies collectively take over 30 minutes to build. So, we are blocking on upstream:
Note that because the triplet files have changed, the hash of …

Bump to cairosvg 2.5.1

---

Sources/Plasma/Apps/plClient/external/render_svg.py

Explicitly sets the output resolution for non-cursor resources during rasterization.

Fix non-cursor resource output scaling.

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/external/render_svg.py

Fixes:
- resource.dat being junked if the number of frames in the spinning book changes or if the number of zeroes changes. Happens when switching to and from the Gehn Shard branch
- removes the listing for all resource files from plClient's target if `PLASMA_BUILD_RESOURCE_DAT` is `OFF`.

Fix some resource.dat bugs.

---

Sources/Plasma/PubUtilLib/plAvatar/plPhysicalControllerCore.cpp

The previous logic could result in a 90-degree contact being returned as the ground. At best, this caused the player to be "flung" backwards after jumping into a wall. At worst, this caused the player to start falling in place against sheer walls.

Fix improper ground filter logic.

---

Sources/Plasma/PubUtilLib/plDrawable/plDrawableSpans.cpp

Fixes a regression from 44f3f64e2478384e91d1230633c033daa963c284, which caused cluster spans to be missing (e.g. Minkata craters)

Fix missing cluster spans regression

---

Sources/Plasma/NucleusLib/inc/plCreatableIndex.h
Sources/Plasma/NucleusLib/pnMessage/CMakeLists.txt
Sources/Plasma/NucleusLib/pnMessage/plSDLModifierMsg.h
Sources/Plasma/PubUtilLib/plMessage/CMakeLists.txt
Sources/Plasma/PubUtilLib/plMessage/plMessageCreatable.h
Sources/Plasma/PubUtilLib/plMessage/plSDLModifierStateMsg.cpp
Sources/Plasma/PubUtilLib/plMessage/plSDLModifierStateMsg.h
Sources/Plasma/PubUtilLib/plModifier/plSDLModifier.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgr.cpp

plSDLModifierStateMsg is a subclass of plSDLModifierMsg that contains the state variable handling. It lives in plMessage, which can safely link against plSDL, and is used only by PubUtilLib classes.

Break the pnMessage->plSDL dependency with new msg

---

cmake/FindVPX.cmake

The last vcpkg update removed the "d" suffix from the libvpx debug library, so we now alias to the vcpkg libvpx target, if available, to ensure proper library linkage.
Updates:
asio 1.18.1 -> 1.18.1#1
cairo 1.16.0#11 -> 1.17.4#1
curl 7.74.0#4 -> 7.74.0#6
OpenSSL 1.1.1j#2 -> 1.1.1k#2
PhysX 4.1.1#7 -> 4.1.2
Python 3.9.2#1 -> 3.9.5
sqlite 3.35.4 -> 3.35.4#1

Update vcpkg submodule and fix libvpx debug.

---

Scripts/Python/xAgeSDLBoolActivatorComboSet.py
Scripts/Python/xAgeSDLBoolRespond.py

There was a [request on the forum](https://forum.guildofwriters.org/viewtopic.php?f=9&t=7177) for Python scripts for making puzzles that use a set of buttons in a combination to open doors. This script is generalized to take a combination, set of buttons, and some SDL variables. When the combination is input correctly, the solved SDL variable is set, which can trigger any arbitrary reaction with xAgeSDLBoolRespond.py

Button Puzzle Scripts

---

Sources/Plasma/PubUtilLib/plAvatar/plAvTaskSeek.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvTaskSeek.h
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.cpp

This fixes the issue by which attempting to use any of the Teledahn power tower machinery would result in the avatar getting stuck while seeking. Also nukes the old PhysX 2.6-era skin width off the character capsule and tries to use tighter bounds for convex hulls.

Cope with more goofy colliders.

---

Scripts/Python/xAvatarCustomization.py

This interesting logic did not do what it said. Instead, it would work sometimes. When attempting to add the new "Gay Zero" shirt courtesy of Paradox, it unconditionally broke, leaving the Gay Zero shirt off the list unless another shirt was either added or removed.

Fix error prone "rounding" used by ACA list box GUI.

---

Scripts/Python/plasma/Plasma.py
Sources/Plasma/CoreLib/hsFastMath.h
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfPython/cyPhysics.cpp
Sources/Plasma/FeatureLib/pfPython/pyWaveSet.cpp
Sources/Plasma/FeatureLib/pfPython/pyWaveSet.h
Sources/Plasma/FeatureLib/pfPython/pyWaveSetGlue.cpp
Sources/Plasma/PubUtilLib/plDrawable/plWaveSet7.cpp
Sources/Plasma/PubUtilLib/plDrawable/plWaveSet7.h
Sources/Plasma/PubUtilLib/plMessage/CMakeLists.txt
Sources/Plasma/PubUtilLib/plMessage/plDampMsg.h
Sources/Plasma/PubUtilLib/plMessage/plImpulseMsg.h
Sources/Plasma/PubUtilLib/plMessage/plMessageCreatable.h
Sources/Plasma/PubUtilLib/plPhysX/plGenericPhysical.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.h

These were mostly already implemented, but the physics messages had gone missing, and someone added a wildly incorrect multiplication factor.
* Fixes some 32-bit assumptions in hsFastMath, but I can drop this commit if it seems misplaced
* Adds back plImpulseMsg and plDampMsg and hooks them up in the physics simulation
* I suspect the damping handling could be improved, but it gives a reasonably decent effect right now
* Adds console commands for testing
* Adds Python API for fun runtime shenanigans
* Adds a new flag to the existing plWaveSet7 bitvector, which causes it to read an extra array of buoys to attach automatically
* I have code ready to go for libHSPlasma and korman
* This should be compatible with all existing data, but not compatible with old clients (although maybe they just …

WaveSet Buoys

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIConstants.py
Scripts/Python/plasma/Plasma.py
Scripts/Python/plasma/PlasmaConstants.py
Scripts/Python/xDialogStartUp.py
Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/FeatureLib/pfCharacter/CMakeLists.txt
Sources/Plasma/FeatureLib/pfCharacter/pfConfirmationMgr.cpp
Sources/Plasma/FeatureLib/pfCharacter/pfConfirmationMgr.h
Sources/Plasma/FeatureLib/pfConsole/pfGameConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIDialogMod.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIDialogMod.h
Sources/Plasma/FeatureLib/pfPython/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue2.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonCallable.h
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/FeatureLib/pfPython/pyGlueHelpers.h
Sources/Plasma/FeatureLib/pfPython/pyObjectRef.h
Sources/Plasma/NucleusLib/inc/plCreatableIndex.h
Sources/Plasma/NucleusLib/pnKeyedObject/plFixedKey.cpp
Sources/Plasma/NucleusLib/pnKeyedObject/plFixedKey.h
Sources/Plasma/PubUtilLib/plMessage/CMakeLists.txt
Sources/Plasma/PubUtilLib/plMessage/plConfirmationMsg.h
Sources/Plasma/PubUtilLib/plMessage/plMessageCreatable.h

While working on the [clickable links in KI Chat](https://www.youtube.com/watch?v=qvsb0mhxUig) concept, it became apparent that I needed to issue a confirmation or Yes/No dialog from a Python script that did not have its own `plKey`. Currently, Yes/No dialogs are handled by the xKI python scripts over many hundreds of lines in an especially ad-hoc way and can only be responded to using a `plNotifyMsg`. This implements a singleton whose job is to receive confirmation requests from anyone who links against plMessage and respond to them via either a (potentially stateful) lambda or using a legacy `plNotifyMsg`.
This new functionality will allow us to be very flexible with where we issue and how we respond to confirmation requests. Some examples floating around in my mind:
- `PtYesNoDialog()` …

Confirmation (Yes/No/OK/Quit/Logout) Overhaul

---

Sources/Tools/MaxComponent/plResponderComponent.cpp

I have no idea what we were smoking before, but `BackpatchPending()` is in Max 2008.

Fix Max 2008 compile error revealed by CI.

---

Sources/Plasma/PubUtilLib/plResMgr/plRegistryKeyList.cpp

This occurs when using a GlobalClothing_District_Female.prp exported by our Max plugin builds. All other uses of fKeys condiser null keyimps, and the reader is not required to fill every slot.

Fix potential null defreference.

---

Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp

Most of the code properly handles `fClothingOutfit` being null, but the LayerLinkAnimation check does not.
Currently all the avatars have clothing outfits (PlasmaMax always exports them) but it doesn't necessarily make sense for things like Quabs.

Safety checking for avatars without clothing outfits

---

Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp

Generally skinned objects will not change their UVs - except in the case of avatar clothing. When the morph slider is adjusted in the ACA, new UVs may or may not be committed to the `plGBufferGroup`. If we simply skip over them in the skinning loop, then the newly morphed UVs will not be sent to DirectX.

Fix clothing UVs not being updated by morphs.

---

Sources/Plasma/PubUtilLib/plDrawable/plMorphDelta.cpp

Actual work with clothing UVs demonstrates that the old threshold is too great. Only large changes such as mirroring the entire UV map will pass and therefore be available in the data. This seems to be enough to enable the kind of tweaking real UV work involves.
Video of previous behavior available on request.

Decrease morph UV delta threshold.

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIConstants.py
Scripts/Python/plasma/Plasma.py
Scripts/Python/plasma/PlasmaTypes.py
Scripts/Python/xGUILinkHandler.py
Scripts/Python/xOptionsMenu.py
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIControlMod.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIDialogMod.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIDialogNotifyProc.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.h
Sources/Plasma/FeatureLib/pfMessage/pfGUINotifyMsg.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEditGlue.cpp

This implements clickable URLs in KI chat and KI mail. This is done by adding a new control code to the `pfGUIMultiLineEditCtrl` that indicates a "link". The actual detection and handling of these links is done in Python where the rest of the text handling is done. Note that due to technical limitations, there are some behavior changes in the KI. Specifically, KI mail is no longer censored in the vault. Rather, it is censored at display time to prevent the corruption of URLs containing censored words. Further, KI mail can only be edited by the sender, preventing a trivial opportunity to escape the naughty word censor... When edit mode is activated, all censored words become unmasked.
[Demonstration video here](https://www.youtube.com/watch?v=ewpgJrTKv1w)
Depends on:
So merge those first.

Clickable URLs in KI Chat and KI Mail.

---

Scripts/Python/ki/xKIChat.py

```
(07/06 17:50:50) KIHandler - Traceback (most recent call last):
(07/06 17:50:50)   File "ki.__init__.py", line 623, in OnGUINotify
(07/06 17:50:50)   File "ki.__init__.py", line 5559, in ProcessNotifyMini
(07/06 17:50:50)   File "ki.xKIChat.py", line 200, in SendMessage
(07/06 17:50:50)   File "ki.xKIChat.py", line 821, in __call__
(07/06 17:50:50)   File "ki.xKIChat.py", line 949, in ClearChat
(07/06 17:50:50) AttributeError: 'CommandsProcessor' object has no attribute 'miniChatArea'
```

Fix /clearchat command regression.

---

Sources/Plasma/NucleusLib/pnKeyedObject/plUoid.cpp
Sources/Plasma/PubUtilLib/plResMgr/plRegistryKeyList.cpp

While this may make some amount of sense if you are working on the game in solely 3ds Max, what ends up happening is that it hides all the ObjID mismatches you have created. They will only be seen when using the external client. Generally, this results in whacky texture goof ups where the wrong textures are applied to the wrong objects. However, in more serious cases, such as pages that have been processed by plPageOptimizer, a round-trip through a bugged process can cause very wrong objects to be returned, crashing the game.

Remove bug-prone local data helper.

---

Sources/Plasma/PubUtilLib/plAvatar/plPhysicalControllerCore.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXSimulation.cpp

Some corrections to physical behaviors resulting from the PhysX 4.1 upgrade. See each commit description for details. This unfortunately does not include #784, which needs more investigation.

PhysX Behavior Rollup

---

Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizedString.cpp

This adds some very basic heuristics for detecting journals contained in the localization files and exports their data enclosed in XML's `<![CDATA[thingy]]>` to prevent having to review localization changes with XML-encoded Plasma esHTML.
Bonus: a spurious copy was eliminated.

Use XML CDATA for journals in LOC files.

---

Scripts/Ports/python3-cairosvg/portfile.cmake
Scripts/Ports/python3-cairosvg/vcpkg.json

Fixes CMake regression [#22444](https://gitlab.kitware.com/cmake/cmake/-/issues/22444) via microsoft/vcpkg-tool#107.
Other updates:
- asio 1.18.2
- cairo 1.17.4#2
- expat 2.4.1
- libcurl 7.74.0#8
- libogg 1.3.5
- libpng 1.6.37#15
- libvpx 1.10.0
- openssl 1.1.1k#7
- python3 3.9.6
- sqlite 3.35.5

Update vcpkg submodule.

---

Sources/Plasma/PubUtilLib/plDrawable/plWaveSet7.cpp
Sources/Plasma/PubUtilLib/plDrawable/plWaveSet7.h

Copying too many elements from a stack array. This whole thing is unused, so just toss it.

Fix plWaveSet7 UB.

---

Sources/Plasma/PubUtilLib/plNetClient/plNetCliAgeJoiner.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plVault/Pch.h
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.h

On MOULa, there have been complaints about linking to some Neighborhoods and activating some players taking a very long time. One of these Neighborhoods in particular is the "DRC(67) Bevin". When I attempted to link to this Age, I found the link took approximately 85 seconds each time. On profiling, I discovered that for every node downloaded during the initialization phase, we were calling into Python at least once. Suppressing vault callbacks during times when they are obviously going to storm and be useless decreases the link time to 7 seconds.
Initially, I suppressed just the Python side of the callbacks when an Age is being initialized, but it seems to me that a more reasonable solution is to not run callbacks during vault loads and unloads. Clearly, things are happening at this …

Suppress vault callbacks when loading or unloading VNodeMgrs.

---

Scripts/Python/ercaHrvstr.py

This corrects the Er'cana Harvester to only put the ramps down when the car and harvester are stationary in the same location. Previously, it was possible to cleverly desynchronize this and wind up with the ramps down while the machine was moving, potentially without the car attached.
See companion m-a PR for more details.
Since this PR does not attempt to rewrite the script to not be a pile of garbage, these are my notes about the harvester states:
```
car pos
0: not ready/eligible to go up into the mill
1: at bottom
2: going up
3: at top
4: going down
harvester pos
0: far shell cloth
2: moving
4: at mill
```

Correct harvester/car ramp logic.

---

Sources/Plasma/PubUtilLib/plFile/plBrowseFolder.cpp
Sources/Plasma/PubUtilLib/plFile/plBrowseFolder.h
Sources/Tools/MaxMain/GlobalUtility.cpp
Sources/Tools/MaxMain/plMaxCFGFile.cpp

Previously, if you launched Max without a PlasmaMAX2.ini file, you were SOL. The functionality to specify a client directory was already present, so this simply enables it. As a bonus, we now use the folder picker dialog from Vista (and above) instead of the old Windows 9x dialog, and windows.h becomes much less viral.

Allow the max plugin to auto-generate PlasmaMAX2.ini

---

Scripts/Triplets/x64-windows-plasma.cmake
Scripts/Triplets/x86-windows-plasma.cmake
cmake/VcpkgToolchain.cmake

Routine vcpkg upgrade with some not-so-routine fixes. This pulls down a patch I submitted to fix the python3 build on GHA windows-2019 runners due to what appears to be a bug in the Windows SDK. Also, we now use the newfangled `VCPKG_DISABLE_COMPILER_TRACKING` to avoid including the hash of cl.exe in the binarycache. So, hopefully, folks will actually download the libraries from GitHub Packages now, instead of rebuilding them from scratch because they have a slightly newer or older VS.
Before merging:
Updated Libraries:
- asio 1.19.2
- curl 7.79.1
- libjpeg-tubo 2.0.6#1
- libvpx 1.10.0#2
- openssl 1.1.1l#1
- Python 3.9.7#1
- sqlite3 3.36.0
- zlib 1.2.11#12

vcpkg upgrade

---

Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClient.h
Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/plClientLauncher.cpp
Sources/Plasma/Apps/plUruLauncher/plClientLauncher.h

This adds the command line switch `-SkipIntroMovies` to allow skipping any and all intro movies when the game starts. This fixes #910 - but doesn't address the letter of the concern because `-Age` only works on internal clients (this switch works on all build types). This switch can be passed directly to plClient or to plUruLauncher.

Add `-SkipIntroMovies`.

---

Sources/Plasma/NucleusLib/pnNetCommon/pnNetCommon.cpp
Sources/Tools/MaxExport/plExportDlg.cpp

* `inet_ntoa` and `inet_addr` are both considered deprecated due to flaws in their API.  This replaces them with the more flexible `inet_ntop` and `inet_pton`, respectively.
* Eliminate some unnecessary `memcpy`/`memset` in `in_addr` manipulation.
* Fix use of non-standard MSVC-backwards-compatible variant of `wcstok` by converting it to the standards-compliant version.

Fix some uses of deprecated libc functions

---

Sources/Plasma/FeatureLib/pfPython/pyVaultNode.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultNode.h

This avoids an incomplete type error on GCC 11, since RelVaultNode is only forward-declared in pyVaultNode.h.

Move implementation of pyVaultNodeOperationCallback constructors to .cpp file

---

Sources/Plasma/NucleusLib/pnAsyncCore/CMakeLists.txt

pnAsyncCoreExe compiles successfully on Linux (albeit without the Windows-specific Socket implementation) and needs to be linked as a dependency of pnAsyncCore on all platforms.

Fix pnAsyncCoreExe linking on non-Windows

---

Sources/Plasma/CoreLib/hsThread.h
Sources/Plasma/CoreLib/hsThread_Unix.cpp
Sources/Plasma/CoreLib/hsThread_Win.cpp
Sources/Plasma/FeatureLib/pfCrashHandler/plCrashBase.cpp
Sources/Plasma/FeatureLib/pfCrashHandler/plCrashBase.h
Sources/Plasma/FeatureLib/pfCrashHandler/plCrashCli.cpp
Sources/Plasma/FeatureLib/pfCrashHandler/plCrashSrv.cpp
Sources/Plasma/FeatureLib/pfCrashHandler/plCrashSrv.h
Sources/Plasma/FeatureLib/pfCrashHandler/plCrash_Private.h

This is for the upcoming redesigned crash dialog.

ST-ize pfCrashHandler.

---

Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceThread.cpp
cmake/CompilerChecks.cmake
cmake/check_pthread_timedjoin_np.cpp
cmake/hsConfig.h.cmake

This will now use `pthread_timedjoin_np()` on any platform which provides it with a compatible API, rather than restricting its use to Linux.

Improve detection of pthread_timedjoin_np

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
cmake/PlasmaTargets.cmake

This is for the upcoming redesigned crash dialog. It doesn't really make sense outside that context, I know.
The new crash dialog needs plClient.pdb to show stack traces, however, this file generally weighs in at 100 MiB, which is a bit excessive to distribute just for showing some crash information. This generates another pdb file with the extension `.stripped.pdb` that has all of the file+line information removed, causing a massive reduction to around ~16 MiB. This compresses down to ~3 MiB. This would be a great file to distribute as plClient.pdb to end users so you get function names in the crash dialog. The crash.dmp file can still be used to gather the exact file and line numbers from the full-fat pdb.
Outside the context of the new crash dialog, the stripped pdb is still useful for …

Add support for stripped PDBs.

---

Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIHelpers.py
Scripts/Python/xDialogStartUp.py

- Change \s and \d escape characters in some python regex pattern strings to use \\s and \\d so they no longer throw deprecation warnings
- Update missing player name check on Create Player dialog so it doesn't repeat (playerName == "") twice

Fix Python deprecation warnings because of \s and \d escape characters in regex patterns

---

Scripts/Python/ki/xKIChat.py
Scripts/Python/xCheat.py
Scripts/Python/xInvite.py

- Update KI chat command processor to discard blank/whitespace messages, including messages used with /me and /buddies, among other commands
- Remove usage of nonexistent constant so /invite command doesn't silently crash and instead actually creates an invite with passkey

Prevent sending blank/space KI messages in variety of contexts; Fix /invite so it doesn't silently crash

---

cmake/FindVPX.cmake

In CMake 3.17 and lower, you cannot create an ALIAS to a non-global target. So, if you tried to use vcpkg with CMake 3.17 or lower (eg on Ubuntu 20.04), the configure step would fail with a curious error message.

Fix FindVPX for CMake < 3.18.

---

Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizationDataMgr.cpp
Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizationDataMgr.h
Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizationMgr.cpp
Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizationMgr.h
Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizedString.cpp
Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizedString.h

pfLocalization is the gift that keeps on giving in terms of pointless copying. The gains for these changes are very minor until you start to increase the localization database to ridiculous levels (eg the GULP hell data set).
MOULa:
```
Before (1,000 iterations):
Total: 90.4061 seconds (90406071 us)
Average: 0.0904 seconds (90406 us)
After (1,000 iterations):
Total: 86.0913 seconds (86091275 us)
Average: 0.0861 seconds (86091 us)
```
Hell:
```
HELL SET BEFORE (1,000 iterations):
Total: 206.5140 seconds (206514028 us)
Average: 0.2065 seconds (206514 us)
HELL SET AFTER (1,000 iterations):
Total: 199.5938 seconds (199593832 us)
Average: 0.1996 seconds (199593 us)
```
There are still more gains that could be achieved in pfLocalization, but these are mostly around actually fetching the …

More pfLocalization `std::map` copying fixes.

---

Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.h
Sources/Tools/MaxComponent/plAvatarComponent.cpp

The age and page names for footstep sounds are stored in the plArmatureMod data, but the effects were getting initialized before those values were read, so they were always using the defaults of "GlobalAvatars" and "Audio". This results in the custom footstep sounds for Quabs not taking effect in-game.
However, this will break footstep sounds for other custom avatars who *do* want to use the global sounds, because the age name is exported as "CustomAvatars" instead of "GlobalAvatars" in their plLODAvatarMod data.  
The custom avatar data can easily be fixed in the compiled data files in the moul-assets repo.
This change include an update to PlasmaMax so that if the avatar footstep page is set to "Audio" it will export with a hardcoded "GlobalAvatars" age, otherwise it will use the current …

Fix custom avatar footsteps

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIConstants.py

- Chat mentions will now only highlight the player's name in the message instead of the entire message. Intended to avoid confusion for players who mistake mentions for private/whisper messages
- When player's name is contained within a URL, the URL handling will take precedence and the name will not be highlighted
- Add DniBlueDk (medium dusky blue) color that matches KI lights for potential use later

Change chat mentions to only highlight player's name instead of entire message

---

Scripts/Python/Personal.py
Scripts/Python/clftImager.py
Scripts/Python/ki/xMarkerBrainUser.py
Scripts/Python/plasma/Plasma.py
Scripts/Python/xAvatarCustomization.py
Scripts/Python/xTakableClothing.py
Scripts/SDL/Myst.sdl
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue3.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue4.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvatarClothing.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvatarClothing.h

PRP files - https://github.com/H-uru/moul-assets/pull/85
Found a bug in how clothing is rewarded, before it would check and if you already had it, it would just reward it again anyways. The HasClothing function is the solution that was suggested to me by Adam to fix it.
Clothing Sets code was removed between CC and Moula, found the old cyan code and added it back in.
Its found in xAvatarCustomization.py
Personal.py has some new reward code for clothing sets added by Calum Traveler
Checks if you have the Bahro wedges and if you complete one, it adds it to your closet on first visit to Relto.

Files updated for Additional Clothing PR

---

Scripts/SDL/GoMePubNew.sdl

Once again condenses a bunch of SDL states into one, this time for the menorah candle flames.
Instead of each flame being a separate bool SDL, everything is now controlled by an integer "gmpnMenFlameStat". The menorah itself is still controlled by the gmpnHolidayVis state.
0 - Default (no flames)
1 - Shammash and Flame01 on Day 1
2 - Flame02 on Day 2
3 - Flame03 on Day 3
4 - Flame04 on Day 4
5 - Flame05 on Day 5
6 - Flame06 on Day 6
7 - Flame07 on Day 7
8 - Flame08 on Day 8
New PRPs to go along with this will be PRed later after I do a few more adjustments to collision to keep the cones and Eddie out of weird spots.

Add new menorah flame SDL state

---

cmake/FindPhysX.cmake

If PhysX is built and installed into somewhere like `/usr/lib32` or `/usr/lib64` on Linux, then it's probably not suffixed with the architecture.

Check unsuffixed PhysX lib names for Linux

---

Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClientLoader.cpp
cmake/PlasmaTargets.cmake

This allows plClient.cpp and plClientLoader.cpp to compile (but not link or do anything useful) on Linux.

Guard all Win32 code in plClient

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIExtChatCommands.py

This allows users to change chat context for future messages without clicking on the KI folders. For example, if you are PMing/whispering to someone, then want to stop whispering and start sending future messages to all Age Players, you can switch context by using "/age\<Enter\>" and it behaves like you have clicked the AGE PLAYERS folder from your KI list.
Should be merged alongside [this moul-assets PR](https://github.com/H-uru/moul-assets/pull/95).

Allow mouse-free and message-free KI commands to select KI folders: /age, /neighbors, and /buddies

---

Sources/Plasma/FeatureLib/pfMoviePlayer/plMoviePlayer.cpp
cmake/Findlibwebm.cmake

This should work with both the existing 1.0.0.27 version as well as the newer 1.0.0.28 version, whether the headers are installed under `libwebm/` or in the global include directory.

Fix lookups for newer libwebm versions

---

Scripts/Python/nxusBookMachine.py

Temporarily removes Tiam listings from the Nexus until a Linking Panel can be added.

Remove TIam from Nexus

---

Scripts/Python/xDialogStartUp.py

Fixes #1031 by re-adding OnGUINotify handling for the error message display box's OK button. I took the missing elif code block from the current OU version of this python file and removed the antiquated gIsExplorer handling.

Restore handling for GUIDialog4d OK button

---

Scripts/Python/ki/xKIChat.py

Calum reported on the OpenUru discord that just sending a chat line with "/" or "/   " would create a prefix-less and message-less line in the KI chat. This PR prevents this bizarre chat line from being added and short-circuits trying to find any emote or other command matches because having an empty command seems clearly invalid and should never match anything.

Prevent empty command '/' or '/  ' from creating a blank message line

---

Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIConstants.py

- Improve formatting and readability for dictionaries of constants in xKIConstants.py
- Add documentation comments for kEasterEggs dictionary in xKIConstants.py so Age creators can more easily know how to add new values without trial and error or trying to understand the python that uses it in xKIChat.py.
- Improve behavior of /look command so it does not try to get nearby player list when kEasterEggs already defined a value to display for "people".
- Improve formatting of nearby player names by conditionally using "is" or "are" depending on how many players are nearby and ending the concatenated list with ", and {lastPlayerName}" instead of ", {lastPlayerName}"

Small improvements for /look command and xKIConstants formatting updates

---

Scripts/Python/ki/xKIChat.py

Previously the name-to-ID conversion would only work for Age Players due to player nodes in Buddies and Neighbors folders not being of type ptPlayer. Primarily for easier /addbuddy usage with neighbor names. Requested by Hazado on OpenUru discord.

Allow getting PID from name for online buddies or neighbors

---

Sources/Plasma/PubUtilLib/plAudio/plDSoundBuffer.cpp
Sources/Plasma/PubUtilLib/plAudio/plWin32StreamingSound.cpp

Arithmetic overflow and usage of an incorrect method were causing the `GetActualTimeSec()` method to return absurdly large values sometimes, usually for medium to long streaming audio.

Make `plWin32StreamingSound::GetActualTimeSec()` return correct values

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/main.cpp
Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClient.h
Sources/Plasma/Apps/plClient/plClientLoader.cpp
Sources/Plasma/Apps/plClient/plClient_Win.cpp
Sources/Plasma/NucleusLib/pnTimer/plTimedValue.h

This lays the groundwork for having cross-platform X11 and Cocoa implementations of plClient.
winmain.cpp is still a problem, so we're going to ignore that for the moment and just provide a main.cpp with an empty stub so the compiler is happy.
Note: I have not enabled building plClient on non-Windows here because it fails to link due to pnAsyncCoreExe. It should work (for _very_ loose definitions of "work" with the changes from #1032 and #1042)

Pull Win32-specific client code into its own cpp file

---

.github/workflows/ci.yml

Use windows 2019 for CI runs

---

Sources/Tools/MaxComponent/plAutoUIBase.cpp

Only the first parameter was visible in Max 2022 because `MoveWindow()` was no longer resizing the rollup for some reason. Copying and pasting the method from `WM_SIZE_PANEL` fixed it, so here you go.
Before:
After:

Fix 3dsMax python parameters.

---

Sources/Plasma/CoreLib/hsSystemInfo.cpp

glibc 2.32 and later no longer have `<sys/sysctl.h>` on Linux. With glibc 2.30/2.31, the header still exists, but gives a deprecation warning when included.
The hsSystemInfo code already uses `<sys/sysinfo.h>` instead if possible, but it also included `<sys/sysctl.h>` if it exists (despite not using it), giving a spurious deprecation warning with those glibc versions.

Fix Linux deprecation warnings about `<sys/sysctl.h>`

---

Scripts/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp

On non-Windows, some modules with C implementations are compiled as shared libraries under a lib-dynload path. These cannot be found by default, resulting in errors when scripts do things like `import math`.

Add python/system/lib-dynload to module paths

---

Scripts/Python/ki/xKIChat.py

Yeah, I caused a bug with #1040 where I referenced a Python var before it was assigned a value in some cases and caused the KI to crash. Sorry. So I made sure to initialize it to None now. Found by HenryMikel on OU discord.

Fix var reference before assignment exception in cases like empty /r and /p

---

Sources/Plasma/NucleusLib/pnNetBase/pnNbError.h

ENetError was a 64 bit type when building with Clang on 64 bit systems. The kNetErrorForceDword value did not seem to be having any effect. My guess is MSVC might have been automatically compressing this type, and kNetErrorForceDword forced the type to be aligned with 32 bits?
This pull request is meant to be a starting point. I know this change fixed things on Clang/macOS. And kNetErrorForceDword doesn't seem needed anymore. I used int32_t instead of uint32_t. Happy to talk over any style or changes relevant to MSVC that I missed.

Fix for ENetError size on Clang/64 bit

---

cmake/Sanitizers.cmake

Putting these in CMake by hand was pretty annoying before. That's now fixed.

Automatically find clang-tidy when using VS.

---

.github/workflows/ci.yml

Ref https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

Cancel running CI jobs when a PR is updated

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUITextBoxMod.cpp

We already know the length of these strings, so we'd prefer to avoid using the bare pointers, forcing us to recalculate their length.

Improve `std::wstring` copying in `pfGUITextBoxMod`.

---

Sources/Tools/MaxComponent/plAnimCompProc.cpp
Sources/Tools/MaxComponent/plAnimComponent.cpp
Sources/Tools/MaxComponent/plGUIComponents.cpp
Sources/Tools/MaxComponent/plNotetrackDlg.cpp
Sources/Tools/MaxComponent/plNotetrackDlg.h
Sources/Tools/MaxComponent/plResponderAnim.cpp
Sources/Tools/MaxComponent/plResponderMtl.cpp
Sources/Tools/MaxPlasmaMtls/Materials/plAnimStealthNode.cpp

Fixes Max plugin crashes reported by @Hazado:
- Hardens the pick node dialog setters against null strings, which are passed in by design.
- Fixed a crash when destroying the GUI Konstant Tag rollout in the GUI Dialog component. Likely related to 64-bit.
- Fixed more UTF-8 being reinterpreted as UCS-2 in note track related UI items.

Fix moar Max plugin crashes.

---

Sources/Plasma/CoreLib/hsWindows.h
Sources/Plasma/PubUtilLib/plClipboard/plClipboard.cpp

Found when experimenting with #1024.
Windows does not like it when you delete the HGLOBAL that you hand off to the clipboard. Subsequent calls to `GlobalLock()` will return nullptr and give the error "Invalid handle." - as in - you deleted my handle! As a bonus, cleanup some of the more C-ish aspects of this fxn.

Fix crash when `plClipboard::SetClipboardText()` is called twice.

---

Scripts/Python/xGUILinkHandler.py

The Kirel 2022 Q1 audio has subtitles of URLs that begin with only www. as the prefix. This will enable that common URL anti-pattern to also be highlighted and opened directly from the KI.
See H-uru/moul-assets#113.

Allow clickable URLs to begin with "www."

---

Sources/Plasma/CoreLib/hsSystemInfo.cpp

If `HAVE_CPUID` was not defined or falsey, then we would not define a value for `cpuid_t` but we would also not guard any of the code that used `cpuid_t`, leading to compilation errors from the undefined type.

Fix errors when HAVE_CPUID is false

---

Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp

wchar_t length can vary by compiler. On Clang/64 bit/macOS it's 4 bytes, not 2. This was causing parsing to fail.
With this change linking books are now rendering properly on Mac/Metal and are linkable. Other books that weren't rendering correctly (like the welcome book in Great Zero) are now rendering in the correct font. I haven't done a full comparison with the Windows version yet so I don't want to label those books as correctly rendering yet.
Also possible more wchar_t issues could be lurking. There is still some funny behavior in places like key mapping that may or may not be related. I haven't really investigated yet, but if the assumption was made wchar_t is always two bytes, that could show up elsewhere.

Fix pfJournalBook parsing where wchar_t != 2 bytes

---

Scripts/Python/ki/__init__.py

When playing in non-English language, hovering over menu/folder items in the Big KI (showing long text rather than short text) could throw errors like this one when the text contained non-ASCII characters:
```
KIHandler - Traceback (most recent call last):
File "ki.__init__.py", line 626, in OnGUINotify
File "ki.__init__.py", line 5912, in ProcessNotifyBigKI
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 2: invalid continuation byte
```
To reproduce, start the client in French, open the Big KI and hover over the **Boîte de réception** (Incoming/Inbox) menu item. A non-fatal (to the KI usability) Python error occurs. It no longer occurs when this fix is in place. 🎉

Prevent unicode decode errors when hovering BigKI menu items

---

Scripts/Python/ki/__init__.py

The Big KI's fontsize control is a weird continuous slider with only 5 distinct values. When sliding the slider, the SetFontSize method is constantly firing and presumably doing all the work and refreshing and whatnot that it does, even when the font size is exactly the same as before. At least for me, this can make the slider usage quite chunky and jerky, especially when there is a lot of text in the KI chat areas (e.g., subtitles from speeches). So... let's make it only do all the work when the new fontsize from the slider is actually different from the old value, yeah? It seems much smoother to me now, but I don't have timings or evidence to back up my claim or anything. 🤷

Short-circuit setting KI font size when new size is same as current size

---

Sources/Plasma/PubUtilLib/plAudio/plWin32Sound.cpp
Sources/Plasma/PubUtilLib/plAudioCore/plSrtFileReader.cpp
Sources/Plasma/PubUtilLib/plAudioCore/plSrtFileReader.h

In the Yeesha Cleft speech, it appears that when you press the imager button to stop the hologram in the middle of her speech, the audio skips close to the ending position and stays there for several `Update` cycles before actually ending, which was causing the updater to feed all the remaining subtitles up to that point. This doesn't seem to be the case when Kirel podium audio is stopped, so I don't exactly know why the Yeesha audio does this. Added a check to make sure the current position/time isn't past the end of the last subtitle before requesting to display entries up to that time.
This will collide with #1096 , so please let me rebase and merge/fix before merging this one.

Don't feed remaining subtitles when audio skips to past the end of last subtitle

---

Sources/Plasma/PubUtilLib/plGImage/plFont.cpp

Clipped character calculation is being done with pointer math, but assumes that wchar_t is 2 bytes.
Windows and Mac are now rendering books identically (in the books I've seen so far.)

Fixing clipped char calc under Clang

---

Scripts/Python/plasma/Plasma.py
Sources/Plasma/FeatureLib/pfCamera/plVirtualCamNeu.cpp
Sources/Plasma/FeatureLib/pfCamera/plVirtualCamNeu.h
Sources/Plasma/FeatureLib/pfPython/cyAvatar.cpp
Sources/Plasma/FeatureLib/pfPython/cyAvatar.h
Sources/Plasma/FeatureLib/pfPython/cyAvatarGlue.cpp
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.h

Exposes `Avatar.Spawn.DontPanic` to Python. If enabled, instead of using the personal book, the player simply spawns back at the start of the Age. This also fixes some (but not all) longstanding problems related to spawning where the camera would zoom from across the Age when spawning.
Fixes #1056

Allow disabling panic linking.

---

Scripts/SDL/spyroom.sdl

Brings the spyroom.sdl file in-line with current MOULa version as of Q4 2021.

Update Spyroom SDL

---

Scripts/Ports/libepoxy/portfile.cmake
Scripts/Ports/libepoxy/threading.patch
Scripts/Ports/libepoxy/vcpkg.json

- Resolve multithreading issues
- Enable building as a static library
Unfortunately, using it as a static library causes linking errors, so we're keeping the line that forces it to be a dynamic library on Windows.
Ref: https://github.com/anholt/libepoxy/pull/265

Customize the libepoxy vcpkg port

---

Sources/Plasma/PubUtilLib/plNetClient/plNetLinkingMgr.cpp

Per reports, it seems to be possible for deferred links that trigger multiple Age registrations from code can sometimes result in the player linking to the wrong Age. So, we add some validation to the deferred linking logic to ensure they go to where they expect.

Prevent deferred link race conditions.

---

Scripts/Python/xCensorFilters.py

Per Zaroth, `aujourd'hui` is being censored in the French Q1 2022 Kirel speech subtitles. "hui" is "today" in French but is vulgar slang for penis in Russian. Given the English-centric nature of the list and the possibility of false-friends, it seems best to simply remove foreign words from the censor list. Future work would be to add proper censored words for each language.
In other words, French speakers may now say "today" in KI chat without being censored. Also, VERGE!!!

Remove foreign swear words from the censor.

---

Scripts/SDL/Garrison.sdl

Version 28 renames one of the duplicate `grsnYeeshaPage02Vis` variables to `grsnYeeshaPage02VisDUP`.
WARNING: This needs to be merged after #912 is merged. Perhaps rebased in-between. 🤷

Add v28 to Garrison.sdl for renamed duplicate variable

---

Scripts/Python/ki/__init__.py

Currently isn't a way to add offline KI mail senders to ignore or buddy lists, except through using the Recents folder/list. Requested in OU discord as a way to handle KI mail spam.

Add Incoming folder KI mail senders to Recents folder

---

Scripts/Python/ki/__init__.py
Scripts/Python/plasma/Plasma.py
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEditGlue.cpp

When chat lines did not have a leading space character, you could sometimes see that shadows were being clipped due to drawing 2 pixels out of bounds. While I generally think managing the shadow unclipping would be better in the text rendering code, Plasma's text rendering is not that smart and works on the idea that text is rendered exactly where you specify it. So, we're largely obligated to handle this kind of text positioning logic in higher level code.
This issue became very apparent when testing #1063 due to the subtitles being drawn at x=0. To illustrate...
Before:
After:

Add margins to KI chat display to fix shadow clipping.

---

Scripts/Python/grsnWallEventHandler.py

Plasma functions should never be executed in the constructor. This is because you may not be executing in the client... for example, it might be a type checker or test tool. In this case, the network client is not initialized, so the call to `PtGetDniTime()` explodes.

Fix 3dsMax crash caused by Garrison Wall.

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.cpp

KI Chat lines were not re-wrapping after changing the font size. Now they will.
Bug:
Fixed:

Fix KI chat not wrapping correctly after size change.

---

Scripts/Python/ki/__init__.py
Scripts/Python/xLocTools.py

Requires https://github.com/H-uru/moul-assets/pull/121.
Clean up formatting of possessive display names for Ages in English and German. Condense and clarify lines for better python-esque code, hopefully. Remove unneeded unicode-encoding function. Make `xTranslatedAgeNames` dictionary values actually be the localized values for clarity and consistency.

Clean up possessive localized age name creation and misc xLocTools.py contents

---

Scripts/Python/ki/__init__.py

Previously editing a game title was allowed at any time. This makes it work like the OU client will now, where only the owner can edit the title and only during editing mode. I don't know if H'uru was previously allowing non-owners to edit the titles since I only had self-created games to test, but... now they can't, I guess.

Only allow marker game title editing during edit mode

---

Sources/Plasma/PubUtilLib/plSurface/plShader.cpp

This divide by zero was resolving to a INF value, which was causing the shader to generate garbage. Changing the divide by zero to non IEEE behavior which aligns with what HLSL 1.1 seems to expect. Metal inherits the IEEE behavior which causes problems.
More background - 
I've been trying to figure out why this hasn't caused problems in HLSL. My best guess is that HLSL treats divide by zero as a FLT_MAX result. The documentation for the rcp instruction in HLSL seems to make this explicit:
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/rcp---vs
This also differs a bit from IEEE behavior where the sign of the denominator should be carried to the result. I'm mostly guessing at how DX Classic would interpret an IEEE float when loading into a shader that doesn't support IEEE. …

Fix for divide by zero breaking Mac/Vee Tsah

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIHelpers.py
Scripts/Python/plasma/PlasmaKITypes.py
Scripts/Python/xLocTools.py
Sources/Plasma/FeatureLib/pfMessage/pfKIMsg.h

Previously, these messages were localized by the sender and sent via net propagation. By Adam's request for a return to UU capabilities, these messages now send one or more LOC key strings along with a flag indicating for the receiver to process the message localization themselves.
As a side effect of my digging and the use of the new chat flag, I have also fixed at least one cause of AFK response spam.
Needs https://github.com/H-uru/moul-assets/pull/131.

Ensure emotes and afk message are shown in receiver's localization

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIChat.py
Scripts/Python/plasma/PlasmaKITypes.py

Add a new chronicle entry to store the RGB value of the user's current `/textcolor` setting.

Save and load the user's /textcolor setting to persist it between game sessions

---

Scripts/Python/islmRegisterNexusLink.py

Missing elif caused Kveer to register as a city link in nexus
Minor issue.
Your able to delete the link no issues, when you use it you end up on the city docks instead of in kveer.
The correct kveer link is lower in the nexus listing as usual as well.

Fix Kveer was registering itself as a city link

---

Scripts/Python/clftYeeshaPage08.py

Found another missed script for cleft start when I was going through scripts.
This adds the new way sounds work for Relto Pages to page 8 (Rain Page)
It also allows you to get the rain page as many times as you want, instead of only being able to get it once.
This behaviour is the same as the other relto pages now.

Missed script change for cleft start

---

Scripts/Python/ki/xKIChat.py

Due to the chat logging code being inside the for-loop over the miniKI and microKI chat areas, it was previously a sad time when using the chat log:
```
(05/11 21:46:28) Chat.log started...
(05/11 21:46:28) Chat.log started...
(05/11 21:46:32) [ERROR] Error: Don't know how to "/fake"
(05/11 21:46:33) [ERROR] Error: Don't know how to "/fake"
(05/11 21:46:50) AbelarTL does a dance
(05/11 21:46:50) AbelarTL does a dance
(05/11 21:47:07) Text reset to default color(s).
(05/11 21:47:07) Text reset to default color(s).
(05/11 21:47:12) ...Chat.log stopped.
(05/11 21:47:12) ...Chat.log stopped.
```
Now it is a less sad time.
```
(05/12 23:58:02) Chat.log started...
(05/12 23:58:07)  Zaroth TL: hello
(05/12 23:58:17) Text color now set to blue.
(05/12 23:58:25)  Zaroth TL: foo
(05/12 23:58:33) To …
```

Fix so chat logs don't duplicate every line

---

Scripts/Python/ki/xKIChat.py

*sigh* I missed a test case. It exploded. Reported by Calum on OU discord.
Previously, `/textcolor <integer>` (integer may be valid hex or invalid altogether) would explode because it would try to go through the (int, int, int) path and cast the `None` value of `arg2` as an int. So... let's check if `arg2` and `arg3` are None before we try to process things as an int or float triplet.

Fix my dumb so /textcolor 999 won't try to convert None to int and die

---

Scripts/Python/plasma/Plasma.py
Sources/Plasma/FeatureLib/pfPython/pyVaultAgeInfoNode.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultNode.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultNode.h
Sources/Plasma/FeatureLib/pfPython/pyVaultNodeGlue.cpp

#1142 revealed inferior AgeInfo node finding code is required due to `ptVaultNode.findNode()` not allowing searches deeper than one level. This allows them.

Allow `ptVaultNode.findNode()` to search deeper than one level.

---

Scripts/Python/Ahnonay.py
Scripts/Python/AhnonayCathedral.py

Steps to trigger bug:
Visit your personal Ahnonay Cathedral, leave without going to your Ahnonay instance
Visit someone else's Ahnonay
Your Ahnonay book on the Relto Bookshelf is now tied to the Ahnonay you visited instead of your personal Ahnonay
Basically the previous code had no way of checking that you were in the correct Ahnonay sub age.
If you had visited your Ahnonay Cathedral, the next Ahnonay you visited became the one your Relto bookshelf book was tied to.
So added a check in Ahnonay to verify the Cathedral subage was your personal Cathedral and not someone elses.
This check allows the owner variable to be correctly set.
Also added a check in Ahnonay Cathedral that the GUID that is set for your AhnonayLink is the correct GUID.
If it isn't the correct one, it sets it to the …

Fixes wrong Ahnonay instance bug

---

Sources/Plasma/PubUtilLib/plAvatar/plAvBrainClimb.cpp

Possible fix for crashing when the climb brain attempts to call a nulled fCurStage.

Climb Brain crash fix

---

vcpkg.json

The libuuid port and vcpkg are now stricter about enforcing that libuuid is a Linux only library. Attempting to build libuuid on macOS fails the build.

Don't build libuuid on macOS with vcpkg.

---

Scripts/Python/xPodBahroSymbol.py

Pod portals animation and sounds would stick around for any players in the age if the age owner went through the portal or left the age when the animation was active.
This issue is caused by the responder being netforced and controlling the experience for anyone in the age.
When the person controlling it leaves the age, the responder doesn't finish its commands and stalls at whatever step it was left at.
In this case you get left with portal sparkles for anyone that missed the portal.

Fix pod portal responder for multiplayer

---

Scripts/Python/ki/__init__.py

Previously, when trying to delete a player from Recent, Buddies, or Ignore List folders (or whatever folders in the Big KI that allow deleting players), the folder name was never populated.
Now, it is. 🎉

Ensure providing current folder name for delete player localized message

---

Scripts/Python/Ahnonay.py

Recent change to ahnonay script failed to initialize the folder variable.
This caused the script to crash and Ahnonay to fail to load correctly.

Ahnonay script crashing

---

Scripts/Python/ki/__init__.py

Reported by @DamnBriggsy on OU discord. The H'uru client was not allowing players to move or delete items sent by other players out of their inbox. Notes, pictures, and marker games could not be moved to other folders or deleted from the player's folders.
Fixed this by splitting out checks for mutability (e.g., editing journal notes or editing titles of journals/pictures) versus checks for deletability/movability (e.g., nearly any journal, picture, or game other than DRC mails) and using appropriately. Journals, pictures, and games sent by other people can be safely deleted by the recipient without affecting the original sender or creator's items.
Also allow users to delete a marker game from their folders when they are still pending a KI upgrade in order to be able to play it, otherwise …

Allow players to move or delete inbox items (besides global inbox items)

---

Sources/Plasma/FeatureLib/pfMoviePlayer/plMoviePlayer.cpp
Sources/Plasma/FeatureLib/pfMoviePlayer/plMoviePlayer.h

- Freeing frames after we’re done with them to keep memory use flatter
- Caching the last frame so if the surface needs to be recreated we can populate it with image data
The first change frees frames after we don't need them. I don't think there is a leak here as everything was freed at the end of the movie. But memory use previously climbed during playback.
The second change is a little more nitpicky. On Mac, if the client changed resolutions during playback (or swapped between windowed/fullscreen) display would be blank momentarily. This is because the movie player only draws when it has a new frame. By retaining the last frame, the movie player can also immediately draw when a new surface is created in response to a reconfiguration.
I'm guessing Windows theoretically has similar …

Improvements to plMoviePlayer

---

Sources/Plasma/FeatureLib/pfCharacter/pfConfirmationMgr.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUITextBoxMod.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUITextBoxMod.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlTextBox.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlTextBox.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlTextBoxGlue.cpp
Sources/Tools/MaxComponent/plGUIComponents.cpp

Now with many less allocations. This fixes problems reported about the Python API nuking unicode characters when going through the non-W codepath.

`ST::string`-ize `pfGUIControlTextBox`.

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleCmd.cpp

This (IMO) significantly improves the formatting of the console documentation, and makes the command group sections collapsible.
Example output of these changes: https://bl.ocks.org/dpogue/raw/3156ee19b6a55d659e2ac92c96527d60/?raw=true
One side effect is that console command arguments will now always be wrapped in `[` `]` when printed anywhere (including in the console itself), but IMO this still ends up being more readable:
`Some.Group.Command [string name], [bool value]` vs `Some.Group.Command string name, bool value`

Reformat HTML Console documentation output

---

Scripts/Python/ki/__init__.py

Marker list panel's scroll buttons won't be shown when there are no markers in the list when editing or playing the game. Also appropriately set the scroll position (and thus recalculate scroll up/down button visibility) when displaying an in-progress game where one or more markers have been found.

Fix so marker list panel's scroll buttons are appropriately displayed or not

---

Scripts/Python/xDialogStartUp.py

- Prevent python errors when clicking Explore/Delete buttons with empty explorer list
- Adjustment so clicking the first Create Explorer slot on an empty list after a Create->Back path or after deleting the only explorer will properly go to the Create dialog again (instead of doing nothing when clicked)
Should close #1169.

Prevent python errors on startup dialog with empty explorer list

---

Scripts/Python/ki/__init__.py
Scripts/Python/xAvatarCustomization.py
Scripts/Python/xDialogStartUp.py
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListBoxMod.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListBoxMod.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListElement.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListElement.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlListBox.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlListBox.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlListBoxGlue.cpp

Now with less string-y death and sadness, including:
- Allow users to be created successfully from startup when names include unicode characters like ü and ó and ä and such
- Make unicode-including player names show up correctly in the avatar customization title bar
- A ton of stuff that displays player names in KI lists, Big KI footer, Big KI content titles, and the Send To Player field
- Some stuff around marker game title creation and editing
- Adjust the pyGUIControlListBoxGlue to treat its input string as unicode so KI folder player lists (left side collapsible lists) are displayed with unicode text properly

Support create player with unicode name and fix a bunch of string-murdering

---

Scripts/Python/ki/xKIChat.py

Since /textcolor overrides all chat colors (except clickable URLs) we automatically add the chat prefixes to specify what context a message is from for non-broadcast/status messages. Also added to chat logs all the time because those never have colors to indicate where a message came from and things can get confusing. Requires https://github.com/H-uru/moul-assets/pull/147.

Add prefix to chat logs, plus to chat headers when /textcolor is enabled

---

Scripts/Python/xAvatarCustomization.py

Clothing and Clothing Categories are sorted alphabetically by the name (not the description)
This mostly sorts everything in a semi-correct order.
I tried sorting by description and the item that clothing category represented was not usually the first thing shown.
Fixed a bug that would cause the clothing to reset when you were clicking the right/left arrows and it would disappear.
This fix avoids the issue by always showing the arrows, and never hiding them.
The bug can still happen if you click on anything inside the "Additional Options" that is not a piece of clothing.
The code currently tells the section to refresh itself whenever you click on it and when you click on something that isn't a piece of clothing it just resets everything in that section.

Sort clothing in closet and fix clothing resetting when clicking on arrows

---

Scripts/Python/plasma/Plasma.py
Sources/Plasma/FeatureLib/pfPython/pyVaultTextNoteNodeGlue.cpp

These method names collided with the vault node type getters and setters in `ptVaultNode`. In previous experiments with removing the manual upcasting junk, this collision broke the KI and imagers. Fix it now to match the variant found in `ptVaultFolderNode`. In my grepping, the text note variants are currently unused.

Fix method name collisions in `ptVaultTextNoteNode`.

---

Sources/Plasma/FeatureLib/pfConsole/CMakeLists.txt
Sources/Plasma/FeatureLib/pfConsole/pfConsole.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsole.h
Sources/Plasma/PubUtilLib/plClipboard/plClipboard.cpp

A lot of the changes are just churn to avoid duplicating console logic. Unfortunately, this does not attempt to make the console unicode friendly. The console still uses the ACP.
If you paste multi-line text into the console, you will get this prompt:
and all intervening lines (ie all but the last) are executed.
Fixes #1113.

Add clipboard support to the console.

---

Scripts/Python/clftImager.py

If you did the relto start, you would be prevented from entering the TPOTS imager code until you solved the cleft age.
Before the cleft start, you could do both Ahnonay and Er'cana, acquire the TPOTS imager code to solve that puzzle before you ever solved the cleft.
This fixes that issue.
It also now prevents you from brute-force solving the first journey code.

Fix issue with TPOTS code and Relto start

---

Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/CoreLib/hsThread_Unix.cpp
Sources/Plasma/CoreLib/plFileSystem.cpp
Sources/Tools/plSystemInfo/main.cpp

On macOS, this will use a more standard `~/Library/Application Support/Uru Live` path.
On Linux/Solaris/etc., this will be `~/.config/Uru Live` which matches the XDG spec.
~Uses the POSIX standard [`wordexp`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/wordexp.html) function to expand the user home path, rather than relying on the `$HOME` environment variable.~
/fyi @colincornaby

Better user data paths on non-Windows

---

Scripts/Ports/python3-cairosvg/portfile.cmake
Scripts/Ports/python3-cairosvg/vcpkg.json

@Hoikas requested that I update vcpkg now that it includes the latest python 3.10 stuff. In theory this also includes the update to string_theory to fix the char buffer issue. I dunno what else changed. YOLO?

Update vcpkg submodule to current

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIHelpers.py

Developed while trying to diagnose a problem Mirphak reported in the OU discord (the PR for the real issue is still to come). The node comparison method returning a -1/0/1 result seems much more complicated and potentially worse performance than the new streamlined version. I don't have evidence for any performance changes; not sure how to run a fair comparison. But I find it easier to read now, at least.

Simplify KI inbox sorting... hopefully

---

Scripts/Python/ki/__init__.py
Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIHelpers.py

Bug introduced in https://github.com/H-uru/Plasma/pull/1129 by me. Could infinitely recurse when opening the Big KI Incoming folder and it added a player to a full Recents list, triggering an addition and removal, which triggered the Big KI refresh again, which tried to add/remove another player to Recents, etc. With this fix, it will recurse to a maximum of 50 (max Recents list size) refreshes if the Recents folder was empty and never try to add more Recents from Inbox Savers if the Recents list is already full.

Fix for infinite BK refresh due to addition to Recents with inbox item senders

---

Sources/Plasma/CoreLib/plCmdParser.cpp
Sources/Tests/CoreTests/test_plCmdParser.cpp

The tokenizer as it was written would split tokens midway if they contained a flag character. I made changes so that the initial tokenization is done by whitespace and separators, and then flags are removed from the front instead of a split being used.
My assumption is that all arguments have to be separated by whitespace and separators.
This should fix things like -Age=GuildPub-Writers

Fixing parser to not split tokens containing flags

---

Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp

This was discovered when testing Fahets Highgarden.
PhysX 4.1 doesn't support trigger shapes that are triangle regions. Instead of dropping them on the floor, however, PhysX seems to think that making them a normal, solid simulation shape is the way to go. Therefore, we force them to convex hull.
A better fix will be to refuse to export these obviously flawed regions in Korman.

Add mitigation for triangle mesh regions.

---

Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/FeatureLib/pfDXPipeline/plDXPipeline.cpp

ALIGN is an already defined macro on macOS. Removing use of ALIGN for all platforms, and scooting Windows over to alignas.

Removing ALIGN macro

---

Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp
Sources/Plasma/NucleusLib/pnNetBase/pnNbConst.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2File/pnNpCli2File.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.h

Fixes for the patcher running on macOS (and likely Linux). The netcode linked some string lengths to MAX_PATH, but this is variable for each platform and can cause problems in network transactions.

Fix platform-dependent path problems in the patcher.

---

.github/workflows/ci.yml
CMakeLists.txt
cmake/PlasmaTargets.cmake

Instead of cluttering up Xcode with a scheme for every library, let's tell it to only include schemes for the executable targets.
Also add a macOS-specific option to tell it to do universal multi-architecture builds (disabled by default).

Clean up autogenerated Xcode schemes

---

Sources/Plasma/PubUtilLib/plPipeline/plTextFont.cpp

Initial work. Rendering well - might need some extremely fine tuning in the future.
I would totally be open to this being a FreeType implementation in the future. Unfortunately, I do not know FreeType. So for now we get a CoreText/Quartz implementation. 😀 This will get the Mac working until something more properly cross platform can be done.
This is also such a small chunk of code it may be fine to keep in platform specific versions. But there might be greater questions about the future of text in Plasma that go into a FreeType sort of decision.

Mac/Quartz version of plTextFont

---

Sources/Tools/plFontConverter/plFontFreeType.cpp

Fix plFontConverter crash when reading .ttf files. Fixes #1144.

Init large arrays on heap instead of stack in font creation

---

Scripts/Python/xSimpleImager.py
Scripts/Python/xSimpleImagerClueHandler.py

This would be used for showing a puzzle image or any static image for imagers at a set interval.
It does require an additional imager object setup to function properly.
You create another imager object, and set the final texture to use the static image you want.
When the timer for the static image is up, it will hide the normal imager object and show the static imager object instead.
That imager goes for the standard image time, then resumes the standard imager images.

Code for static imager image to show in imager slides

---

Sources/Plasma/FeatureLib/pfCharacter/pfMarkerInfo.h
Sources/Plasma/FeatureLib/pfCharacter/pfMarkerMgr.cpp

If user code (ie Python) spawns a marker then quickly deletes it, the deletion may occur before the global marker object is cloned. This results in trying to call `InitSpawned()` on a null pointer. Fix that.
Drive-by: fix a potential memory leak.

Fix a pfMarkerMgr crashing problem.

---

Sources/Plasma/CoreLib/hsStream.h

Use perfect forwarding in `hsStream::WriteFmt()`.

---

Sources/Plasma/FeatureLib/inc/CMakeLists.txt
Sources/Plasma/PubUtilLib/inc/CMakeLists.txt
cmake/PlasmaTargets.cmake

The benefit to this change is that for IDE-based generators (eg Visual Studio), you can now see the headers in a dedicated project instead of either having ghost headers that appear only as includes (or, worse, the headers duplicated into all consuming projects).
Required by #1217.

Add object library support.

---

Scripts/Python/xLinkingBookDefs.py

* Adds Book and Linkpoint definitions for Elonin, Eder Naybree, and Highgarden to `xLinkingBookDefs.py` to match MOULa.

Add Elonin, Eder Naybree and Highgarden definitions

---

Sources/Plasma/FeatureLib/pfPython/cyMiscGlue.cpp

Long is 8 byte outside of Windows, not 4. Hardcoded uint32_t is causing pointer corruption on the stack because Python expects an 8 byte type.
I did a quick check and didn't see any other issues that looked like this in cyMiscGlue - doesn't mean they aren't lurking.
Intel has a guide for long size here:
https://www.intel.com/content/www/us/en/developer/articles/technical/size-of-long-integer-type-on-different-architecture-and-os.html

Fixing chat crash on macOS (and likely Linux)

---

Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.cpp

The controller was being removed from the scene - but user data wasn't being cleared. Mangled key was being processed during physics events causing crashes.
I was investigating this but @Hoikas wrote the fix.

Fix for crash when a different player leaves

---

cmake/FindOpenAL.cmake
cmake/FindSecurity.cmake

It looks like CMake changed the expected of interface libraries when the end library is a framework. Frameworks were failing to link properly previously - this seems to fix them. Dylibs were unaffected.
This is lifted from CMake's FindOpenCL.cmake:
https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindOpenCL.cmake

Fixing Mac builds with CMake 3.24

---

Sources/Plasma/PubUtilLib/plInterp/plATCEaseCurves.cpp

This one is gonna be a bit weird. macOS (and maybe Linux in the future) is tripping the assert on 331 repeatedly. There is a key difference between macOS and Windows on the line I changed.
M_PI as a float is 3.14159274. hsConstants::pi<float> is also 3.14159274.
acos(-1.0f) should be Pi. And on Windows acos(-1.0f) is:
3.14159274.
Makes sense. But on macOS, acos(-1.0f) is instead:
3.1415925
I don't know why. It's a big enough change it moves around this function and trips the assert.
Basically the best solution seems to be to force the acos to be done as a double, and then downcast that into a float. That's the same way hsConstants::pi<float> converts it's value down to float.
`(float)acos(double(R / sqrt(Q3)))` properly resolves to 3.14159274. Even though it's stored in a double, we need …

Fixing plSplineEaseCurve asserts on Mac

---

Sources/Plasma/CoreLib/plFileSystem.cpp

The code as written should have worked - but Apple seems to have changed the way they do things. There are other reports of /proc/curproc/file disappearing from macOS. I'm not sure when that happened.
This code gets called as part of the patching process - which is why I wrote this change. Patching did not work without this change.
I defined a new implementation - but I realized this will only work if the current process is an app bundle. For a flat executable (like your command line patcher @dpogue), this probably isn't going to work. I'm open to other suggestions - this take is very AppKit centric.

Fix for plFileSystem not finding self on Mac

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/NucleusLib/inc/plPipeline.h

This PR adds some initial support for deep/10 bit color supports in the graphics pipelines. It's still up to the pipelines to implement - but this adds the option for 10 bit gamma tables.
Uru assets tend to be 8 bits or less per color channel - but color blending happens in a 16 bit color space. So does lighting, effects like water, and fog. These effects can suffer banding in an 8 bit color space. For example, the fog near Kerath's Arch can show banding. Allowing 10 bit output on compatible displays can reduce or eliminate banding, and allowing blending outside of 8 bit color resolution.
This commit doesn't attempt to enable wide color (either the P3 color space or HDR.) Metal can also render in these modes - but it would likely require assets specifically built for wide color. Allowing …

Deep Color/10 bit support for pipelines

---

Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglCore.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglCore.h
Sources/Tools/CMakeLists.txt
Sources/Tools/plFilePatcher/CMakeLists.txt
Sources/Tools/plFilePatcher/main.cpp
Sources/Tools/plFilePatcher/plAllCreatables.cpp
Sources/Tools/plFilePatcher/plFilePatcher.cpp
Sources/Tools/plFilePatcher/plFilePatcher.h

This provides a simple patcher that can be run on the command-line, intended for testing the ASIO cross-platform networking code, but also because it might be useful in general.
Windows-only for the moment, until the cross-platform sockets are merged.

Add plFilePatcher command-line tool

---

Sources/Plasma/CoreLib/plFileSystem.cpp
cmake/CompilerChecks.cmake
cmake/check_builtin_available.cpp
cmake/hsConfig.h.cmake

Technically, the issue here is the `__builtin_available` on compilers that don't support it (such as gcc), but we can effectively mask it by only running the `__builtin_available` check if we actually need to (when sysdir.h is found).

Fix macOS compiler errors when sysdir.h is not available

---

Sources/Plasma/Apps/plPythonPack/main.cpp
Sources/Plasma/FeatureLib/pfPython/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue2.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonCallable.h
Sources/Plasma/FeatureLib/pfPython/plPythonConvert.h
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.h
Sources/Plasma/FeatureLib/pfPython/pyAlarm.cpp
Sources/Plasma/FeatureLib/pfPython/pyAlarm.h
Sources/Plasma/FeatureLib/pfPython/pyVaultNode.cpp
Sources/Tools/MaxMain/plPythonMgr.cpp

As of Python 3.8, a new calling convention was added to CPython. The new convention is faster, per the the PSF, so we now use it. The major benefit to it on our end is that we don't have to construct intermediate Python tuples holding function call arguments anymore. Instead, we simply pass arrays of `PyObject*`. As part of this, I added scaffolding for more generic C++ -> PyObject* conversion.
There is still lots of room for improvement in the Python API in a large variety of topics, for example:
- There are many places in `plPythonFileMod` where an `ST::string` is being `c_str()`'d and the result being sent to Python.
- All of the glue should probably be updated to use [`METH_FASTCALL`](https://docs.python.org/3.8/c-api/structures.html#METH_FASTCALL) to remove the overhead of parsing …

Use PEP 590 Vectorcall

---

Sources/Plasma/FeatureLib/pfPython/plPythonCallable.h

PyObject varient of CallObject is not declared before pyObjectRef CallObject varient. This could lead to pyObjectRef CallObject calling itself repeatedly in since the desired PyObject varient is not technically in scope.
I took the approach of declaring the function instead of moving the order - as it might be a bit safer and more clear for future developers. I'm assuming there may be some discussion on the approach (or style of where that declaration should go.)

Fixing possible deadlock in plPythonCallable

---

Sources/Plasma/CoreLib/HeadSpin.h

…matching the MSVC behavior.
This silences some warnings about functions not returning a value when a switch statement with `DEFAULT_FATAL` is at the end of the function.

Give GCC and Clang a hint that DEFAULT_FATAL() is unreachable

---

Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommandsNet.cpp
Sources/Plasma/NucleusLib/pnDispatch/plDispatch.cpp
Sources/Plasma/NucleusLib/pnNetCommon/plNetApp.h
Sources/Plasma/PubUtilLib/plNetClient/plNetCliAgeJoiner.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgr.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgrSend.cpp
Sources/Plasma/PubUtilLib/plNetCommon/plNetObjectDebugger.cpp
Sources/Plasma/PubUtilLib/plNetCommon/plNetObjectDebugger.h
Sources/Plasma/PubUtilLib/plSDL/plStateDataRecord.cpp
Sources/Plasma/PubUtilLib/plSDL/plStateVariable.cpp

This allows us to get rid of the final user of `hsStrLower()`, which can now be removed from the code.  As a bonus, we also don't need to keep around copies of strings converted to lower-case any more, since ST already enables all the case-insensitive comparisons we need to perform.

Port plNetObjectDebugger to ST::string

---

Sources/Plasma/NucleusLib/pnNetProtocol/Private/pnNpCommon.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/pnNpCommon.h
Sources/Plasma/PubUtilLib/plAvatar/plAvatarClothing.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultNodeAccess.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultNodeAccess.h

This also cleans up a hack where a private type needed to be exposed publically for helper functions in pnNpCommon.cpp.

Replace NetVaultNode::Blob with a std::vector

---

Sources/Plasma/Apps/plClient/winmain.cpp

Previously, clicking the button with no Server.Signup URL set would send the login window to the background with no explanation.

Disable "Need an account?" button if no Server.Signup URL is set

---

Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/PubUtilLib/plPhysX/plKickableLog.h

I'll be honest, the real reason why I'm doing this is because CLion (in non-clangd mode) doesn't understand `__noop`. But AFAICT there's no good reason to use a non-standard extension here anyway.
Also removed a couple of unused and broken macros.

Always use standard `((void)0)` instead of MSVC-specific `__noop`

---

Sources/Plasma/CoreLib/hsStream.cpp

This was accidentally broken in #617. See commit message for details.

Remove incorrectly "fixed" obfuscation check in `ReadSafeWString`

---

Sources/Plasma/PubUtilLib/plAudio/plWin32Sound.cpp

This should prevent subtitles from being sent to the KI when audio is muted or the source is so far away that it is not audible.

Add volume threshold for subtitled audio before sending subtitles

---

.github/workflows/ci.yml

Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This also adjusts the workflow so that it always checks for the 3DS Max token before trying to clone the Max SDK repo, otherwise forks will get `Missing input 'token'` errors (which are harmless but annoying)

Fix for GitHub's set-output deprecation & workflow warnings

---

Sources/Plasma/Apps/plPythonPack/PythonInterface.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonCallable.h

The macOS GitHub Actions runner on my fork has started defaulting to the system's Python 3.11 installation, and these changes were needed to stop the builds failing. This makes it compile, but no promises about whether there are other changes needed to make it actually work.
(Aside: We're using homebrew on macOS to install Python 3.10 and telling CMake to use that... and it's still grabbing the system Python 3.11 somehow...)
* eval.h has been removed in Python 3.11. That's not a problem though because it's been included in Python.h since at least Python 2.7, and we're already including Python.h so we don't need to include either eval.h or compile.h.
* `_PyObject_CallNoArg` static inline method has been made private. Use the public `PyObject_CallNoArgs` method (available since Python 3.9) …

Attempt to fix compiling with Python 3.11

---

Sources/Plasma/CoreLib/hsStream.h
Sources/Plasma/NucleusLib/pnNetCli/pnNetCli.h
Sources/Plasma/PubUtilLib/plFile/plEncryptedStream.cpp
Sources/Plasma/PubUtilLib/plPipeline/plPlates.cpp
Sources/Plasma/PubUtilLib/plPipeline/plPlates.h

Most of these are fairly noisy because they're in header files.

Fix some truncation warnings.

---

Scripts/Python/xAgeSDLBoolActivatorComboSet.py
Scripts/SDL/xAgeSDLBoolActivatorComboSet.sdl
Sources/Plasma/FeatureLib/pfPython/plPythonSDLModifier.cpp

In response to a report by @EhrenCG on the OU discord and comment that @ametist365 would like to try the sliding window variation. When the puzzle button python file mod is used without providing feedback to the user that the combination is reset on a wrong click and prompting them to start over from the beginning of the sequence, it can seem that entering the right combination will not work correctly. With this new attribute added for puzzles, the script will check a sliding window of the last N entries so that, for example, entering 1,1,2,3 will match a combination of 1,2,3 rather than failing after 1,1 and expecting the user to start the sequence over.
**Original report by Ehren (re: flower button sequence in Elonin):**
Guys, I feel like I've found a major programming oversight and it …

Add capability to use a sliding solution window for puzzle buttons

---

.github/workflows/ci.yml
NuGet.Config.in
cmake/VcpkgToolchain.cmake

The NuGet.config file wasn't working reliably for uploading packages to GitHub's package registry during CI builds, in part because NuGet really wants you to use an API key instead (and those API keys are apparently encrypted in a machine-specific way). It also caused issues when building from forks because it would try to use the fork for all the packages instead of falling back to the H-uru repo.
So, now the NuGet.config file is only set up to read from the H-uru packages. This should (hypothetically) still allow anyone building on their own machine to grab the binaries from GPR automatically.
In CI, we manually configure NuGet credentials ahead of time, telling it to read/write from the current repository, but still allowing it to fall back to the NuGet.config file that allows reading …

Fix (and simplify) vcpkg NuGet binary caching

---

.github/workflows/scripts_review.yml

This avoids warnings about deprecation of node12 in GHA workflows.

Update script review workflow to latest versions

---

Sources/Plasma/NucleusLib/pnEncryption/plBigNum.h

The "fast" BigNum prime check function is deprecated in OpenSSL 3 because it apparently doesn't do a sufficient job of testing prime-ness. This newer method does it properly, which probably means it's slower, but probably not to a degree that it noticeably impacts performance (if this method is called at all, which it doesn't seem to be?).
Also, the `Div` method was complaining about a ternary that tested whether `this` was null, which isn't possible in well-defined C++ code. I tried to look at where this was being used to see how that could happen and it turns out the function wasn't being used at all, so I just removed it entirely.

Fix OpenSSL 3 deprecation warnings from plBigNum

---

.github/workflows/ci.yml

This sets up the workflow to do arm64 builds in the future, but they're disabled now because of issues getting python3 to build with vcpkg for arm64.
We originally moved from vcpkg to homebrew for macOS dependencies because of issues with vcpkg caching and slow build times when macOS had to recompile several large dependencies (PhysX, OpenSSL, Python, etc.) on every single build. With the caching fixed, these builds should run much more quickly now (after the first run), comparable to the runtime with homebrew dependencies.

Run macOS builds with vcpkg again

---

Sources/Tools/plFilePatcher/main.cpp

The progress output was janky because it was flushing when the buffer filled instead of when we printed (because stdout doesn't flush until there's a newline or the buffer fills).
Now it looks smoother.

Fix plFilePatcher progress bar flushing to screen

---

Sources/Tests/CMakeLists.txt
cmake/SubmoduleUtils.cmake
cmake/VcpkgToolchain.cmake

This will hopefully allow people to just use Visual Studio to clone the main Plasma repo, and have it deal with git submodule initialization as part of the build process, rather than needing people to manually run a git command which clones submodules recursively.

Try to automatically init submodules with CMake

---

Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGateKeeper.cpp

The reconnect timer prevents deallocation if a reconnect actually occurs. The reconnect timer removes the Gatekeeper connection from the connection list, preventing the timer for being stopped later.
When a reconnect event occurs, the refcount logging looks like:
Inc 0x600003b00000 Lifetime: 1
Inc 0x600003b00000 ReconnectTimer: 2
Inc 0x600003b00000 Connecting: 3
Dec 0x600003b00000 Connecting: 2
Inc 0x600003b00000 Connecting: 3
Dec 0x600003b00000 Connecting: 2
Inc 0x600003b00000 Connecting: 3
Dec 0x600003b00000 Connecting: 2
Inc 0x600003b00000 Connecting: 3
Dec 0x600003b00000 Connecting: 2
Inc 0x600003b00000 Connecting: 3
Dec 0x600003b00000 Lifetime: 2
Dec 0x600003b00000 Connecting: 1
(Where 0x600003b00000 is a plNGLGatekeeper instance.)
This logging is from plFilePatcher which is …

Fixing timer not deallocating after reconnect

---

Scripts/Python/clftYeeshaPage08.py

This fixes the issues noted in #1274 
Relto Pages in the rainy cleft before would sometimes have the holographic page show instead of the correct solid background.
It could also show the previous symbol used in addition to the holographic page.
This code in my testing fixed the issues.

Fixes Yeesha Page 8 issues

---

Sources/Plasma/NucleusLib/pnUUID/pnUUID_Unix.cpp

Windows encodes the UUID fields in little endian, but *nix encodes as an array of unsigned chars (which is a big endian encode.) This was leading to unexpected failures against the Cyan patch server when the product UUID was sent over the wire.
This change makes it so that UUIDs are consistently encoded internally in Plasma. A little endian encoding will always be used in Plasma because UUIDs are encoded directly into network packets, and the server expects a little endian encoding.
I don't know what implications this could have for Windows/ARM. I think Windows/ARM is little endian as well - but a lot of this is baking in assumptions about how Windows encodes it's GUID structure and building an ad hoc standard off of that.

Fixing endian encoding on *nix systems for UUIDs

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfDXPipeline/plDXPipeline.cpp
Sources/Plasma/PubUtilLib/plGLight/plShadowMaster.cpp
Sources/Plasma/PubUtilLib/plGLight/plShadowMaster.h

There are two global variables defined in plDXPipeline that are used by the Console.
* One is the maximum blur scale for shadows. There are already several configurable values in plShadowMaster, so I've just added this as another value there so it has a proper home instead of being referenced via extern.
* The other is a debug flag that restricts the rendering capabilities of the DirectX pipeline to that of a GeForce 2 card. This seems pretty DirectX-specific, so I opted to just wrap the console commands in `#ifdef` so that they are only enabled when the DX pipeline is enabled (and thus the externed variable is defined).
These were showing up as linker when I tried to compile a Linux build with plGLPipeline, because they were referenced from the console commands.
/cc @colincornaby because …

Fix DX Pipeline externed global variables

---

Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore_Apple.cpp

This moves the Apple Keychain integration onto the supported APIs and off the deprecated ones. The APIs we use were deprecated in 10.10, and the replacement APIs were added in 10.6. The SecItem class APIs replace the SecKeychain class APIs. Note that we were already using one SecItem API - so this code already required 10.6.
The deprecated API was producing warnings so this will clean those up.

Moving Keychain integration off deprecated APIs

---

CMakeLists.txt
Sources/Plasma/Apps/plPageOptimizer/main.cpp
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/PubUtilLib/plAnimation/plAGAnimInstance.h
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainHuman.cpp
Sources/Plasma/PubUtilLib/plResMgr/plKeyFinder.cpp
cmake/CompilerChecks.cmake
cmake/FindPhysX.cmake

This allows removing some compiler-specific CMake code.

Replace last uses of MSVC-specific `_DEBUG` with `HS_DEBUGGING`

---

Sources/Plasma/CoreLib/hsStream.cpp

Previously, a pair of "skip" and "piks" tokens (for `GetToken`) or lines (for `ReadLn`) was treated like a block comment - anything between them was simply ignored. Because this was part of hsStream, it affected many file types (.csv, .fni, .ini, .sdl, .srt), even though many of them already have proper syntax for comments.
This feature (?) isn't documented anywhere and apparently no existing code or data files rely on this, so just get rid of it to avoid confusing behavior if someone uses the word "skip" in the wrong place.

Remove special handling of skip/piks tokens and lines in `hsStream`

---

Scripts/Python/ki/xKIChat.py

To reproduce:
1. Use a keyboard layout with non-ASCII keys
2. Have "Start Chat" not mapped to anything in the Key Map
3. Be in-game without chat open
4. Start chatting by pressing a non-ASCII key
Without this fix, the first character was incorrectly re-encoded from UTF-8 to Latin 1 (e. g. "ä" became "Ã¤").

Fix mis-encoded text when starting chat with a non-ASCII character

---

Sources/Plasma/NucleusLib/pnNetCli/pnNcCli.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/pnNpCommon.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/pnNpCommon.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp

Previously the game crashed when reading truncated vault node data.
I implemented these checks in a similar way as in the other `IRead*` functions further up in pnNpCommon. Perhaps these two sets of functions should be merged... Or maybe all of these functions should be replaced with `hsReadOnlyStream`/`hsRAMStream`? (Most of the `hsStream::Read*` methods don't really handle truncated data either, but at least they don't crash right away.)

Guard against invalid data when reading vault nodes

---

Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore_Apple.cpp

- Default arguments to CFStringCreateWithCStringNoCopy deallocate the source buffer on dealloc. kCFAllocatorNull prevents this.
- Creating only on set of CF ojbects in SetPassword.
- SetPassword wasn’t setting the password data on the initial store.

More bug fixes for Apple password store

---

.github/workflows/ci.yml

vcpkg leaves quite a bit of garbage when it builds the libraries. Unfortunately, this results in the available disk space being exhausted when building our tests, causing the run to fail.

Prevent Windows CI runners from exhausting disk space.

---

Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp

- Don't spin-wash an `ST::string`.
- Reserve vector storage to prevent extra allocations.
- Protect against null net clients.

Fix some problems with `PtGetPlayerList()`.

---

Sources/Plasma/Apps/plClient/win32/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/plClientLauncher.cpp

The previous code incorrectly assumed that the buffer from curl is a zero-terminated string.
This issue was almost never noticeable, because I guess in practice both buffers start out zero-initialized. One case where it was noticeable: when the server dynamically changes the status message to a shorter message, the client displayed garbage characters from the previous (longer) message at the end.

Fix buffer overread and incorrect termination of server status message

---

Sources/Plasma/FeatureLib/pfPython/pyGlueHelpers.h

Previously, an integer was returned. Returning an actual boolean enables improved Python code (eg `meow() is True`) and allows f-strings with these booleans to print the words `True` and `False` instead of the integers `1` and `0`.

Return a real bool from `PYTHON_RETURN_BOOL`.

---

Sources/Plasma/FeatureLib/pfSurface/plGrabCubeMap.cpp

The front and back face suffix strings were reveresed compared to the output of `hsMatrix44::MakeEnvMapMatrices()`.

Fix `GrabCubeCam` suffixes.

---

Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgHandler.cpp

Although we are indeed using a simplified object ownership model, we do still want to send out broadcasts to game scripts about when the ownership was changed.
This is needed for the upcoming rewrite of xBlueSpiral to use swappable backends. See #1217.

Fix `OnOwnershipChanged` callbacks.

---

Scripts/Python/bhroBahroBlueSpiral.py
Scripts/Python/bhroBahroMink.py
Scripts/Python/bhroBahroPOTS.py
Scripts/Python/bhroBahroPod.py
Scripts/Python/bhroBahroYeeshaCave.py

Assets - https://github.com/H-uru/moul-assets/pull/216
@EhrenCG pointed out that when your camera is forced to third person in the Bahro Pole cave it doesnt revert that camera and your arrival in Relto will have a messed up third person camera. He also provided a fix for this behavior.
This fix reverts the camera properly on leaving the bahro cave ages.
The Live bahro caves did not force third person camera when falling out of the caves.
Ive added the code required to do that.
All caves should force third person camera when you fall out of them.

Fix Bahro Cave TPP camera

---

Scripts/Python/xAgeSDLBoolActivatorComboSet.py

This will not change the current Python functionality, but will help Max plugin users to be able to set the respButtonPush value correctly with a list of responders.

Change xAgeSDLBoolActivatorComboSet to use more accurate responder list attrib type

---

Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp

Triangulate convex n-gons with standard fan triangulation. Now with less gnashing of teeth, fewer f-bombs, and (probably) more efficiency!
See:
https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/Geometry.html#id2
https://en.wikipedia.org/wiki/Fan_triangulation

Replace algorithm for triangulation from n-gon in IGenerateProxy

---

Sources/Plasma/FeatureLib/pfDXPipeline/plDXPipeline.cpp
Sources/Plasma/PubUtilLib/plPipeline/plDynamicEnvMap.h

It was pointed out in H-uru/moul-assets#209 that the resolution setting in DCMs can be extremely useful for non-reflections. Therefore, use the artist settings for things that aren't reflections.

Limit HQ DynamicCamMaps to reflections.

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIEditBoxMod.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIEditBoxMod.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMenuItem.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMenuItem.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMultiLineEditCtrl.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIPopUpMenu.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIPopUpMenu.h
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlEditBox.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlEditBox.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlEditBoxGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEdit.h
Sources/Plasma/FeatureLib/pfPython/pyGUIControlMultiLineEditGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyJournalBook.cpp
Sources/Plasma/FeatureLib/pfPython/pyJournalBook.h
Sources/Plasma/FeatureLib/pfPython/pyJournalBookGlue.cpp

Migrates `pfJournalBook` to `ST::string`, along with `pfGUIMultiLineEditCtrl` (which it uses) and `pfGUIEditBoxMod` (which isn't directly related, but seemed logical to do along with the multiline version). This is my first time doing anything serious with string_theory, so expect silly mistakes :)
A few places in this code used `wchar_t` arrays as buffers containing a variably-sized string. I replaced those with `ST::wchar_buffer`, as that seems to be the closest equivalent, but unfortunately `ST::wchar_buffer` can't be resized dynamically without destroying its contents. On second thought, it might make more sense to use `std::vector<wchar_t>` instead, to avoid moving data manually and having to track the actual string length.

Improve Unicode support in `pfJournalBook` and related code

---

Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/PubUtilLib/plMessage/plCCRMsg.h

This didn't actually break anything, because apparently all places that use this method also include windows.h (without defining `UNICODE`), so the method was just silently renamed to `GetMessageA`.

Rename `GetMessage` method to avoid conflict with Win32 macro

---

Scripts/CMakeLists.txt

Changes the Python Script project grouping to nest scripts according to the actual file structure.  
This feature requires CMake 3.8, which is well below our current minimum.

Improve script browsing structure in Visual Studio.

---

Sources/Tools/MaxComponent/plAudioComponents.cpp
Sources/Tools/MaxComponent/plCAnimParamBlock.h
Sources/Tools/MaxComponent/plComponentReg.h
Sources/Tools/MaxComponent/plGUIComponents.cpp

See commit message for details.
These are all in the Max plugin code, which I can't test properly. The compiler is happy though and CLion/clangd no longer complains.

Fix non-standard uses of preprocessor paste operator `##`

---

Sources/Plasma/CoreLib/CMakeLists.txt
Sources/Plasma/CoreLib/hsMatrix44.cpp
Sources/Plasma/CoreLib/hsMatrix44.h
Sources/Plasma/CoreLib/hsMatrixMath.h
Sources/Plasma/NucleusLib/pnSceneObject/plCoordinateInterface.cpp
Sources/Plasma/PubUtilLib/plDrawable/plDrawableSpans.cpp

This adds support for Accelerate for matrix multiplication in Plasma. I'm not quite sure how we would want to patch this in, in since it doesn't quite fit the previous model of capability checks.
Accelerate automatically supports:
- SSE3/SSE4/AVX/AVX512 on Intel
- NEON/AMX on Apple Silicon

Initial support for Accelerate for matrix mult

---

Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plUruLauncher/plClientLauncher.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsole.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsole/pfDispatchLog.cpp
Sources/Plasma/FeatureLib/pfConsole/pfDispatchLog.h
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue3.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.h
Sources/Plasma/FeatureLib/pfPython/plPythonConvert.h
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.h
Sources/Plasma/NucleusLib/pnDispatch/plDispatchLogBase.h
Sources/Plasma/PubUtilLib/plAudio/plSound.cpp
Sources/Plasma/PubUtilLib/plAudio/plSound.h
Sources/Plasma/PubUtilLib/plAudio/plWin32GroupedSound.cpp
Sources/Plasma/PubUtilLib/plAudio/plWin32StaticSound.cpp
Sources/Plasma/PubUtilLib/plAudio/plWin32StreamingSound.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvTaskSeek.cpp
Sources/Plasma/PubUtilLib/plPipeline/plStatusLogDrawer.cpp
Sources/Plasma/PubUtilLib/plStatGather/plAutoProfile.cpp
Sources/Plasma/PubUtilLib/plStatusLog/plStatusLog.cpp
Sources/Plasma/PubUtilLib/plStatusLog/plStatusLog.h
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp

This migrates `plStatusLog` and some related code to `ST::string` and makes the following improvements to Unicode support in logging:
* The Python stdout/stderr handler now supports full Unicode, not just the ANSI code page.
* Non-ASCII characters in Python stdout/stderr were badly mis-encoded before. They are now output correctly everywhere that supports Unicode (i. e. except in the in-game console and log drawer).
* When `plStatusLog` calls `OutputDebugString`, it now supports full Unicode and no longer mis-decodes non-ASCII characters.
* `plStatusLogDrawer`'s internal line buffer now supports Unicode (even though the rendering code is still ASCII-only).

Improve Unicode support in Python stdout/stderr handler and `plStatusLog`

---

Sources/Plasma/PubUtilLib/plAudio/plSound.cpp
Sources/Tools/MaxComponent/plAudioComponents.cpp

A lot of warnings like this appear on the console for debug builds:
```
[ALSOFT] (WW) Error generated on context 00000178631E5D10, code 0xa003, "Value out of range"
```
These are caused by out-of-range values for `plSound.fOuterVol` read from some PRPs. Because there are quite a few of these incorrect values (e. g. for many avatar sound effects), the easiest fix is to clamp the value  on read to the expected range.

Fix "Value out of range" warnings from openal-soft

---

Sources/Plasma/FeatureLib/pfCharacter/pfConfirmationMgr.cpp
Sources/Plasma/FeatureLib/pfConsole/pfGameConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUICtrlGenerator.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUICtrlGenerator.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMenuItem.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMenuItem.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIPopUpMenu.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIPopUpMenu.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGameGUIMgr.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGameGUIMgr.h
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue2.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIPopUpMenu.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIPopUpMenu.h
Sources/Plasma/FeatureLib/pfPython/pyGUIPopUpMenuGlue.cpp

This one is also just internal refactoring with (I think) no player-visible Unicode improvements. Some of this is code is probably dead anyway - the `Game.GUI` console commands seem to be unused...
Closes #473, except for a few small bits that I'll do later (together with other modules).

Migrate remainder of pfGameGUIMgr to `ST::string`

---

Sources/Plasma/PubUtilLib/plClipboard/plClipboard.cpp

[`EmptyClipboard`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-emptyclipboard) returns nonzero on success and zero on error.

Fix `EmptyClipboard` result assert

---

Sources/Plasma/CoreLib/hsMatrixMath.h

Went unnoticed because of unity builds again, I assume.

Add missing hsMatrix44.h include

---

vcpkg.json

If we're cross-compiling Plasma to run on a different architecture, we still want to build python-cairosvg for the host architecture because it runs as part of the build process on the host machine rather than at runtime on the target architecture.

Mark python-cairosvg as a host dependency

---

Sources/Plasma/FeatureLib/pfConsole/pfAvatarConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsole/pfGameConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfPython/cyAvatar.cpp
Sources/Plasma/FeatureLib/pfPython/cyAvatar.h
Sources/Plasma/FeatureLib/pfPython/cyAvatarGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyCritterBrain.cpp
Sources/Plasma/FeatureLib/pfPython/pyCritterBrain.h
Sources/Plasma/FeatureLib/pfPython/pyCritterBrainGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyGlueHelpers.h
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.h
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainCritter.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainCritter.h
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainGeneric.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainGeneric.h
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainHuman.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainHuman.h

Again not because of concrete Unicode bugs, just `ST::string`-ifying more Python glue. This removes almost all uses of `std::string` in pfPython.

Migrate avatar brain Python glue to `ST::string`

---

Sources/Plasma/PubUtilLib/plAvatar/plPhysicalControllerCore.cpp

Sometimes, when running into a solid wall, the player will jitter. The most evident side effect when that happens is lots of small transient contacts being reported. Therefore, don't slide against small collisions. As a bonus, don't make a copy of each contact while we're calculating the sliding normal.

Fix player jittering when running into walls.

---

Scripts/Python/nxusBookMachine.py

This seems to only occur when the Nexus SDL is at its default state.

Fix UnboundLocalError in the Nexus Python.

---

Scripts/Python/ki/xKIConstants.py
Scripts/Python/nxusBookMachine.py
Scripts/Python/psnlBookshelf.py
Scripts/Python/xLinkingBookGUIPopup.py
Scripts/Python/xRegisterAge.py

Assets - https://github.com/H-uru/moul-assets/pull/220
These changes add a hardcode link to the Relto Bookshelf for linking to the Chiso Preniv Age.
Changes the Chiso Preniv Age so its no longer inviteable in the KI or visible in the Nexus under Personal and Invited links.
Adds a script to click an object and add it to the Owned age links.
This is used to add Chiso Preniv Book to the owned ages. This will be added by @DoobesURU in a seperate PR.

Add Chiso Preniv Book to Relto bookshelf

---

Scripts/Python/xOptionsMenu.py

This was caused by #1319 (0b6c04be83c8764a217f8f1d0d138cebab06326a). With that change, the option value was written as True/False rather than 1/0, but the reading code only recognized the integer 1 as true, so True/False were interpreted as false.
The value is now written as true/false, matching the default value and the other boolean options. The reading code now accepts all three variants.

Fix "Display Shadows" getting unchecked every time settings are opened

---

Sources/Plasma/PubUtilLib/plPipeline/plDebugText.h
Sources/Plasma/PubUtilLib/plPipeline/plStatusLogDrawer.cpp

Fixes #1355.
I checked and couldn't find any other calls broken in the same way.
Perhaps we should remove the `_TEMP` suffix and make it an overload like all the others. That would avoid this issue - but might also cause *more* silent breakage if we're unlucky...

Fix broken colors in `plStatusLogDrawer`

---

Scripts/Python/grsnMainWallPython.py
Scripts/Python/grsnWallEventHandler.py
Scripts/Python/grsnWallImagerDisplayN.py
Scripts/Python/grsnWallImagerDisplayS.py
Scripts/Python/grsnWallPython.py

**grsnMainWallPython.py**
1. Blocker announcements will now only happen during a game.
You could before stay in the game area after it ended and wait for someone to sit at the North panel, and then it would allow announcements again.
**grsnWallImagerDisplay(N|S).py**
1. fix a code crash
**grsnWallPython.py**
Lot of code movement on this change. 
1. Added a check in the OnNotify section to only trigger code for the player that initiated the action @ line 466.
This change made it so I could move only the things that needed to be multiplayer above it that and cause less code to run for players that don't need it.
2. Reduced the for loops for the events. It will now only run through the events loop once for everything that needs that loop.
3. Was able to make it so setting the SDL was not …

Wall game code adjustments

---

Sources/Plasma/FeatureLib/pfConsole/pfConsole.h
Sources/Plasma/NucleusLib/pnAsyncCore/Private/pnAcLog.cpp

These functions/methods are declared, defined, and used only within Plasma itself, so it doesn't matter which calling convention they use.
The only uses of `CDECL` where it actually matters are in hsSystemInfo.cpp, for the Wine version functions. (Even those *could* be safely removed I think... [the MSVC docs](https://learn.microsoft.com/en-us/cpp/build/reference/gd-gr-gv-gz-calling-convention?view=msvc-170) say that `__cdecl` is the default calling convention for C and C++.)

Remove `CDECL` modifiers where not needed

---

Scripts/Python/xOptionsMenu.py

PRP and other required files - https://github.com/H-uru/moul-assets/pull/206
Adds code for two new buttons in Trailer GUI
First video in AVI directory is now first video played
Ignores any videos smaller than 1000 bytes
Videos will loop if you keep clicking buttons
GUI will exit when video is over (retains previous behaviour)

Add Video Selector buttons for Video Options Menu GUI

---

Sources/Plasma/PubUtilLib/plAvatar/plAvBrainSwim.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainSwim.h
Sources/Plasma/PubUtilLib/plPhysical/plCollisionDetector.cpp

The `plObjectInVolumeAndFacingDetector` is used to, for example, trigger ladder mounts and dismounts when walking forward. It makes sense that we might want to do similar animations when swimming forward (eg climbing up out of a body of water using a special animation). Unfortunately, swimming is a special brain type with a forward movement behavior that isn't working. So, update the logic to allow swimming forward to trigger the walking forward condition.
To better understand what this fixes, a video of the new behavior can be found here: https://youtu.be/dGraK0O7584. Without this fix, setting `fNeedWalkingForward = true` would prevent the climb out animation from executing at all. This would have to be disabled, causing the animation to fire any time the avatar was in the regions sensor …

Allow swimming forward to satisfy walking forward condition.

---

Sources/Plasma/PubUtilLib/plParticleSystem/plParticleGenerator.h

> warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648
This was showing up several times in my build logs and it's easy enough to make the cast explicit to silence the warning

Resolve clang implicit conversion warning

---

Sources/Plasma/FeatureLib/pfConsole/pfConsole.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIEditBoxMod.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGameGUIMgr.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue3.cpp
Sources/Plasma/FeatureLib/pfPython/pyDrawControl.cpp
Sources/Plasma/FeatureLib/pfPython/pyKeyMap.cpp
Sources/Plasma/FeatureLib/pfPython/pyKeyMap.h
Sources/Plasma/FeatureLib/pfPython/pyKeyMapGlue.cpp
Sources/Plasma/NucleusLib/pnInputCore/plControlDefinition.h
Sources/Plasma/NucleusLib/pnInputCore/plInputMap.cpp
Sources/Plasma/NucleusLib/pnInputCore/plInputMap.h
Sources/Plasma/NucleusLib/pnInputCore/plKeyMap.h
Sources/Plasma/PubUtilLib/plInputCore/plAvatarInputInterface.cpp
Sources/Plasma/PubUtilLib/plInputCore/plAvatarInputInterface.h
Sources/Plasma/PubUtilLib/plInputCore/plInputDevice.cpp
Sources/Plasma/PubUtilLib/plInputCore/plInputDevice.h
Sources/Plasma/PubUtilLib/plInputCore/plInputInterfaceMgr.cpp
Sources/Plasma/PubUtilLib/plInputCore/plInputInterfaceMgr.h
Sources/Plasma/PubUtilLib/plMessage/plInputEventMsg.cpp
Sources/Plasma/PubUtilLib/plMessage/plInputEventMsg.h

Migrates pnInputCore and plInputCore to `ST::string`, fixing some weird issues with non-ASCII characters in the code that translates `plKeyCombo`s from/to strings. As a result, you can now successfully change all key bindings in French without any hangs or silent errors.
This does *not* address some of the other internationalization issues in the input system, such as localized strings being passed around internally and stored in the vault. It only fixes Unicode support in the strings.
I also did other small modernization/refactoring where I think it's safe, and re-enabled some commented out Spanish/Italian translations. See commits for details (the single commit diffs may also be easier to read too).

InputCore Unicode improvements (and slight cleanup)

---

Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp

These don't really do anything, but Python expects `stdout`/`stderr` to have `flush` methods. This fixes the "Hmm... Errors during Python shutdown." message on every exit.

Add `flush` methods to Python `stdout`/`stderr` redirectors

---

Sources/Plasma/NucleusLib/pnNetCli/Pch.h
Sources/Plasma/NucleusLib/pnNetProtocol/Pch.h
Sources/Plasma/NucleusLib/pnUtils/Pch.h
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Pch.h
Sources/Plasma/PubUtilLib/plVault/Pch.h

`malloc.h` is a non-standard, platform-specific header that exposes implementation details of the C library's memory allocator, but Plasma doesn't need any of that. The `malloc` function itself is provided by `<cstdlib>`, which is already included by `HeadSpin.h`.

Remove unneeded `malloc.h` includes

---

Scripts/Python/plasma/Plasma.py
Sources/Plasma/Apps/plClient/win32/winmain.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUITextBoxMod.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue3.cpp
Sources/Plasma/PubUtilLib/plGImage/plDynamicTextMap.cpp
Sources/Plasma/PubUtilLib/plResMgr/plLocalization.cpp
Sources/Plasma/PubUtilLib/plResMgr/plLocalization.h
Sources/Tools/MaxComponent/plGUIComponents.cpp
Sources/Tools/plLocalizationEditor/plAddDlgs.cpp

And remove some unused and/or obsolete methods.
The changes touch a few parts of the Max plugin, which I cannot test properly, as usual.
This class could use some further cleanup too:
* The language numbers are typed weirdly - they're often cast back and forth between `plLocalization::Language` and plain `int`, sometimes offset by 1 for mysterious reasons.
* `kNumLanguages` is one higher than `GetNumLocales()`, presumably so that `kJapanese` (the last language in the enum) isn't shown to players.
* The `LocalToString`/`StringToLocal` mechanism seems to be obsolete - everything now uses pfLocalizationDataMgr instead of storing translations in the PRPs. `pfGUITextBoxMod` is the only place still using this old mechanism, but even there it's effectively dead. PRPs still have `$`-separated …

Migrate plLocalization to `ST::string`

---

Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceSocket.cpp

This tripped a debug assertion - calling `front()` on an empty list is undefined behavior according to the standard.

Fix out-of-bounds list access in `SocketQueueAsyncWrite`

---

Scripts/Python/Ahnonay.py

```
(03/18 13:38:35) VeryVerySpecialPythonFileMod - Traceback (most recent call last):
(03/18 13:38:35)   File ".\python\Ahnonay.py", line 127, in OnServerInitComplete
(03/18 13:38:35)     elif chron and chron.getName() == "AhnonayOwner" and personalCathedralGuid and personalCathedralGuid == localCathedralGuid:
(03/18 13:38:35) UnboundLocalError: local variable 'localCathedralGuid' referenced before assignment
```
Broken in #1142.

Fix potential `UnboundLocalError` in Ahnonay.

---

Scripts/Python/psnlYeeshaPageChanges.py

Adds back the cluster group disabling from URU CC
This is not currently used on the Huru branches, but Blue Flowers Page requires this code to work.
Otherwise the flowers will stay enabled all the time while using the Huru client on any shard that has that page included with it.

Adds being able to disable cluster groups in Relto age

---

Scripts/Python/xDynTextLoc.py

For H-uru/Korman#372
Before:
After:

Allow setting the `blockRGB` argument in xDynTextLoc.py.

---

Sources/Plasma/FeatureLib/pfMessage/pfGameGUIMsg.h
Sources/Plasma/NucleusLib/inc/CMakeLists.txt
Sources/Plasma/NucleusLib/inc/hsResMgr.h
Sources/Plasma/NucleusLib/inc/plClassIndexMacros.h
Sources/Plasma/NucleusLib/pnFactory/plCreator.h
Sources/Plasma/NucleusLib/pnModifier/CMakeLists.txt
Sources/Plasma/NucleusLib/pnModifier/plLogicModBase.cpp
Sources/Plasma/NucleusLib/pnModifier/plLogicModBase.h
Sources/Plasma/PubUtilLib/plModifier/plLogicModifier.cpp
Sources/Plasma/PubUtilLib/plModifier/plLogicModifier.h

This fixes a longstanding cross-project linking issue from plLogicModBase (by extracting that particular bit of behaviour into plLogicModifier).

Some NucleusLib Cleanups

---

Sources/Plasma/PubUtilLib/plModifier/plLogicModifier.cpp

This was only noticeable when disabling unity builds.

Fix missing hsTimer.h include

---

Sources/Plasma/NucleusLib/inc/CMakeLists.txt
Sources/Plasma/NucleusLib/inc/hsGMatState.h
Sources/Plasma/NucleusLib/inc/hsGMatStateEnums.h

For shader-based pipelines with Metal and OpenGL, we need to make use of these hsGMatState flag values in the shader code, but the shaders can't include the existing hsGMatState.h file with C++ class definitions.
This extracts just the enum values into their own header that can be imported by shaders, with one major caveat: Rather than plain enum declarations, the enums are generated from macro statements.
You must define `GMAT_STATE_ENUM_START`, `GMAT_STATE_ENUM_VALUE`, and `GMAT_STATE_ENUM_END` before importing this header.
This is because OpenGL shaders don't support enums except as an extension, so it would be better for these to be defined as constants in the shader in that situation.
/cc @colincornaby because I know you had to do some hacking of hsGMatState.h to include it in your …

Expose just the hsGMatState enums as a header

---

Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp
Sources/Plasma/PubUtilLib/plGImage/plDynamicTextMap.cpp
Sources/Plasma/PubUtilLib/plGImage/plFont.cpp
Sources/Plasma/PubUtilLib/plGImage/plFont.h
Sources/Tools/plFontConverter/plFontPreview.cpp

For the `ST::string` overloads of the text rendering methods, the `firstClippedChar` output parameter still counted in `wchar_t` units, not UTF-8 bytes as needed for indexing into `ST::string`.

Fix journals not rendering Unicode text correctly (fixes #1403)

---

Scripts/Python/ki/__init__.py

Partially addresses #1243 by only allowing the looking-at-KI animation to play while we're a *human* brain, meaning that the avatar is directly under the player's control for walking purposes. The swimming brain has some very interesting problems where it can receive erroneous buoyant forces or fall with gravity when tasks are executed from the water. These are complicated enough that I felt it would be better to submit this incremental fix than spend a lot of time chasing all of that down. This means that linking out from the water will still cause weird behavior.

Don't play the look at KI animation while swimming.

---

Sources/Plasma/PubUtilLib/plMessage/plDisplayScaleChangedMsg.h

This is more consistent with how we do compile-time checking in the rest of the codebase, and avoid issues on compilers producing Windows binaries that somehow don't define `WIN32` by default (aka mingw-w64)

Fix Win32 ifdef check in DisplayScaleChangedMsg

---

Sources/Plasma/FeatureLib/pfMoviePlayer/plMoviePlayer.cpp

`fLastImg` is only declared in the header if `USE_WEBM` is true, and we can't call `vpx_img_free` if `USE_WEBM` is not true

Fix pfMoviePlayer when libwebm is not available

---

Sources/Plasma/PubUtilLib/plPipeline/CMakeLists.txt

plTextFont uses CoreText on macOS but didn't explicitly declare a dependency.  In the full macOS client, I think this was being masked by something else that brought in CoreText.

plPipeline needs to link against CoreText

---

Sources/Plasma/CoreLib/hsStream.cpp

Happy 20th birthday to this code that was only meant to exist for a week or so! I think it's safe to remove by now. This "old" format is never produced by `WriteSafeString` and doesn't seem to be used in any data files.

Drop SafeString "backward compat hack" from 20 years ago

---

Sources/Plasma/PubUtilLib/plResMgr/plRegistryKeyList.cpp
Sources/Plasma/PubUtilLib/plResMgr/plRegistryNode.cpp
Sources/Plasma/PubUtilLib/plResMgr/plResManager.cpp

While doing some multiplayer testing, I encountered a crash on exit that looks very similar to the "`plWin32LinkSound`/`plWin32StaticSound` crash" that's been reported with OpenUru clients for a while now. I can reproduce this reliably with two internal debug H'uru clients running on the same machine, simply by linking two avvies to the Ferry Terminal and then closing the two clients. (I first close the client that linked in first, then wait a couple of seconds, then close the second client, which then crashes. Haven't tested if the order or timing is important.)
<details>
<summary>Stack trace from debugger</summary>
```
[plClient.exe] std::_Iterator_base12::_Adopt_unlocked(const std::_Container_base12 *) xmemory:1145
[plClient.exe] std::_Iterator_base12::_Adopt_locked(const …
```

Fix possible use after free in `plRegistryPageNode::UnloadKeys`

---

Scripts/Ports/python3-cairosvg/portfile.cmake
Scripts/Ports/python3-cairosvg/vcpkg.json

Update to latest cairosvg too, since that seems to work fine.
On July 1st, a new major version of Pillow was released, and it requires zlib to compile. For whatever reason, that's not working when pip tries to install it. However cairosvg is fine using the older version so it's easiest to rollback for the moment to fix the builds.

Specify older Pillow version to fix cairosvg build

---

Sources/Plasma/FeatureLib/pfMoviePlayer/plMoviePlayer.cpp
cmake/Findlibwebm.cmake

This partially allows us to upgrade to libwebm 1.0.0.30, modulo other issues with libwebm's cmake install configuration.
Note that compatibility with libwebm 1.0.0.28 (as present in vcpkg) is kept, but I have not tested any _older_ versions of libwebm with this change.

Fix include path compatibility with newer versions of libwebm

---

Sources/Tools/plFontConverter/plFontConverter.cpp
Sources/Tools/plFontConverter/plFontFreeType.cpp
Sources/Tools/plFontConverter/plFontFreeType.h
Sources/Tools/plFontConverter/res/FreeType.ui
Sources/Tools/plFontConverter/res/FreeTypeBatch.ui

Previously, plFontConverter by default converted the first 255 glyphs that it could find. The user could increase or decrease that limit but not have any other control. This PR removes the character counter specification and instead hardwires certain unicode character sets of interest to be converted, namely Latin and Cyrillic (see H-uru/moul-assets#237). Additional character sets are trivial to add by modifying plFontTrueType.cpp. Useful future work might be allowing .p2f files to be compressed, but that currently seems like overkill.
As a bonus, this improves the conversion of monochrome fonts by pulling in @colincornaby's fixes for crunchy freetype monochrome fonts. Further, some `ST::string` goodness is added.

Convert more character sets with plFontConverter.

---

Sources/Plasma/PubUtilLib/plParticleSystem/plParticleApplicator.cpp
Sources/Plasma/PubUtilLib/plParticleSystem/plParticleApplicator.h
Sources/Plasma/PubUtilLib/plParticleSystem/plParticleCreatable.h

Neither plParticleGravityApplicator nor plParticleDragApplicator have class indexes that exist in the list of class indexes, and they are not registered as creatables. Most linkers seem to handle this fine by just removing the classes entirely since they are unused, but I've seen errors about the missing class indexes on a few systems.
Since they are unused and have no working implementation, let's just remove them to avoid any potential linking issues.

Remove particle applicators that cause linker errors

---

Sources/Tools/MaxComponent/plAutoUIBase.cpp

The change introduced by 107af8272 breaks the plugin as far back as Max 7.  This applies the fix only to versions that were confirmed as requiring it.

Fix Python Parameter display on pre-2022 Max Plugins.

---

Sources/Plasma/PubUtilLib/plCompression/plZlibStream.cpp
Sources/Plasma/PubUtilLib/plCompression/plZlibStream.h

For some reason, the code in `IValidateGzHeader` was copied from zlib, when they could have just used it through the API... (Perhaps this is *really* old code from before the main zlib API had gzip support?)

Let zlib handle the gzip header instead of parsing it manually

---

Scripts/Python/ki/xMarkerBrainCGZM.py
Scripts/Python/ki/xMarkerBrainQuest.py
Scripts/Python/xMarkerGameUtils.py
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/NucleusLib/pnNetBase/pnNbConst.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.h

Fixes a few small errors in #1217 that I encountered during normal testing. (Haven't done any in-depth testing of marker or GameMgr stuff, so there may be other problems lurking still.)
One of the tracebacks was longer than the `LogPythonTraceback` network message formally allows (1023 characters), so I added a workaround for that as well.

Minor fixes for GameMgr-based marker games

---

Sources/Plasma/Apps/plPageInfo/plPageInfo.cpp
Sources/Plasma/Apps/plPageOptimizer/plPageOptimizer.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/NucleusLib/pnKeyedObject/hsKeyedObject.cpp
Sources/Plasma/NucleusLib/pnKeyedObject/plKey.h
Sources/Plasma/NucleusLib/pnKeyedObject/plKeyImp.cpp
Sources/Plasma/NucleusLib/pnKeyedObject/plKeyImp.h
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
Sources/Plasma/PubUtilLib/plResMgr/plRegistryNode.cpp
Sources/Plasma/PubUtilLib/plResMgr/plResManager.cpp
Sources/Tools/MaxConvert/hsMaterialConverter.cpp
Sources/Tools/MaxMain/plPluginResManager.cpp
Sources/Tools/plFontConverter/plFontConverter.cpp
Sources/Tools/plResBrowser/plResBrowser.cpp

`plKey`'s contents are separated into a public interface `plKeyData` and an internal implementation subclass `plKeyImp`. However, the main `plKey` API had an implicit conversion to `plKeyImp`, making it relatively easy to access the implementation details anyway.
This changes that to require an explicit method call, which only becomes available if you include the implementation header. This will make it easier to find all the places that rely on this conversion.
Confusingly, the implicit conversion was used quite often whenever a `plKey` was used as a boolean (to check if its underlying pointer is null). Those uses don't actually need the implementation details and are now handled by a simple `operator bool`.

Avoid exposing `plKey` implementation details

---

Sources/Plasma/CoreLib/HeadSpin.h
Sources/Tools/MaxExport/plExportDlg.cpp
Sources/Tools/MaxMain/plMaxMenu.cpp

I thought there was some reason why the non-standard versions were still used, but apparently not. After re-reading the Microsoft docs ([`snprintf`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l?view=msvc-170), [`swprintf`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l?view=msvc-170)), I'm pretty sure we can safely switch to the standard functions on Windows too.
`snprintf` is supported since VS 2015 and the standard-compliant version of `swprintf` since at least VS 2010, which is definitely enough for our purposes.

Use standard versions of `snprintf`/`swprintf` on Windows

---

Sources/Plasma/CoreLib/hsMatrix44.cpp
Sources/Plasma/CoreLib/hsMatrixMath.h

1. This is a C++ file, and Accelerate is a C library, so we should use `#include` instead of `#import`.
2. Somewhere around Mac OS X 10.10, some parameters to `vDSP_mmul` were changed from `float*` to `const float*`. But earlier versions complain if you try to pass them `const float*` values, so just cast to `float*`.
Tested and successfully compiled on Mac OS X 10.5 PowerPC 😛

Minor tweaks to hsMatrix44 Accelerate.framework support

---

building.html
download.html
involvement.html

* Encourage using VS2022 and the built-in git functionality for a more seamless process that doesn't involve dealing with git bash and submodules
* Keep the list of dependencies up to date
* Link to our new pre-release tag with artifacts for download instead of sending people to mine for zip files in the Actions tab

Update website download and build instructions

---

Sources/Plasma/PubUtilLib/plSDL/plSDLParser.cpp

Note: The `SetInternal()` and `SetAlwaysNew()` methods are still used, but are flagged from `DISPLAYOPTION=hidden` and `DEFAULTOPTION=vault` respectively.

Remove dead code in SDL parser.

---

Sources/Tools/MaxComponent/plAnimCompProc.cpp
Sources/Tools/MaxComponent/plClimbComponent.cpp
Sources/Tools/MaxComponent/plNavigableComponents.cpp
Sources/Tools/MaxComponent/plResponderAnim.cpp
Sources/Tools/MaxComponent/plResponderMtl.cpp
Sources/Tools/MaxComponent/plTypesComponents.cpp
Sources/Tools/MaxMain/plTextureSearch.cpp

And fix them to properly pass in `TCHAR*`. There may still be more Chinese left to uncover, but this is the worst offender.

Audit all `ComboBox_AddString` macro calls.

---

README.md

It's better to maintain these in a single place rather than multiple places where they can get out of date and out of sync (although yes it would be nice for the instructions to be available after cloning the repo).
Also update the list of libraries to keep it accurate.

Update README to point to website instructions

---

Sources/Plasma/PubUtilLib/plSDL/plSDL.h
Sources/Plasma/PubUtilLib/plSDL/plStateDataRecord.cpp
Sources/Plasma/PubUtilLib/plSDL/plStateVariable.cpp

The code that handles the SDL blob read/write options is quite tangled, so it's difficult to see which options do what exactly and where they even have any effect at all.
This PR adds detailed comments for all the options' meanings (for both reading and writing) and explicitly lists all the options understood by each method. Also some minor cleanup to the option passing, but not much - this is 90% a documentation change.

Document SDL read/write options in more detail

---

Sources/Plasma/FeatureLib/pfDXPipeline/plDXPipeline.cpp

- Remove manual input/output temporary buffer initialization because it slows down the loop significantly.
- Position and normal now share a single 32-byte aligned buffer for (future?) AVX skinning.
- Removed SSE 4.1 skinning because the SSE 3 codepath is significantly faster after these changes.
- Fixed a problem in the FPU variant whereby the Y component of the normal was skinned instead the Z component.

A few more skinning improvements.

---

Sources/Plasma/NucleusLib/pnEncryption/plChallengeHash.cpp

The previous broken `StrCopy` used in the older implementation of `CryptHashPassword` would only write the trailing '\0' character if the copied string had a size greater than zero.  This change ONLY affects empty usernames and passwords, which is basically useless for anything other than testing (however, it can get DirtSand into a bad state -- see the PR there for details).

Fix an unlikely corner case of backwards compatibility with older clients

---

Sources/Plasma/FeatureLib/pfPython/plPythonSDLModifier.h
Sources/Plasma/NucleusLib/pnFactory/plCreatable.h
Sources/Plasma/NucleusLib/pnFactory/plCreator.h
Sources/Plasma/NucleusLib/pnFactory/plFactory.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvatarCreatable.h
Sources/Plasma/PubUtilLib/plMessage/plMessageCreatable.h

The initialization went through a couple of getter/setter methods (one of them virtual), but the field can easily be made a constant initialized at compile time with no dynamic lookup.
I'm actually fixing a couple of IDE warnings here: one about virtual calls in constructors (`ClassIndex()`) and one about "unnecessary" semicolons after the plCreator.h `REGISTER_*` macros.

Avoid runtime indirection when initializing `plCreatable` class indices

---

Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/win32/winmain.cpp
Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp
Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.h
Sources/Plasma/PubUtilLib/plAgeLoader/plResPatcher.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.h

The impetus for this change is the SDL on MOULa is now progressing, sometimes faster than we can update it due to limited reviewer manpower and the lack of proper reviews taking place on the OU side. This results in SDL DESC PROBLEM for people using our clients. Further, it is known that the MOULa game server does not inspect SDL blobs before propagating them to other players, so it is fairly trivial to make clients error out on MOULa with cryptic messages by taking specially crafted SDLs on that shard. Therefore, we now prefer to use the server's SDL, even in /LocalData.
This removes the singlular `/SkipPreload` command line argument in favor of two arguments: `/LocalPython` and `/LocalSDL`. `/LocalData` now implies the former but not the latter. The reason for this change is that the …

Prefer to grab the server's SDL descriptors.

---

Sources/Plasma/Apps/plPageInfo/plPageInfo.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsole/pfDispatchLog.cpp
Sources/Plasma/NucleusLib/pnDispatch/plDispatch.cpp
Sources/Plasma/NucleusLib/pnFactory/plCreatable.h
Sources/Plasma/NucleusLib/pnFactory/plCreator.h
Sources/Plasma/NucleusLib/pnFactory/plFactory.cpp
Sources/Plasma/NucleusLib/pnFactory/plFactory.h
Sources/Plasma/NucleusLib/pnKeyedObject/plKeyImp.cpp
Sources/Plasma/NucleusLib/pnSceneObject/plSceneObject.cpp
Sources/Plasma/PubUtilLib/plAnimation/plAGAnimInstance.cpp
Sources/Plasma/PubUtilLib/plAnimation/plAGApplicator.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgr.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgScreener.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetClientRecorder/plNetClientStatsRecorder.cpp
Sources/Plasma/PubUtilLib/plNetClientRecorder/plNetClientStreamRecorder.cpp
Sources/Plasma/PubUtilLib/plNetCommon/plNetCommonHelpers.cpp
Sources/Plasma/PubUtilLib/plNetCommon/plNetMsgScreener.cpp
Sources/Plasma/PubUtilLib/plNetMessage/plNetMessage.cpp
Sources/Plasma/PubUtilLib/plNetMessage/plNetMsgHelpers.cpp
Sources/Plasma/PubUtilLib/plResMgr/plRegistryNode.cpp
Sources/Plasma/PubUtilLib/plResMgr/plResManager.cpp
Sources/Plasma/PubUtilLib/plSDL/plStateVariable.cpp
Sources/Tools/MaxMain/plMaxUtils.cpp
Sources/Tools/plResBrowser/plResBrowser.cpp

Touching the core plCreatable headers, part two.
The private members of `plFactory` were only conditionally defined in plFactory.h, which is an ODR violation and gives warnings with GCC for example (although apparently it has never caused any issues in practice). I'm not sure why it was done that way (perhaps to reduce header pollution very slightly?), but it seems safe to define everything unconditionally.
Regardless, to avoid pulling in `plFactory` in many places where it's not needed, I also adjusted plCreatable.h to not automatically include plFactory.h anymore. This required removing a couple of `plCreatable` methods, but they weren't used anywhere and are trivial to replace.

Fix ODR violation for `plFactory` and avoid including it everywhere

---

Scripts/Python/plasma/PlasmaTypes.py
Sources/Plasma/FeatureLib/pfPython/pyGUIDialog.cpp
Sources/Plasma/FeatureLib/pfPython/pyGUIDialog.h

Fixes:
```
(08/06 18:14:26) cPythScope1 - Traceback (most recent call last):
(08/06 18:14:26)   File ".\python\ercaOvenScope.py", line 419, in OnGUINotify
(08/06 18:14:26)     timerWheel = control.getControlModFromTag(kTimerWheel)
(08/06 18:14:26) KeyError: 'TagID 500 not found in GUIDialog BakingRmGUI'
```
It looks like `pfGUIProgressCtrl` was never added to `WhatControlType()`, so any attempts to grab those kinds of value controls resulted in an error (eg in the Er'cana bakery). This fixes that problem and updates the "enum" in PlasmaTypes.py, which was even further behind than the C++.

Fix regression from #1428.

---

Sources/Plasma/Apps/plCrashHandler/plCrashHandler.rc

This was causing issues cross-compiling on Linux with clang-cl.

Fix file extension case on plCrashHandler icon

---

Sources/Tools/plNetLog/Auth.cpp
Sources/Tools/plNetLog/Auth.h

This fixes compatibility with DirtSand and comaptible servers for the early Auth server connection messages.

Add ServerCaps message support to plNetLog.

---

Scripts/Python/nb01RPSGame.py

Stops the mouse movement keys when sitting at the heek table to prevent misclicking and leaving the game unintentionally.
Keyboard movement still works and allows you to leave the game still.
Closing the KI will also re-enable mouse movement keys.
Mouse movement key is re-enabled after standing back up.

Add popup quit when sitting at heek table

---

Scripts/Python/xOpeningSequence.py

The starting video will fail to play with the default SDL due to "IndexError: tuple index out of range"
Adding this check catches that before we get an error.

Fix starting video failing to play

---

Sources/Plasma/Apps/plClient/win32/winmain.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetCliAgeJoiner.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgr.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgr.h

Previously, when asking for the server's time, the calculation was done by basically offsetting the local system time by some previously calculated delta. This was basically useless because the user can easily change the system time out from under us and cause huge deltas. The attempt to fix things in #173 by using `WM_TIMECHANGE` was a good idea but ultimately incorrect because `hsTimer` is a monotonic timer. At this point, it uses `std::chrono::steady_clock` as its backend, so attempting to use `hsTimer` to recalculate the server/client time offset is useless.
Therefore, this changes us to simply save the last time value that we received from the game server and the monotonic time that we received that update. This is definitely not perfect because we don't consider things like round …

Don't trust the local machine's system time.

---

Sources/Plasma/CoreLib/hsWindows.h
Sources/Plasma/NucleusLib/pnNetCommon/plNetAddress.cpp
Sources/Plasma/NucleusLib/pnNetCommon/plNetAddress.h
Sources/Plasma/NucleusLib/pnNetCommon/pnNetCommon.cpp

pnNetCommon is also the only library that actually links with Winsock, so including the header elsewhere doesn't make much sense.

Include Winsock header only where it's actually used

---

Scripts/Python/xAvatarCustomization.py

Fixes typo causing issue reported in discord where the avatar customization GUI can persist into Relto.
Fixes #1474.

Fix #1474.

---

Sources/Plasma/NucleusLib/pnUtils/pnUtCrypt.cpp

Yes, we know it's deprecated, no we can't realistically do anything about that right now so let's stop cluttering up the build output with warnings.

Silence OpenSSL RC4 deprecation warnings

---

.github/workflows/ci.yml
Scripts/Ports/python3-cairosvg/vcpkg.json
Scripts/Triplets/arm64-macos-plasma.cmake
Scripts/Triplets/universal-macos-plasma.cmake
Scripts/Triplets/x64-macos-plasma.cmake
vcpkg.json

On Apple Silicon, Homebrew has moved the location its installed its libraries. That means if you are installing a version of Cairo from Homebrew, Python/python3-cairosvg cannot find Cairo, and vcpkg will fail to build python3-cairosvg.
Homebrew's version of Python passes an additional rpath to the configuration phase of the Python build to fix this:
https://github.com/carlocab/homebrew-core/blob/d83d8d4665518494ef7fc3e5a64ba937e69cb06c/Formula/python%403.9.rb#L150
This patch to our Python port also introduces the same patch. I'm still pretty new with vcpkg so I possibly haven't defined this correctly from a maintainable vcpkg perspective. But this fix does block Apple Silicon builds out of the box. I've had to do some manual patching each vcpkg update to work around it.

Adding missing rpath to Python on Apple Silicon

---

Sources/Tools/MaxConvert/hsMaterialConverter.cpp

This fixes an incorrect format specifier in use in the wild (crashes). As a bonus, I have also fixed a potential ODR violation in our unity builds. The deleted strings were also present in plLayerConverter but never used in hsMaterialConverter.

Fix hsMaterialConverter format stuff.

---

Sources/Plasma/FeatureLib/pfCrashHandler/plCrashSrv.cpp
Sources/Plasma/FeatureLib/pfCrashHandler/plWindowsStackWalker.cpp

clang-cl was reporting 2 warnings when compiling pfCrashHandler:
```
Plasma/FeatureLib/pfCrashHandler/plCrashSrv.cpp(86,46): warning: argument to
'sizeof' in 'memcpy' call is the same pointer type 'PCONTEXT' (aka '_CONTEXT
*') as the destination; expected 'struct _CONTEXT' or an explicit length
[-Wsizeof-pointer-memaccess]
memcpy(context, ptrs->ContextRecord, sizeof(ptrs->ContextRecord));
~~~~~~~                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
Plasma/FeatureLib/pfCrashHandler/plWindowsStackWalker.cpp(140,5): warning:
explicitly defaulted default constructor is implicitly deleted
[-Wdefaulted-function-deleted]
plStackWalkError() = default;
^
Plasma/Sources/Plasma/FeatureLib/pfCrashHandler/plWindowsStackWalker.cpp(137,26):
note: default constructor of 'plStackWalkError' is …
```

Resolve 2 clang warnings in pfCrashHandler

---

Sources/Plasma/NucleusLib/pnNetCli/pnNcCli.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2File/pnNpCli2File.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGame.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGateKeeper.cpp

There are 3 special cases that are not handled here:
- UUIDs are handled as "data", but those should already be stored in the weird mixed endian mode that Windows uses (we had to fix this for macOS a while back)
- SHA digests are handled as "raw data", and I'm not sure of the endianness on these. I think this might have been fixed in my first batch of PowerPC fixes? This might need further tweaking.
- Plasma Net Messages are "variable pointers" but those should have all their data stored in little endian by the `Read()`/`Write()` methods on the classes, so we should be okay here.

pnNcCli should consistently convert to little endian

---

Sources/Plasma/Apps/plClient/CMakeLists.txt

I'm not sure why this is required or how the fix improves things - but the part of the CMake script that finds pngcrush has been failing on _some_ of my Macs. I'm not sure why - the Mac that I am seeing this on is running the latest version of CMake.
These changes to the script seem to make things work.
If anyone has a CMake perspective on why this is going on or why the fix works - that would be appreciated.

Fixes for finding png crush executable

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/Mac-Cocoa/NSString+StringTheory.h
Sources/Plasma/Apps/plClient/Mac-Cocoa/NSString+StringTheory.mm
Sources/Plasma/Apps/plClient/Mac-Cocoa/PLSLoginWindowController.mm
Sources/Plasma/Apps/plClient/Mac-Cocoa/PLSPatcher.mm
Sources/Plasma/Apps/plClient/Mac-Cocoa/PLSPatcherWindowController.mm
Sources/Plasma/Apps/plClient/Mac-Cocoa/main.mm
Sources/Plasma/CoreLib/CMakeLists.txt
Sources/Plasma/CoreLib/_CoreLibPch.h
Sources/Plasma/CoreLib/hsDarwin.h
Sources/Plasma/CoreLib/hsSystemInfo.cpp
Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore_Apple.cpp
Sources/Plasma/PubUtilLib/plMessageBox/hsMessageBox_Mac.mm
Sources/Tests/CoreTests/CMakeLists.txt
Sources/Tests/CoreTests/test_hsDarwin_CF.cpp
Sources/Tests/CoreTests/test_hsDarwin_NS.mm

The `NSString` category in the macOS plClient folder is useful, but there are several other spots where we're wanting to convert between `CFString`/`NSString` and `ST::string`, so it make sense to have helpers available throughout the engine. These helper functions are written so that they can be used from C++ code without needing to bring in Objective-C.

Add hsDarwin.h with helpers for string conversion

---

Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
Sources/Plasma/PubUtilLib/plModifier/plResponderModifier.cpp

The impetus for this change is that Korman's new `Change Subworld` message node can cause all players in the Age to change to that subworld. The rationale here is that changing subworlds modifies a player's avatarPhysical SDL. So, really, we probably only want to be sending `plSubWorldMsg` to the local player from a Responder. Responders are primarily a zero-code artist logic tool, so they shouldn't have to care about that level of SDL detail. Further, there is precedent for major avatar/player related actions to be rejected from non-local sources. Namely, all camera messages are restricted in the same way in Responders.
As a bonus, I fixed a memory leak that wouldn't be detected by asan and fixed a logic error with the subworld SDL synch.

Fix 3 problems with `plSubWorldMsg`.

---

Sources/Plasma/FeatureLib/pfConsoleCore/CMakeLists.txt
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleCmd.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleCmd.h
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleEngine.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleEngine.h
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleParser.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleParser.h
Sources/Tests/FeatureTests/CMakeLists.txt
Sources/Tests/FeatureTests/pfConsoleCoreTest/CMakeLists.txt
Sources/Tests/FeatureTests/pfConsoleCoreTest/test_pfConsoleCore.cpp
Sources/Tests/FeatureTests/pfConsoleCoreTest/test_pfConsoleParser.cpp
Sources/Tests/FeatureTests/pfConsoleCoreTest/test_pfConsoleTokenizer.cpp

Converts the very "old C-like" console command parsing code into its own class that has a bit more structure and uses modern C++ data types. Also, unit tests!
Aside from cleaning up the code, my motivation here is to allow parsing console commands *without* actually executing them. This would be especially useful for parsing .ini files - thinking of server.ini or cases like in #1244.
Suggestions for improving the parsing API are welcome. It has to be a bit complex unfortunately, to support situations where the input should only be partially parsed (e. g. tab completion), and because of the wacky command name syntax where parsing depends on which commands are defined...

Refactor and add tests for console command parsing

---

Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceThread.cpp
cmake/CompilerChecks.cmake
cmake/check_pthread_timedjoin_np.cpp
cmake/hsConfig.h.cmake

No longer needed as of c70211a327682fbe11c73f8241dcd361ef2e6224 (#1205).

Remove no longer used check for `pthread_timedjoin_np`

---

Sources/Plasma/NucleusLib/pnNetCommon/plNetAddress.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp

This fixes auth server reconnects for servers that send `Auth2Cli_ServerAddr` messages (i. e. Cyan's server and MOSS). Previously, the received IPv4 address was byte-swapped, making the reconnect always fail.

Fix a couple of endianness issues with `plNetAddress`

---

cmake/CompilerChecks.cmake

This resolves a bunch of CMake warnings during the configuration step.

Update to latest googletest version

---

Scripts/Python/ki/xKIConstants.py

Re-order KI Easter Egg commands so that the more specific `/look in pocket` command is checked for match before `/look`
Fixes https://github.com/H-uru/Plasma/issues/1492

Fix /look in pocket command incorrectly triggering /look

---

Scripts/Python/ki/xKIConstants.py

There were some very condensed dictionaries and arrays that made this file hard to read. The `OKDialogDict` dictionary was especially wide and hard to read on my narrower monitors without the lines wrapping. Also removed excess spaces in dictionaries between the key and its following colon.

Format xKIConstants.py for better readability and narrower screens

---

Sources/Plasma/NucleusLib/pnKeyedObject/plKey.h
Sources/Plasma/NucleusLib/pnKeyedObject/plKeyImp.cpp
Sources/Plasma/PubUtilLib/plResMgr/plKeyFinder.cpp

Fixes #1479.
This was broken by #1429 (4ef380f10fef7523761c73bc4cb2aeec68fac6fd). Previously, `plKey`'s ordering operators were provided by the implicit conversion to `plKeyImp*`, meaning that `plKey`s were ordered by their `fKeyData` pointers. When this was replaced by the conversion to `bool`, the ordering operators unintentionally also changed - `plKey`s were now ordered only by their `bool` value, so all non-null `plKey`s were converted to the same value (`true`) and had no ordering relative to each other! This made anything that uses the ordering operators misbehave, such as stdlib containers like `std::set`.
This change adds explicit `plKey` ordering operators that match the previous behavior.
Also includes another change I made during debugging, which makes a few …

Fix ordering operators for `plKey`

---

Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp

This issue was introduced when `hsStream::Close()` was removed in favor of RAII in #1448. Unfortunately, the patcher is handing off files before it deletes the patcher stream, which causes race conditions around zlib decompression not being complete. We need to explicitly close the underlying stream before performing any handoffs to prevent crashes.
Fixes #1506

Fix ahnyQuab ogg decompression crashes.

---

Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/CoreLib/hsBitVector.cpp
Sources/Plasma/NucleusLib/pnKeyedObject/plUoid.h
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.h
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainCoop.cpp
Sources/Plasma/PubUtilLib/plContainer/plConfigInfo.cpp
Sources/Plasma/PubUtilLib/plDrawable/plGeometrySpan.cpp
Sources/Plasma/PubUtilLib/plDrawable/plWaveSet7.cpp
Sources/Plasma/PubUtilLib/plDrawable/plWaveSet7.h
Sources/Plasma/PubUtilLib/plFile/plSecureStream.cpp
Sources/Plasma/PubUtilLib/plGImage/plAVIWriter.cpp
Sources/Plasma/PubUtilLib/plGImage/plFont.cpp
Sources/Plasma/PubUtilLib/plGLight/plShadowMaster.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgScreener.cpp
Sources/Plasma/PubUtilLib/plPipeline/plCullTree.cpp
Sources/Plasma/PubUtilLib/plScene/plPageTreeMgr.cpp
Sources/Plasma/PubUtilLib/plScene/plSceneNode.cpp

Best to review this one commit at a time and I can drop any commits that people deem controversial.
This does not clear up all the issues that cppcheck found, but these were some low-hanging fruit.

Various small fixes identified by cppcheck

---

.github/workflows/ci.yml
Scripts/Ports/python3/vcpkg-cmake-wrapper.cmake
Scripts/Ports/python3/vcpkg.json

This requires using the host platform's Python interpreter rather than the target platform's interpreter, which runs as part of the build process for resource.dat generation.
Also have to disable running tests when cross-compiling because the host system can't run the test executables compiled for the target system.

Enable macOS arm64 builds in CI

---

CMakeLists.txt
Sources/Plasma/CoreLib/CMakeLists.txt
Sources/Plasma/CoreLib/hsWindows.cpp
Sources/Plasma/PubUtilLib/plAudio/plAudioSystem.cpp
Sources/Plasma/PubUtilLib/plUnifiedTime/plUnifiedTime.cpp

This is not a full set of changes to make everything build on 10.5 PowerPC (because everything does not build on 10.5 PowerPC) but this is a hopefully uncontroversial set of small fixes.

Mac OS X 10.5 compiler fixes

---

Sources/Plasma/Apps/plClient/plClientLoader.cpp
Sources/Plasma/Apps/plClient/win32/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/plClientLauncher.cpp
Sources/Plasma/CoreLib/hsThread.cpp
Sources/Plasma/CoreLib/hsThread.h
Sources/Plasma/CoreLib/hsThread_Unix.cpp
Sources/Plasma/CoreLib/hsThread_Win.cpp
Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp
Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceDns.cpp
Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceSocket.cpp
Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceThread.cpp
Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceTimer.cpp
Sources/Plasma/PubUtilLib/plAudioCore/plSoundBuffer.cpp
Sources/Tools/MaxComponent/plPickMaterialMap.cpp

This is helpful when debugging, especially with all of the IO worker threads created by the asio-based socket code.
The APIs for setting thread names are really platform-specific, so this adds a wrapper function that supports Windows, Linux, and Apple platforms. (Only the Windows version has been tested so far.)

Set custom names for all of our threads

---

Scripts/Python/xSimpleImager.py
Scripts/SDL/Neighborhood.sdl

Assets - https://github.com/H-uru/moul-assets/pull/241
Sets up the an SDL variable so you can set individual permissions for upload/pellet drops to everyone/member only/off
Requested by Cyan Shard operator to prevent pellet uploads in individual hoods
Adds new SDL variable to Neighborhood.sdl
nb01PelletUploadState
0 <= Everyone can upload (Default)
1 = Members only upload
2 >= No one can upload

Adds SDL based upload check for imagers

---

.github/PRERELEASE_NOTES.md
.github/workflows/ci.yml
.github/workflows/publish-artifacts.yml
.github/workflows/scripts_review.yml

Unfortunately this still does not handle deleting and re-creating releases properly, so we're likely to move to a system with a static tag on a placeholder commit, and just update the release description and attachments every time.
As part of that, this will now embed the commit SHA in the release notes for easier tracking.
Also adds mention of the macOS arm64 clients and the 3DS Max 2023 & 2024 builds.

Improve the prerelease workflow a bit

---

Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.h
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.cpp

Metal wasn't honoring that dynamic buffers should be volatile like the DX pipeline was. On modern systems - this should be pretty low impact. But it's still nice to implement.
Plasma refreshes its buffers every frame which can make volatile buffers a little niche. However - Metal Plasma triple buffers which means this could allow a buffer not currently being presented to be freed.

Volatile dynamic buffers in Metal

---

Scripts/Python/xGUILinkHandler.py

This fixes #1538 by allowing an optional / character at the end of a URL.

Fix #1538.

---

cmake/QtDeployment.cmake

Trying to deploy Qt when no Qt tools have been built causes the install process to fail with a cryptic error. This error has persisted for quite some time, likely due to being silently masked by older Qt tools being present in build directories.

Don't deploy Qt if no Qt tools are built.

---

Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.h

The argument is now always treated as a plain string and passed directly to the cheat. This is the behavior expected by all the functions in xCheat.py, which parse the string argument manually where needed.
The previous implementation evaluated the argument value as a Python expression. This theoretically allowed passing non-string arguments, but none of the cheats use this (and it's also a potential code execution issue). If no argument was passed, the function was called with no arguments, which is also not supported by any of the cheats.
In practice, this required unintuitive syntax for calling the cheats correctly, for example:
```
Python.Cheat GetPlayerID None
Python.Cheat GetSDL "'FirstWeekClothing'"
```
With the new argument handling, these have been simplified to:
```
Python.Cheat …
```

Make `Python.Cheat` command more usable by not parsing its argument

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
cmake/PlasmaTargets.cmake

Yes, this somehow manages to be worse than the XIB files because actool generates a partial plist output file that needs to be merged with the application plist in order to provide the correct icon.

Handle xcasset files when building outside of Xcode

---

Sources/Plasma/FeatureLib/pfMetalPipeline/ShaderSrc/PlateShaders.metal

Metal pipeline only uses 16 bit precision for color. Not sure how this escaped cleanup.

Simplifying plate Metal shader

---

Sources/Plasma/NucleusLib/pnAsyncCore/Private/pnAcIo.h
Sources/Plasma/NucleusLib/pnAsyncCore/Private/pnAcTimer.h
Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceDns.cpp
Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceSocket.cpp
Sources/Plasma/NucleusLib/pnAsyncCoreExe/pnAceTimer.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNcCli.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNetCli.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGame.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGateKeeper.cpp

Trying to improve the "callback hell" in the low-/middle-level network code. The AsyncCore APIs relied heavily on C-style callback functions with untyped `void*` context parameters, which made it difficult to follow the execution and data flow in NetGameLib.
This PR migrates almost all of the async callbacks to use `std::function` (where they didn't already) and the callers to use lambdas for capturing context variables. This obsoletes the `void*` parameters and removes lots of manual casts.
AsyncSocket is a special case: its callback function was really multiple distinct callbacks wrapped in a generic signature, so I replaced it with a "callbacks object" with multiple virtual methods that the caller has to implement. This is a very "Java-ish" solution and is incompatible with lambdas, …

Modernize NucleusLib async callbacks using lambdas

---

Sources/Plasma/FeatureLib/pfDXPipeline/plDXEnumerate.cpp
Sources/Plasma/FeatureLib/pfDXPipeline/plDXEnumerate.h
Sources/Plasma/FeatureLib/pfDXPipeline/plDXPipeline.cpp
Sources/Plasma/FeatureLib/pfDXPipeline/plDXPipeline.h
Sources/Plasma/PubUtilLib/plPipeline/hsG3DDeviceSelector.cpp
Sources/Plasma/PubUtilLib/plPipeline/hsG3DDeviceSelector.h

D3D enumerates adapters. In kernel driver parlance - an adapter is a device that represents a video output on a card. Typically an enumeration API (like the one in D3D) will only enumerate adapters on a video card that have a display connected.
Basically:
- An adapter has one display.
- A GPU may have more than one adapter.
- An adapter may have more than one compatible renderer. There might be a software renderer. Or the GPU that hosts the adapter may have one or more renderers.
I think the original source code has muddled things by assuming that an adapter is a driver or a video card. This has led to weird descriptions in the code like a video card having display modes instead of a monitor having display modes.
Comments like this one are suspicious:
``` …
```

Reconciling D3D Adapter Enumeration

---

Sources/Plasma/FeatureLib/pfGameScoreMgr/pfGameScoreMgr.h
Sources/Plasma/NucleusLib/inc/plTimerCallbackManager.h
Sources/Plasma/NucleusLib/pnKeyedObject/plKey.h
Sources/Plasma/NucleusLib/pnKeyedObject/plKeyImp.cpp
Sources/Plasma/NucleusLib/pnMessage/plMessage.h
Sources/Plasma/NucleusLib/pnMessage/plNotifyMsg.h
Sources/Plasma/NucleusLib/pnTimer/plTimerCallbackManager.cpp
Sources/Plasma/PubUtilLib/plMessage/plInputEventMsg.h

The debugging message in the destructor was unconditionally disabled and no longer compiles if manually enabled. The debugging check in `plKeyImp::SetObjectPtr` can be rewritten to not require any extra fields (also making it a bit faster by removing the string comparison).
This uncovered missing includes in multiple places due to plKey.h not including `<string_theory/string>` anymore.

Remove old debug-only fields from `plKeyData`

---

Sources/Plasma/FeatureLib/pfMetalPipeline/CMakeLists.txt
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalEnumerate.cpp

There's a C++ wrapper for NSProcessInfo in metal-cpp, and that's available to us since we're in pfMetalPipeline, and this allows us to avoid Objective-C in shared library code.
Since it returns a struct with just integers, we can also use ST::format to combine them into a string instead of needing to create and release an NSString.

Use metal-cpp's NS::ProcessInfo to get version

---

vcpkg.json

This includes OpenSSL 3.2.0, so we can stop pinning an old 3.0.x version (because 3.1.x had bugs on macOS AArch64 that are solved in 3.2.0).
* **curl**
`8.4.0` -> `8.5.0`
* **freetype**
`2.12.1#4` -> `2.12.1#5`
* **libpng**
`1.6.39#1` -> `1.6.40#1`
* **libvpx**
`1.13.1` -> `1.13.1#2`
* **openssl**
`3.0.8#2` -> `3.2.0#2`
* **string-theory**
`3.6` -> `3.8`

Update to vcpkg tag 2024.01.12

---

Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.cpp

This will make the max AA setting functionally unavailable as 8x will be out of range. However - this will be more consistant with Windows where the max AA setting is typically interperated as 4x or 6x.

Matching MSAA behavior from D3D

---

Sources/Plasma/NucleusLib/pnNetCli/Intern.h
Sources/Plasma/NucleusLib/pnNetCli/pnNcChannel.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNcCli.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNcEncrypt.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNetCli.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/pnNpCommon.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGame.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGateKeeper.cpp

This drops various bits of code under pnNetCli that are unused and very unlikely to ever be useful, namely:
* The last remaining server-side network code. I assume that we'll never see the plServer sources that would need this code.
* Unused network message field types that are difficult/impossible to use correctly. With the base network protocols being almost frozen, I assume there will never be any use for these extra types.
As usual, the commit messages for the non-obvious changes have more detailed reasoning.

Remove dead/server-only network protocol code

---

Sources/Plasma/PubUtilLib/plAvatar/plAvTaskBrain.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvTaskBrain.h
Sources/Plasma/PubUtilLib/plAvatar/plCoopCoordinator.h
Sources/Plasma/PubUtilLib/plMessage/plLoadAvatarMsg.h
Sources/Plasma/PubUtilLib/plMessage/plLoadCloneMsg.cpp
Sources/Plasma/PubUtilLib/plMessage/plLoadCloneMsg.h
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgScreener.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgScreener.h

Like H-uru/dirtsand#191, but on the client side. This expands `plNetClientMsgScreener` to also screen messages nested inside other messages, as can happen for avatar messages.
Also disallows receiving any kind of `plInputEventMsg` over the network - particularly `plControlEventMsg`, which can execute console commands, like the already blocked `plConsoleMsg`. This should have no effect on normal gameplay, but will probably break bot effects that modify other clients' fog settings (I haven't tested this though). If this is a problem, we could selectively allow "known safe" console commands instead of blocking everything.

Screen more kinds of unwanted network messages

---

.github/workflows/ci.yml

https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

Use 4 concurrent jobs in CI.

---

Scripts/Python/xEntryCam.py

This adds support for entry camera spawn points from Korman. The idea is that, when spawning in, a specific camera will be pushed inside of a specific region. This camera will only ever be pushed when spawning in. Therefore, we need to disable all entry camera regions after linking in.
See H-uru/korman#395

Add xEntryCam.py

---

Sources/Plasma/CoreLib/hsRefCnt.h

This restores the vftable of `hsRefCount` to match its layout in TPotS and the original MOUL. Having these methods be virtual is extremely helpful in the case of ModDLLs that define external creatables. If you're making an external creatable, it's important that those creatables are allocated and deallocated by the ModDLL itself. If `UnRef()` is not virtual, then your external creatable may be deleted by the engine, which may not be built against the same C++ runtime library as the engine. If the two C++ runtime libraries are not ABI compatible, this can result in sinister crashes. This is most relevant for very, very old builds of the engine, such as TPotS (Visual C++ 6) where it would be nice to build a ModDLL with a newer compiler.
(Yes, this does mean that I have made a ModDLL with an …

Restore vftable of `hsRefCount`.

---

.github/workflows/ci.yml

Build times seem to be cut in half using the M1 runners, and this allows us to properly install and build with Qt on arm64 builds.
Worth noting, I also tried running the x86_64 builds on M1 and it failed to compile Python. That might be something we need to look at in the future. For now, I've kept x86_64 running on Intel macOS 12.

Use M1 macOS runners for arm64 builds

---

Sources/Plasma/Apps/plCrashHandler/CMakeLists.txt
Sources/Plasma/Apps/plCrashHandler/plCrashHandler.rc
Sources/Plasma/Apps/plCrashHandler/winmain.cpp

No more fuzzy crash dialog! This also fixes a minor visual issue whereby the Uru Live banner was slightly smaller than the rest of the dialog, even on 100% scaling.

Allow DPI awareness in plCrashHandler.

---

cmake/PlasmaTargets.cmake

Per @dpogue, the problem is https://gitlab.kitware.com/cmake/cmake/-/issues/25650. Long story short, CMake broke PCH and Unity on CMake 3.28.2, so disable that combination when it's used.

Fix Linux CI.

---

Sources/Plasma/FeatureLib/pfMetalPipeline/CMakeLists.txt

This causes it to use the timestamp of the downloaded zip file rather than the timestamps from within the zip file, to ensure that a newer download is always compiled regardless of whether existing extracted files have newer timestamps.

Fix warnings on newer CMake about FetchContent

---

Sources/Tools/MaxComponent/plResponderComponent.cpp

Fixes #1508.
As it turns out, the responder state combo box has the owner draw style applied. So, `ifdef`ing the draw method out causes the box to be blank. Who would have thought it? While I was here, I cleaned up the colors to not look out of place on Max 2022.

Fix #1508.

---

Sources/Tools/MaxComponent/plResponderAnim.cpp

Fixes the Animation FFwd command missing from the list of potetial responder commands in the Max plugin. How long has this been broken?????????

Fix missing Anim FFwd Responder Cmd.

---

Scripts/Python/plasma/Plasma.py
Scripts/Python/xIniDisplay.py
Scripts/Python/xOptionsMenu.py
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue4.cpp

This is the companion piece to H-uru/moul-assets#251. There is no longer any need to manually localize the options menu :tada:. I didn't bother with improving the quality of tangential Python code. All of the options menu Python is terrible, and I didn't want to get bogged down with that.

Add support for new DynamicCamMap checkbox.

---

Sources/Tools/plLocalizationEditor/plEditDlg.cpp
Sources/Tools/plLocalizationEditor/plLocalizationEditor.cpp

QoL improvement for plLocalizationEditor. It now remembers your last selection for the data directory and puts that path into the open file dialog by default.

[plLocalizationEditor] Remember the data dir across sessions.

---

.github/workflows/ci.yml
vcpkg.json

This is effectively the same fix they're [making upstream](https://github.com/microsoft/vcpkg/pull/37841), but relying on vcpkg.json to pin the version instead of waiting for their baseline change to make it into a release.
You can confirm that it is using the older liblzma version by looking at the log output of the Configure step and checking for output similar to the following at the top of the log:
```
The following packages will be built and installed:
[...]
* liblzma:arm64-macos-plasma@5.4.4 -- /Users/runner/work/Plasma/Plasma/vcpkg/[...]
[...]
```
Also had to change how python setuptools are installed on macOS because new GitHub Actions runner images weren't happy with using `sudo pip` 🙄

Downgrade liblzma in vcpkg

---

Scripts/Ports/python3/0001-only-build-required-projects.patch
Scripts/Ports/python3/portfile.cmake
Scripts/Ports/python3/python_vcpkg.props.in
Scripts/Ports/python3/vcpkg.json
vcpkg.json

It was only used for an optional Python module, which is not needed for Plasma. Since we already manage our own modified Python vcpkg port, we can just disable that optional module.

Drop the liblzma dependency entirely

---

.github/workflows/ci.yml

`macos-latest` now points to macos-14 on arm64, and vcpkg doesn't want to build Python for x86_64 when the host is arm64 🙄

Fix macOS x86_64 CI builds

---

Sources/Plasma/PubUtilLib/plWinDpi/plWinDpi.cpp

In Windows 7 and Windows 8 the intro is very small and no mouse cursor is visible.
This fixes the problem.

fix Win7/8 resolution

---

.github/workflows/ci.yml
Sources/Plasma/CoreLib/hsStream.cpp
Sources/Plasma/NucleusLib/pnUUID/pnUUID_Unix.cpp
Sources/Plasma/PubUtilLib/plAudioCore/plBufferedFileReader.cpp
Sources/Plasma/PubUtilLib/plPipeline/plTransitionMgr.cpp
Sources/Tests/NucleusTests/CMakeLists.txt
Sources/Tests/NucleusTests/pnUUIDTest/CMakeLists.txt
Sources/Tests/NucleusTests/pnUUIDTest/test_plUUID.cpp
cmake/hsBuildInfo.inl.cmake

* plDetectorLog was initializing before plProduct had initialized its static strings, leading to some weird stuff where the User Data Folder path was missing "Uru Live"
* Was running with AddressSanitizer to try to track down some GL Pipeline issues, and ended up tracking down a bunch of other issues and warnings first.
* It is (apparently) undefined behaviour to cast non-memory-aligned values to int types, which we were doing in a few spots (and are still doing in a bunch more spots). This fixes the easy ones in plUUID and hsStream. Also, `memcpy` is a built-in now so there should be no speed benefit to doing casting.
* `fRegisteredForTime` (and a few other values) were never being zero initialized in plTransitionMgr
* plBufferedFileReader's `fBuffer` is created with `new[]` but was …

Sanitizer fixes and plProduct static init fix

---

Scripts/Python/xOptionsMenu.py
Sources/Plasma/FeatureLib/pfPython/pyGUIControlEditBoxGlue.cpp
Sources/Plasma/NucleusLib/pnInputCore/plInputMap.cpp

Previously, it was possible to get the key map chronicle into an invalid state with the same key bound to multiple controls. You can reproduce that by binding UpArrow to "start chat" then rebinding UpArrow to "move forward". The chronicle will then have two entries for UpArrow in it. The bindings will behave as you expect until you quit and restart Uru, at which point UpArrow will be bound to "start chat" again. The only way to fix this is by resetting the key map to default.
To fix this, I cleaned up the code to make the ownership of the key map more clear. Previously, the code half-handedly updated the vault chronicle value and the key map. Now, we bind any input directly, and completely rewrite the chronicle each time a key is bound. In this way, the UI display, key bindings, and key …

Key Map dialog improvements.

---

Sources/Plasma/CoreLib/hsThread_Unix.cpp
cmake/CompilerChecks.cmake
cmake/hsConfig.h.cmake

In some non-standard setups that slip through our checks, this function doesn't exist and we should guard against calling it. Since it's only used for debugging, let's just use CMake to check if it's defined in the header rather than complicated conditionals in the code for all the different possible versions of this that might exist (or not exist).

Detect pthread_setname_np with CMake

---

Sources/Plasma/CoreLib/hsStream.cpp
Sources/Tests/CoreTests/CMakeLists.txt
Sources/Tests/CoreTests/test_RAMStream.cpp

This was added because UBSan was warning that we were calling memcpy with a null destination, and while that is technically true, it was also a no-op because it was copying 0 bytes. A null buffer gets properly resized with the data in the next step, so this is actually expected behaviour that is broken by asserting too early.
Instead, detect the cases where we're calling memcpy with actual data, and assert in those cases that the RAMStream buffer is non-null.

Fix a bad assert in hsRAMStream

---

CMakeLists.txt
Sources/Plasma/FeatureLib/pfMetalPipeline/CMakeLists.txt
cmake/FindMetal.cmake

Metal was introduced in OS X 10.11 El Capitan, so the framework doesn't exist on older Apple systems. Instead of trying to unconditionally use it on Apple devices, check for the framework first.
Note: Metal still only works with the Xcode project generator, and not with Makefiles/Ninja because CMake doesn't yet know how to handle the metal shaders.

Don't try to enable Metal on older Macs

---

Sources/Plasma/FeatureLib/pfMetalPipeline/ShaderSrc/FixedPipelineShaders.metal

Affects the single weight animations in places like Garden.
We used to transpose matrices on the CPU side before they were sent to the GPU. I removed transposing and just flipped the multiply order in the shaders, but I think this case escaped. This was causing the trees in Garden to be wildly distorted.

Fix for Metal skinning blend matrix being multiplied in wrong order

---

Sources/Plasma/Apps/plClient/Mac-Cocoa/main.mm
Sources/Plasma/Apps/plClient/main.cpp
Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClient.h
Sources/Plasma/Apps/plClient/win32/plClient_Win.cpp
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/PubUtilLib/plPipeline/hsG3DDeviceSelector.cpp
Sources/Plasma/PubUtilLib/plPipeline/hsG3DDeviceSelector.h

* There's a static initializer ordering issue that sometimes crops up with the `hsG3DDeviceSelector` Device Enumerator vector on Linux which causes crashes (not that there's much of a client to crash at the moment). Easy enough to change the vector to a function static rather than a global static to work around the problem.
* Support loading ModDLLs on Linux and macOS using `dlopen` and `dlsym`.

ModDLL & Linux hsGD3DeviceSelector fixes

---

Sources/Plasma/Apps/plClient/Mac-Cocoa/PLSKeyboardEventMonitor.mm
Sources/Plasma/PubUtilLib/plInputCore/plInputDevice.cpp

This is for fixing #1599.
I don't see any facilities in Cocoa to query the current state of caps lock, only updates. It seems like that might be present in HID - but HID is gated by security permissions in recent macOS releases. So far I've considered HID out of bounds for macOS.
@dpogue - If you have any Cocoa APIs I don't know about I'd be happy to implement. Would also be happy to forward on to Apple for guidance. I didn't see anything during my research online - and it does not even seem like the Game Controller framework supports querying Caps Lock. But my investigation was pretty shallow.

Fixing caps lock input on macOS

---

cmake/FindPhysX.cmake

This resolves an issue where PhysX libraries installed with generic names at a system level were being found preferentially ahead of the ones created by vcpkg.

FindPhysX should search specific lib names first

---

Sources/Plasma/Apps/plClient/CMakeLists.txt

There's an extra `install` function call that seems to be causing the pngs to be copied to the client directory. This history of this seems to go back to 6fa6565 which was a commit about fixing Metal shaders. Metal shaders do not seem to be affected by this change now. The other possibility is that the Mac build didn't use to call plasma_executable (which I believe is where install dirs are supposed to be set) so this might have been patching over that missing bit.

Fixing banner pngs being included in root folder of Mac client

---

Sources/Plasma/CoreLib/CMakeLists.txt
Sources/Plasma/CoreLib/hsFILELock.cpp
Sources/Plasma/CoreLib/hsFILELock.h
Sources/Plasma/PubUtilLib/plStatusLog/plStatusLog.cpp
Sources/Plasma/PubUtilLib/plStatusLog/plStatusLog.h

This is an alternative to #1603, inspired by https://github.com/H-uru/Plasma/pull/1603#issuecomment-2235700787.
The global semaphore has been observed to not be released on unix like platforms when the process exits. So, we convert to file locks, which will be released on process exit on unix like platforms. Unfortunately, Win32 file locks and POSIX file locks have slightly different semantics in that Win32 locks are mandatory and POSIX locks are advisory, which can result in slightly different behavior. OTOH, this should fix the client deadlocking until the system is restarted, so this should be an overall win.

Use system wide file locks to synchronize log files.

---

Sources/MaxPlugin/MaxComponent/plAutoUIBase.cpp

Fixes #1613.
3ds Max 2020 is also affected by `MoveWindow()` not properly resizing AutoUIs. So, relax the check back to 3ds Max 2020.

Fix #1613.

---

Scripts/Python/xHighLevelStarTrekDoor.py

Not saying this is better but its less bad
Removes age owner from controlling the triggering of the doors
Removes the SendNote() stuff it was doing
Removes the doorstack tracking
Makes the door opening and closing rely on the SDL triggering
Makes the SDL trigger only happen by the person who set off the door sensor
I think ive fixed some of the race conditions but this is a multiplayer script and those are hard to troubleshoot

make xHighLevelStarTrekDoor.py to be less bad

---

CMakeLists.txt

Fixes #1616.
Don't build the 3ds Max plugin in external release builds. External releases don't include Age creation plugins, they are just for players. Further, some of the security lockdowns break critical plugin features.

Fix #1616.

---

Sources/MaxPlugin/MaxPlasmaMtls/Materials/plClothingMtlPBDec.h

Fixes #1617.
This invalidates the UI when the clothing material combo box selections are changed. By invalidating the UI, the texture pickers update appropriately. I also added some extra safety valves to reduce spurious updates that the debugger showed coming through.

Fix #1617.

---

CMakeLists.txt
Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/FeatureLib/pfMetalPipeline/CMakeLists.txt
cmake/CMakeDetermineMetalCompiler.cmake
cmake/CMakeMetalCompiler.cmake.in
cmake/CMakeMetalInformation.cmake
cmake/CMakeTestMetalCompiler.cmake
cmake/Dependencies.cmake
cmake/MetalShaderSupport.cmake

This removes the strict requirement to use the Xcode project generator, but still requires the Xcode build tools (and specifically the Metal compiler) to be installed. With these changes, I was able to build and launch plClient.app locally with a Makefile build, and it rendered as expected (so I'm assuming the Metal shaders are working).
I expect that our official stance will always be that the Xcode project generator is the recommended and supported way to do macOS builds, but any day I don't have to launch Xcode is a good day.
Note: the new CMake files came from https://github.com/dpogue/CMake-MetalShaderSupport

Allow building macOS client with Makefiles/Ninja

---

Scripts/Python/plasma/Plasma.py
Scripts/Python/plasma/PlasmaTypes.py
Scripts/Python/stupStartUp.py
Sources/MaxPlugin/MaxComponent/plAutoUIBase.cpp
Sources/MaxPlugin/MaxComponent/plAutoUIBase.h
Sources/MaxPlugin/MaxComponent/plAutoUIParams.h
Sources/MaxPlugin/MaxComponent/plPythonFileComponent.cpp
Sources/MaxPlugin/MaxMain/plPythonMgr.cpp
Sources/MaxPlugin/MaxMain/plPythonMgr.h
Sources/Plasma/FeatureLib/pfPython/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonParameter.h
Sources/Plasma/FeatureLib/pfPython/pyImage.cpp
Sources/Plasma/FeatureLib/pfPython/pyImage.h
Sources/Plasma/FeatureLib/pfPython/pyImageGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyImageLibMod.cpp
Sources/Plasma/FeatureLib/pfPython/pyImageLibMod.h
Sources/Plasma/FeatureLib/pfPython/pyImageLibModGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyLayer.cpp
Sources/Plasma/FeatureLib/pfPython/pyLayer.h
Sources/Plasma/FeatureLib/pfPython/pyLayerGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pySceneObject.cpp
Sources/Plasma/FeatureLib/pfPython/pySceneObject.h
Sources/Plasma/FeatureLib/pfPython/pySceneObjectGlue.cpp
Sources/Plasma/PubUtilLib/plModifier/plImageLibMod.cpp
Sources/Plasma/PubUtilLib/plModifier/plImageLibMod.h

In order to facilitate the expansion of existing Ages as well as adding new Fan Ages, this PR provides a way to modify textures dynamically through Python scripts.  It is especially ideal for otherwise-identical meshes whose appearance can be easily changed with only a texture swap.  Book covers and Linking Panels are the primary intended targets.
Planned uses:
- Random selection of backdrop images on the StartUp menu screen, showcasing Ages from interesting perspectives.
- Adding new books to the Nexus with minimal modifications.  Currently, to add a new Age to the Nexus, an entire new copy of the book mesh and animations is required, with extensive and error-prone wiring and material duplication.  This PR allows the entire book machine jumble to be simplified into a single book and an …

Enable Python access to plLayer and ImageLibMod textures.

---

Sources/Plasma/CoreLib/hsFILELock.cpp

The logic in `hsFILELock::ILock()` is incorrect on Win32. We should only fail immediately if we are *not* blocking. As it stands, running multiple clients can cause the lock to fail, resulting in an uncaught exception being thrown.

Fix crash when running multiple clients on Windows.

---

Sources/Plasma/PubUtilLib/plGImage/plPNG.cpp

Pngcrush optimizer will sometimes create greyscale images for the cursor resources.  These are not loaded correctly without being explicitly converted.

Support Greyscale PNGs created by Pngcrush.

---

Scripts/Python/xLinkingBookGUIPopup.py

Adjust script to actually use cover image defined in `xLinkingBookDefs.py`. Fixes #1338 
The script currently makes the Relto shelf and some other Books gain the "default" cover and/or extra pages, so it's a draft for now.

Fix Linking Book cover function

---

Sources/MaxPlugin/MaxComponent/plPythonFileComponent.cpp

These errors really only make sense if the artist has actually set something. If the field is blank, don't warn about what they specified not being found. That doesn't even make sense!

Silence overzealous Python File component errors.

---

Sources/MaxPlugin/MaxComponent/plAutoUIBase.cpp
Sources/MaxPlugin/MaxComponent/plAutoUIParams.cpp
Sources/MaxPlugin/MaxComponent/plAutoUIParams.h

Using the pick material button class causes the underlying mipmap to be exposed to Python instead of the layer. Therefore we add a shim to only expose the layer.

Fix `ptAttribLayer` being exported incorrectly from Max.

---

vcpkg.json

Pipewire is supposed to become the new standard audio system on desktop Linux, replacing PulseAudio (which itself replaced the cursèd mess of Also/OSS/Jack (except all of those somehow still exist... 😣 ))
It's not enabled by default in vcpkg's openal-soft package, but is available as a feature that we can opt into.

Enable pipewire backend for OpenAL on Linux

---

Sources/MaxPlugin/MaxConvert/plBitmapCreator.cpp

Workaround the problem until the rest of the fix in #1623.
As discussed in IRC and Discord, 3ds Max does some manipulation and pretty much always successfully loads the bitmap data. Unfortunately, we are trying to access the file manually here, which might be an absolute path to a file on another machine. This path may not be valid on our system, which fails, causing textures to be duplicated.

Work around not-found textures.

---

Sources/Plasma/FeatureLib/pfMetalPipeline/ShaderSrc/FixedPipelineShaders.metal
Sources/Plasma/FeatureLib/pfMetalPipeline/ShaderSrc/ShaderTypes.h
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.cpp

This fixes the popping issue discovered while investigating bump maps in BumpDemo.
Similar changes may need to be done to OpenGL. These changes will also need to be back ported into the per pixel lighting branch.

Implementing light range support in Metal

---

Sources/Plasma/FeatureLib/pfMetalPipeline/ShaderSrc/FixedPipelineShaders.metal
Sources/Plasma/FeatureLib/pfMetalPipeline/ShaderSrc/ShaderTypes.h

The matrix multiply order was incorrect. Also added some clarity to the varaible names.
These changes impact the reflection path - but I'be been unable to verify the before or after state. As discussed in IRC use of reflect seems to be rare and the one case it's used for does not seem to be working in D3D or Metal.
This bug was found in Kemo - specifically with the light posts where the light rays use a normal UV projection. The normal UV path fix was tested in Kemo.

Fixing normal based UV calculation in Metal shader

---

.github/workflows/ci.yml

The newer 24.04 runner has too many issues 😞

Use the Ubuntu 22.04 runner for Linux CI for now

---

Sources/Plasma/PubUtilLib/plDrawable/plDrawableSpans.cpp

Adding an if check to resize the buffers only when there is a risk of an overflow.
Every pass through is resizing the scratch buffers in SortVisibleSpans. Resize is completely deallocating and reallocating the buffers. This is resulting in a ~5% performance drag - so this change results in a ~5% performance improvement on the main loop.
It’s possible this is a result of 78c0b48 which moved this storage over to std. I don’t know if the Cyan array implementation would have handled this.
I don’t see any reason this would create issues - there doesn’t seem to be code that relies on the size of the vectors. The vectors only need to be correctly sized to fit all the data required.

Preventing resize overuse in SortVisibleSpans

---

Sources/Plasma/FeatureLib/pfMetalPipeline/ShaderSrc/FixedPipelineShaders.metal
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.h

The D3D9 shadow system would manipulate lights to properly cast shadows. This change decouples Metal shadows from the lighting system and instead passes the required variables directly to the shadow renderer. This allows Metal to avoid expensive light changes to render shadows.
Also includes a fix for high shadow strength causing shadows to be too dark. The Metal pipeline was not clamping the output diffuse color into a valid range.
These changes are to support #1551 by preventing shadows from needing to touch the cache states for the lighting system. But these changes can be merged and reviewed independently.

Unhooking Metal shadows from the lighting system

---

Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore_Apple.cpp

Minor fixes
- Keychain changes apparently need to happen from a secondary thread - and not the main thread. Xcode is now warning about it.
- Had some issues with Keychain not updating reliably on one of my machines. Some refinements that seem to make Keychain happier with updating password records by simplifying the queries.

More keychain fixes

---

Scripts/Python/xDialogStartUp.py
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIButtonMod.cpp
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIButtonMod.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIDialogNotifyProc.cpp
Sources/Plasma/FeatureLib/pfMessage/pfGUINotifyMsg.h

This allows setting the active player from the StartUp Age by simply double clicking on the button corresponding to the player you want to activate.

SetActivePlayer when double clicking on the player name.

---

Sources/Plasma/FeatureLib/pfPython/pyImage.cpp
Sources/Plasma/FeatureLib/pfPython/pyLayer.cpp
Sources/Plasma/FeatureLib/pfPython/pyLayer.h
Sources/Plasma/FeatureLib/pfPython/pyLayerGlue.cpp

This is useful for setting textures that are in global PRPs.

Allow `ptLayer.setTexture()` for unloaded images.

---

building.html
running.html

Update building/running instructions for macOS

---

Scripts/Python/nxusBookMachine.py

Requires #1632.
Requires corresponding assets PR H-uru/moul-assets#268.
This will allow us to more easily ingest fan Ages in the game without requiring their information to be mainlined.

Dynamic Nexus

---

Sources/MaxPlugin/MaxComponent/plAudioComponents.cpp
Sources/MaxPlugin/MaxMain/plPythonMgr.cpp
Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/PubUtilLib/plAnimation/plAGAnimInstance.cpp
Sources/Plasma/PubUtilLib/plAnimation/plAGAnimInstance.h
Sources/Plasma/PubUtilLib/plAnimation/plAGChannel.cpp
Sources/Plasma/PubUtilLib/plNetMessage/plNetMessage.h
Sources/Plasma/PubUtilLib/plSDL/plStateVariable.cpp

Most calls to these functions have already been removed in previous `ST::string`/Unicode conversion work. This PR takes care of the last few remaining uses and finally drops these custom functions (in favor of `ST::string` and standard C APIs).
Important difference: `hsStrncpy` always ensured that the destination string is 0-terminated, whereas the standard C `strncpy` will *not* add a 0 terminator if the destination buffer is too small to hold the entire source string. So we do lose this convenience/safety feature by switching to standard functions. But considering that (after this PR) the codebase only contains 12 `strncpy` calls in total, I don't think `hsStrncpy` is worth keeping around (especially not in the HeadSpin.h header that's included almost everywhere).

Remove last uses of `hsStrcpy` and `hsStrncpy`

---

vcpkg.json

Of particular note, this updates OpenAL-Soft to bring in the fixes for surround sound on macOS.
* **asio**
`1.30.2` -> `1.32.0`
* **curl**
`8.8.0` -> `8.12.1`
* **expat**
`2.6.2` -> `2.6.4`
* **fontconfig**
`2.14.2#1` -> `2.15.0#2`
* **freetype**
`2.13.2#1` -> `2.13.3`
* **libarchive**
`3.7.2` -> `3.7.7#2`
* **libjpeg-turbo**
`3.0.2` -> `3.1.0#1`
* **libpng**
`1.6.43#2` -> `1.6.46`
* **libvpx**
`1.13.1#3` -> `1.13.1#4`
* **libwebm**
`1.0.0.28#1` -> `1.0.0.31#1`
* **openal-soft**
`1.23.1` -> `1.24.2`
* **openssl**
`3.3.1` -> `3.4.1`
* **opus**
`1.5.1` -> `1.5.2`

Update vcpkg to 2025.02.14 tag

---

Scripts/Python/plasma/Plasma.py
Scripts/Python/plasma/PlasmaConstants.py
Scripts/Python/plasma/PlasmaGameConstants.py
Scripts/Python/plasma/PlasmaVaultConstants.py

Preparation for #1661 to make the diff more readable. This sorts all definitions in the Python stubs consistently, according to the established sorting style in the stubs:
* By default, all definitions are sorted in case-sensitive alphabetical order.
* Enum constants are sorted by their numeric value.
* In classes, all attributes/properties are placed before all methods.
This PR *only* fixes the sorting and contains no other fixes or style changes.

Sort Python stubs consistently

---

Sources/Plasma/PubUtilLib/plAudio/plAudioSystem.cpp
Sources/Plasma/PubUtilLib/plAudio/plAudioSystem.h
Sources/Plasma/PubUtilLib/plAudio/plAudioSystem_Private.h
Sources/Plasma/PubUtilLib/plAudio/plSound.cpp
Sources/Plasma/PubUtilLib/plAudio/plSound.h
Sources/Plasma/PubUtilLib/plAudio/plWin32GroupedSound.cpp
Sources/Plasma/PubUtilLib/plAudio/plWin32StaticSound.cpp
Sources/Plasma/PubUtilLib/plAudio/plWin32StreamingSound.cpp

This optimizes the "Soft Update" portion of the audio system update. According to my profiling, with 101 male avatars in an Age (resulting in approximately 31,000 sounds loaded), this function would take 7ms on my Ryzen 9 7900X3D. I have something of an overkill CPU, so this kind of drag in the update loop is unacceptable. The problem is that the sounds are all being stored in an intrusive doubly linked list, which is being traversed and partially bubble sorted each update. This pull request changes the container from the intrusive doubly-linked list to an `std::vector` and uses `std::sort()` to sort the active sounds. This change results in the "Soft Update" portion of the update loop only taking about 3ms on my Ryzen 9 7900X3D.
As a bonus, I have improved the semantics around accessing …

Optimize some poorly performing parts of ASYS.

---

Sources/Plasma/PubUtilLib/plAudioCore/plOGGCodec.cpp
Sources/Plasma/PubUtilLib/plAudioCore/plOGGCodec.h

The error handling code here was broken and tried to free a not yet initialized pointer. This PR adjusts the initialization order to fix that.
Also improved the error messages to include the specific error code returned by libvorbis, along with a description of the error code, if possible.
(The error reporting in plAudioCore could use some improvements in general. Currently, everything is reported via `hsAssert`, rather than returning the error message to the caller. But that is work for another time.)

Fix hard crash in `plOGGCodec` when opening an .ogg file containing invalid data

---

Scripts/Python/xOptionsMenu.py

The old code sometimes wrote KeyMap chronicles containing *two* spaces between key bindings. The new code incorrectly assumed that there is always exactly *one* space between key bindings, causing all of the key bindings to be shifted around if the KeyMap chronicle contained an extra space.
Detailed repro steps:
1. Log in using a client that has the "old" key map code (before #1573).
2. Change a key binding for an action that can have two keys (e. g. add "J" as the secondary key for "Jump").
3. Close the game.
4. Log in with the same avatar using a client that has the "new" key map code (after #1573).
5. Open the Key Map options and observe that most key bindings are mixed up.
If you repeat steps 4 and 5 with a client that has this PR applied, the key bindings should show up correctly …

Fix incorrect parsing of some KeyMap chronicles written by old code

---

Sources/MaxPlugin/MaxComponent/plResponderLink.cpp

Parameters were typed incorrectly, causing the reference to be tossed.

Fix #1667.

---

Scripts/Python/Personal.py
Scripts/Python/psnlYeeshaPageChanges.py

All the comments was doing here was list all the Relto pages you had if you had not gotten the 5th page
Removing that section allows removing the xLinkingBookDefs import

Remove xLinkingBookDefs import from psnlYeeshaPageChanges.py

---

Scripts/Python/plasma/Plasma.py
Scripts/Python/plasma/PlasmaGame.py
Scripts/Python/plasma/generate_stubs.py

Each class stub now only contains attributes defined directly by the class itself.
This shaves off over 4000 lines of duplicated stubs in Plasma.py! Apparently this is so much that the default Git diff algorithm gets confused and thinks some parts are additions/modifications... If you view the diff locally using any other diff algorithm, e. g. `git show --diff-algorithm=patience de41320571810e8123d3698142da3df7246f8881`, you can confirm that the stub changes are in fact all deletions.

Remove inherited attributes from Python stubs

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIListBoxMod.cpp

Fixes #1674 by adding checks for `fScrollControl`s that are `nullptr`.

Fix #1674.

---

Scripts/Python/nglnTreeMonkey.py
Scripts/Python/nglnUrwinBrain.py
Scripts/Python/payiUrwinBrain.py

If the spawn times array size exceeded 20 it would fail to write to the age SDL preventing that entire days creature appearances
This is pretty unlikely to happen due to the randomness and large timeframe the creatures can spawn
I only encountered it because I shortened the spawn windows to a few minutes.

Negilahn and Payiferen creature spawn time edge case

---

Sources/Plasma/PubUtilLib/plMessage/plInputEventMsg.cpp

Fixes #1677.
The field `plMouseEventMsg::fWheelDelta` was uninitialized by default and thus had an unpredictable value (which may or may not be 0) for most mouse events. This made the code for fading out the cursor sometimes wrongly think that the player is constantly scrolling, which prevented the cursor from ever fading out.
The underlying bug (the uninitialized field) has always been there since the original open-source release, but went unnoticed, because apparently nothing used the field. It only became noticeable recently with #1653, which added code to reset the cursor fade out timer upon scrolling.

Fix mouse cursor unpredictably not fading out

---

Sources/MaxPlugin/MaxComponent/plIgnoreComponent.cpp
Sources/Plasma/FeatureLib/pfMessage/pfGameGUIMsg.h
Sources/Plasma/FeatureLib/pfMessage/pfKIMsg.h
Sources/Plasma/NucleusLib/pnMessage/plAudioSysMsg.h
Sources/Plasma/NucleusLib/pnMessage/plCameraMsg.h
Sources/Plasma/NucleusLib/pnMessage/plClientMsg.h
Sources/Plasma/NucleusLib/pnMessage/plCmdIfaceModMsg.h
Sources/Plasma/NucleusLib/pnMessage/plCursorChangeMsg.h
Sources/Plasma/NucleusLib/pnMessage/plEnableMsg.h
Sources/Plasma/NucleusLib/pnMessage/plFakeOutMsg.h
Sources/Plasma/NucleusLib/pnMessage/plPlayerPageMsg.h
Sources/Plasma/NucleusLib/pnMessage/plRemoteAvatarInfoMsg.h
Sources/Plasma/NucleusLib/pnMessage/plSelfDestructMsg.h
Sources/Plasma/NucleusLib/pnMessage/plWarpMsg.h
Sources/Plasma/PubUtilLib/plMessage/plActivatorMsg.h
Sources/Plasma/PubUtilLib/plMessage/plCondRefMsg.h
Sources/Plasma/PubUtilLib/plMessage/plExcludeRegionMsg.h
Sources/Plasma/PubUtilLib/plMessage/plInputEventMsg.cpp
Sources/Plasma/PubUtilLib/plMessage/plInputEventMsg.h
Sources/Plasma/PubUtilLib/plMessage/plInputIfaceMgrMsg.h
Sources/Plasma/PubUtilLib/plMessage/plInterestingPing.h
Sources/Plasma/PubUtilLib/plMessage/plMatrixUpdateMsg.h
Sources/Plasma/PubUtilLib/plMessage/plPickedMsg.h
Sources/Plasma/PubUtilLib/plMessage/plPlayerMsg.h
Sources/Plasma/PubUtilLib/plMessage/plSpawnModMsg.h
Sources/Plasma/PubUtilLib/plMessage/plSpawnRequestMsg.h
Sources/Plasma/PubUtilLib/plMessage/plTimerCallbackMsg.h
Sources/Plasma/PubUtilLib/plMessage/plTriggerMsg.h

Various message classes had alternative constructors that *looked* like a convenience constructor, but actually ignored all arguments and behaved exactly like the no-arg constructor. Thankfully, none of these broken constructors were used anywhere.
Along the way, I also fixed a few other small oddities in some message constructors.

Remove `plMessage` subclass constructors that ignore their arguments

---

Scripts/Python/plasma/Plasma.py
Scripts/Python/plasma/PlasmaConstants.py
Scripts/Python/plasma/PlasmaGame.py
Scripts/Python/plasma/PlasmaGameConstants.py
Scripts/Python/plasma/PlasmaNetConstants.py
Scripts/Python/plasma/PlasmaVaultConstants.py
Scripts/Python/plasma/generate_stubs.py

Big automated reformatting of the stubs to get rid of some weirdness from Cyan's original formatting style. See commit messages for details.
I think all of these formatting choices are uncontroversial, but let me know if anything doesn't seem right. Thankfully, it's now very easy to re-adjust the formatting 🙂

Improve formatting of the Python stubs

---

Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.h
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalMaterialShaderRef.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPlateManager.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalTextFont.cpp

Only using storage mode managed on Mac - shared elsewhere. See: https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/ResourceOptions.html
Fixes for a few other compile issues when building for iPad OS.

Support for Metal renderer on iOS

---

Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalMaterialShaderRef.h

Vectors of const types are not allowed. Clang now aligns with the cpp spec.
The Xcode 16.3 release notes describe this change:
> libc++ no longer supports `std::allocator<const T>` and containers of const-qualified element type, such as `std::vector<const T>` and `std::list<const T>`. This used to be supported as an undocumented extension. If you were using `std::vector<const T>`, replace it with `std::vector<T>` instead. The `_LIBCPP_ENABLE_REMOVED_ALLOCATOR_CONST` macro can be defined to temporarily re-enable this extension. This compatibility macro will be removed in a future release. To assist with the clean-up process, consider running your code through Clang Tidy, with `std-allocator-const` enabled.

Fix builds for Xcode 16.3

---

Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGateKeeper.cpp

`AsyncAddressLookupName` can handle plain IP addresses just as well as host names, so there's no need for this special case.
This fixes the client being unable to connect to server addresses that contain a plain IP address with a port number (either in server.ini or when returned by the gatekeeper server). Cyan's original code supported this, but it was apparently broken by accident way back as part of some `plNetAddress` cleanup in #182 (3ea3473d1397d54322bbff177ca8ae6a36e46856).
This is relevant at least for MOSS, where the gatekeeper server returns addresses with an explicit port number if the server is running on a port other than the default 14617.
Server addresses consisting of a host name with a port number have always worked fine. Only the plain IP address case was broken.

Remove special case for plain IP addresses when connecting to servers

---

Scripts/Python/plasma/Plasma.py
Sources/Plasma/FeatureLib/pfPython/pyAgeVault.cpp
Sources/Plasma/FeatureLib/pfPython/pyAgeVault.h
Sources/Plasma/FeatureLib/pfPython/pyAgeVaultGlue.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.h

A vault Age node doesn't contain a PublicAgesFolder, so it's not obvious how this API was supposed to behave.
The correct current API for getting the list of public ages is `NetCommGetPublicAgeList`/`PtGetPublicAgeList`.

Remove unused and unimplemented `VaultGetAgePublicAgesFolder`

---

Scripts/Python/plasma/Plasma.py
Scripts/Python/psnlBahroPoles.py
Scripts/Python/psnlBookshelf.py
Scripts/Python/xLinkingBookGUIPopup.py
Sources/Plasma/FeatureLib/pfPython/pyAgeVaultGlue.cpp

The implementation of the two methods is identical, so this doesn't change any behavior.
However, the name `getBookshelfFolder` more accurately describes the method's behavior and avoids confusion with `ptVault.getAgesIOwnFolder`, which does *not* do the same thing as the `ptAgeVault` method:
* `ptVault.getAgesIOwnFolder` can be called in any age and returns the age   instances owned by the current avatar.
* `ptAgeVault.getBookshelfFolder` (formerly `ptAgeVault.getAgesIOwnFolder`) only succeeds when in an instance of Relto and returns the age instances owned by the avatar that owns the Relto instance (i. e. the books appearing in that Relto instance's bookshelf).
These two lists will be different if one avatar is visiting another avatar's Relto!

Remove `ptAgeVault.getAgesIOwnFolder` in favor of `.getBookshelfFolder`

---

.github/workflows/ci.yml

Windows 2019 runners will be unsupported next month.  Fortunately, MSVC 17 is ABI-compatible with MSVC 16.

CI: Update Windows CI builds to use Windows 2022 / MSVC 17.

---

vcpkg.json

This fixes our vcpkg builds on macOS. There is a compile problem with libffi described here:
https://github.com/libffi/libffi/pull/857
I noticed this problem with Xcode 26 (which is in beta) on a fresh Mac install. The PR states it's been a compile issue since Xcode 15.2 (where Xcode 15 is the current release series for Xcode.) It's possible that everyone including the build system has been working off a cached libffi so it went unnoticed until I tried a fresh machine.
libffi is a dependency of Python - we don't directly declare it.
This updates vcpkg to the 2025.04.09 tag:
- **expat**
2.6.4 -> 2.7.1
- **openal-soft**
1.24.2 -> 1.24.3
- **openssl**
3.4.1 -> 3.5.0

Fixing vcpkg libffi builds on macOS

---

Sources/MaxPlugin/MaxMain/MaxCompat.h

Building the Max plugins locally using the 2022 SDK gives me this warning many times:
```
C:\Program Files\Autodesk\3ds Max 2022 SDK\maxsdk\include\CS/bipexp.h(42): warning C4005: 'BIPDRIVEN_CONTROL_CLASS_ID': macro redefinition
...\Plasma\Sources\MaxPlugin\MaxMain/MaxCompat.h(297): note: see previous definition of 'BIPDRIVEN_CONTROL_CLASS_ID'
```
This PR fixes that by only defining the macro for versions that don't already define it themselves. According to the comments in the BIPEXP.H header, the old name was deprecated in Max 2022 (`MAX_VERSION_MAJOR` 24), so I assume all Max versions older than that don't have the new name yet.
I think this was caused by #1532, but apparently I didn't notice for a long while.

Fix `BIPDRIVEN_CONTROL_CLASS_ID` macro redef warning with 3ds Max 2022 SDK

---

Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.h
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp

Follow-up to #1539, part 3. This one is a bit bigger, but it makes the low-level vault code much easier to follow - so many helper structs and functions can be condensed into inline lambdas that are just a few lines long.
This intentionally only covers the low-level `NetCliAuthVault` functions. The high-level vault API still uses C-style function pointers for now - I'll convert that separately later, because I expect that to be a similar amount of effort.
Small detail: some of the `NetCliAuthVault` functions accepted `nullptr` if the caller doesn't need a callback, but others didn't. For consistency, I made all of the callbacks required now. If a caller really doesn't need a callback, it's easy to explicitly pass an empty lambda.

Lambda-ify auth server vault callbacks

---

Scripts/Python/nxusBookMachine.py

The Nexus dialog never marks that it is closed. This causes the open-dialog init to only run once. The dialog is fairly resilient and is able to cope with that not happening, with the exception of the Neighborhood button not being cleared out properly on exit. This fixes the state tracking so that the button is reinitialized correctly.

Fix #1705.

---

Sources/Plasma/NucleusLib/pnNetCli/pnNcCli.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp

Previously, this caused an assertion failure in the low-level network message code.
Also improved a few related asserts.

Display a proper error for too long avatar names

---

Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.h
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.h

Exclude regions were in practice not clearing because the PhysX CCT was holding onto the collision so as long as the "details" of the collision are largely the same. According to empirical evidence, once the preFilter stage is passed, PhysX never questions an actor again unless there's a position change or something of that nature. So, changing from an exclude region group to a detector volume isn't enough. We actually have to invalidate the character controller's cache to force re-evaluation of the collision. This allows us to move through a released exclude region immediately.
I suppose we could destroy and recreate the actor, but that feels like a more expensive option than just telling the character controllers to reevaluate their lives. Ideally, we would only do this for characters …

Fix #1708.

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIEditBoxMod.cpp

Fixes #1714, supersedes #1717.

Fix accidental conversion to unsigned in `pfGUIEditBoxMod`

---

Scripts/Python/xDialogStartUp.py

Fixes #1716 by making the implicit logic around focused explorers explicit. Gone is the idea of "toggling" - now the state must be explicitly requested. Also, apparently, there was some problem with a default state returning that Cyan was hacking around. Instead, when the GUI dialog is shown, we simply fixup everything.

Fix #1716.

---

Scripts/Python/Personal.py
Scripts/Python/nxusBookMachine.py
Scripts/Python/plasma/Plasma.py
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue4.cpp
Sources/Plasma/PubUtilLib/plMessage/plNetCommMsgs.h
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.h

The `gotPublicAgeList` callback method is called on any PythonFileMod that has one, not on the particular object passed to `PtGetPublicAgeList`.
Alternatively, I could try to change the implementation so that it actually uses the `cbObject` argument for calling the callback method. It depends on which style of callback API we would prefer going forward.
(For reference, a while back in 9b8523cdf7493a2889e81f26abb884cb6a4d98c0 in #1486, I made a similar change for another Python function.)

Remove `PtGetPublicAgeList` `cbObject` parameter that had no effect

---

Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.h
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalMaterialShaderRef.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.cpp

hsMatrix2SIMD used to do a transpose of the input hsMatrix - but shaders and code were rewritten to make this unnecessary. hsMatrix2SIMD still does a vestigial memory copy. This commit removes that memory copy.
This changes the meaning of hsMatrix2SIMD - so functions that need to make a copy now do so manually. Otherwise a direct cast is made. hsMatrix2SIMD has also been made constexpr.
This should result in a small (~1%) performance improvement in the Metal renderer main loop.

Remove copy from hsMatrix2SIMD in Metal renderer

---

Sources/Plasma/Apps/plClient/Mac-Cocoa/main.mm
Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClient.h
Sources/Plasma/Apps/plClient/plClientLoader.h
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/FeatureLib/pfGLPipeline/plGLPipeline.cpp
Sources/Plasma/FeatureLib/pfGLPipeline/plGLPipeline.h
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.cpp
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.h
Sources/Plasma/PubUtilLib/plPipeline/plNullPipeline.h

This PR is in preparation for further macOS resolution work. I thought I'd ask for review for just this chunk to lighten the load in the next PR.
Plasma uses hsWindowHndl for both the window and display types. This worked under Windows because both displays and windows are HWND types. (That's technically not true, under Windows the display should be an HMONITOR type. Was this refactored at some point?)
I'd added the dedicated type and made it a CGDirectDisplayID on macOS.

Adding dedicated hsDisplayHndl type

---

Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/NucleusLib/pnNetBase/pnNbConst.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp

Nothing else uses this constant anymore, so it doesn't need to be in HeadSpin.h. This also makes it clearer that this value can't be changed.

Replace `MAX_EXT` with a netcode-specific constant

---

Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/pyAgeVault.cpp
Sources/Plasma/FeatureLib/pfPython/pyVault.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultNode.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultPlayerInfoListNode.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultTextNoteNode.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetCliAgeJoiner.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetLinkingMgr.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.h

Follow-up to #1703. As expected, this is another big diff because of lots of helper structs and functions being inlined (especially commit f5759534475496170b45ae9a83c1f9ab0f04ee68). But now you can read the async vault code internals without your brain catching fire immediately.

Lambda-ify the high-level vault API callbacks

---

Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.h
Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalPipeline.cpp

Also making sure pt/vec bufs in IBlendVertBuffer are aligned correctly.
Fixes #1732

Putting copy back for hsMatrix2SIMD

---

Sources/MaxPlugin/MaxExport/plExportErrorMsg.cpp
Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/CoreLib/hsRefCnt.cpp
Sources/Plasma/NucleusLib/pnDispatch/plDispatch.cpp
Sources/Plasma/PubUtilLib/plAgeLoader/plAgeLoader.cpp
Sources/Plasma/PubUtilLib/plAudioCore/plWavFile.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglTrans.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXSimulation.cpp

Renames the following global functions in HeadSpin.h that were missing the usual `hs` prefix, and also adjusts some names for clarity (bikeshedding welcome 😉):
| previously | with this PR |
|---|---|
| `ErrorEnableGui` | `hsDebugEnableGuiAsserts` |
| `ErrorAssert` | `hsDebugAssertionFailed` |
| `DebugIsDebuggerPresent` | `hsDebugIsDebuggerPresent` |
| `DebugBreakIfDebuggerPresent` | `hsDebugBreakIfDebuggerPresent` |
| `DebugBreakAlways` | `hsDebugBreakAlways` |
| `DebugMsg` | `hsDebugPrintToTerminal` |
`DebugMsg` is the main motivation for this change, because there are multiple other functions/methods named `DebugMsg` elsewhere in the codebase, e. g. in `plLoggable`, `plSDLParser`, and `plClient`. This made it very difficult to tell if a call to `DebugMsg` went to the global function or …

Rename global `DebugMsg` function (and others) to avoid name collisions/confusion

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/Mac-Cocoa/main.mm

Prevent display sleep while game is running on macOS

---

Sources/Plasma/FeatureLib/pfMessage/pfKIMsg.h
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMsgHandler.cpp
Sources/Plasma/PubUtilLib/plVault/CMakeLists.txt
Sources/Plasma/PubUtilLib/plVault/Pch.h
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultClientApi.h

Was only used in an unused, stubbed out function (`VaultGetKILevel`).

Make `plVault` not use `pfKIMsg`

---

.github/workflows/ci.yml
cmake/QtDeployment.cmake

ANGLE was removed in Qt6, so `--no-angle` is no longer a legal argument to winqtdeploy. As a drive by, add Qt6 coverage for 64-bit Windows CI builds.
NOTE: I'm adding the CI commit first to demonstrate the failure and will push the fix after the first CI run finishes.

Fix Qt6 Deployment on Windows

---

Sources/Plasma/Apps/plClient/win32/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/winmain.cpp

Fixes #1767 and fixes the plClient entrypoint on Windows to use UCS-2 as well.

Fix #1761 stragglers.

---

Sources/Plasma/FeatureLib/pfConsole/pfConsole.cpp
cmake/CompilerChecks.cmake
cmake/hsConfig.h.cmake

`strnlen` isn't available on Mac OS X pre-10.7, as well as some Solaris systems, so we'll check if it exists and do the counting loop ourselves otherwise.
If we ever convert the whole console over to ST::string, this problem likely goes away

Check for (and polyfill) strnlen API

---

Sources/Tests/CoreTests/test_hsDarwin_CF.cpp
Sources/Tests/CoreTests/test_hsDarwin_NS.mm

It's apparently ill-advised to use non-ASCII characters in NSString `@`-literals or CFString `CFSTR` literals, so test those with pure ASCII strings and add separate tests with manually constructed strings for UTF8 testing.
Also wrap the NSString tests in autorelease pools to make sure nothing leaks.

Minor improvements to Darwin string tests

---

Scripts/Python/ahnyQuabs.py
Scripts/Python/plasma/Plasma.py
Scripts/Python/plasma/PlasmaConstants.py
Scripts/Python/plasma/PlasmaGame.py
Sources/Plasma/FeatureLib/pfGameMgr/CMakeLists.txt
Sources/Plasma/FeatureLib/pfGameMgr/pfGmVarSync.cpp
Sources/Plasma/FeatureLib/pfGameMgr/pfGmVarSync.h
Sources/Plasma/FeatureLib/pfPython/CMakeLists.txt
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/FeatureLib/pfPython/pyCritterBrain.cpp
Sources/Plasma/FeatureLib/pfPython/pyCritterBrain.h
Sources/Plasma/FeatureLib/pfPython/pyCritterBrainGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyGmVarSync.cpp
Sources/Plasma/FeatureLib/pfPython/pyGmVarSync.h
Sources/Plasma/FeatureLib/pfPython/pyGmVarSyncGlue.cpp
Sources/Plasma/NucleusLib/inc/plCreatableIndex.h
Sources/Plasma/PubUtilLib/plAvatar/plArmatureMod.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainCritter.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvBrainCritter.h
Sources/Plasma/PubUtilLib/plMessage/plAIMsg.cpp
Sources/Plasma/PubUtilLib/plMessage/plAIMsg.h
Sources/Plasma/PubUtilLib/plMessage/plMessageCreatable.h

This continues the game manager restore compatibility work by bringing back the VarSync quab game. The non-game manager version has been rewritten simultaneously to improve ownership and synchronization. This changeset has been in progress for over a year, so there are some remnants of ideas about how to improve synchronizing critter AI in the code that has been somewhat left by the wayside, specifically around the whole GoToGoal aspect. A lot of the commit messages are aspirational in that regard.
Notes:
- Fixed the client crash on Cyan's server when the owner of the VarSync game links out AND retains the quabs in their previous location.
- When the game owner is running this implementation, the "goal position" of the quabs will be synchronized to other clients, improving the behavior of …

Ahnoying GameMgr Redux

---

Scripts/Python/xJournalBookGUIPopup.py
Sources/Plasma/FeatureLib/pfConsole/CMakeLists.txt
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.h
Sources/Plasma/PubUtilLib/plGImage/plFont.h

This adds clickable links to journals. Links already somewhat existed in journals in that you could have an image or movie with a `link=[event ID]` attribute on the tag that fired a notification to the host Python script. This pull request extends that in a number of ways, rather creatively in some respects by:
- adding named anchors to journals
- adding the ability to link to named anchors using text, images, or movies
- adding the ability to link to URLs using text, images, or movies
Text based links can be created using `<a link=[event ID]>`. So, if you want some text to fire event 1 in the host script, use `<a link=1>`. EsHTML does not use closing tags, so to stop making text a link, use `<a link=clear>`. This is mostly consistent with `<img link=1>` and `<movie link=1>`. By default, …

Add clickable links to journal books.

---

Sources/MaxPlugin/MaxComponent/plGUIComponents.cpp
Sources/MaxPlugin/MaxComponent/plMiscComponents.cpp
Sources/MaxPlugin/MaxConvert/hsMaterialConverter.cpp
Sources/MaxPlugin/MaxConvert/plBitmapCreator.h
Sources/MaxPlugin/MaxConvert/plLayerConverter.cpp
Sources/MaxPlugin/MaxPlasmaMtls/Layers/plPlasmaMAXLayer.cpp
Sources/MaxPlugin/MaxPlasmaMtls/Layers/plPlasmaMAXLayer.h

Closes #1623 by either using the safer, new in Max 2022 `BMMGetFullFilename()` or by falling back to copying the `BitmapInfo` object in older versions of Max. I also centralized all of the conversions to `plPlasmaMAXLayer::GetBitmapFileName()`.

Resolve Max Textures During Export (Part Deux)

---

Sources/Plasma/NucleusLib/pnNetCommon/CMakeLists.txt
Sources/Plasma/NucleusLib/pnNetCommon/plNetAddress.cpp
Sources/Plasma/NucleusLib/pnNetCommon/plNetAddress.h
Sources/Plasma/NucleusLib/pnNetCommon/pnNetCommon.cpp
Sources/Plasma/NucleusLib/pnNetCommon/pnNetCommon.h
Sources/Tests/NucleusTests/CMakeLists.txt
Sources/Tests/NucleusTests/pnNetCommonTest/CMakeLists.txt
Sources/Tests/NucleusTests/pnNetCommonTest/test_plNetAddress.cpp

The code behind `plNetAddress` still used `inet_ntop`, `inet_pton`, and `getaddrinfo` instead of the corresponding Asio APIs. `getaddrinfo` is especially problematic, because it can block for an unpredictable amount of time because of DNS queries.
Thankfully, most of this code was already unused, except for the IPv4-to-string conversion. I reimplemented that part manually, because it seems overkill to depend on Asio just for a simple string conversion. (But at some point, we might want to properly reimplement `plNetAddress` based on `asio::ip::address`.)

Remove last non-Asio socket/internet API calls

---

Scripts/Python/plasma/PlasmaConstants.py
Scripts/Python/xJournalBookGUIPopup.py
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp
Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.h
Sources/Plasma/FeatureLib/pfPython/pyJournalBookGlue.cpp

Superceeds and closes #1679 by addressing concerns I had and fixing some disclosed drawbacks with the previous implementation.
Journals should now remember their last position, for the most part. I've retained the 1024 character limit for the chronicle to ensure nothing bad happens. This PR does not use JSON at all and also hashes the journal content to ensure that we don't assume that page numbers from old journal contents correspond to the new contents. Further, with this PR, the auto turn mechanic can tell the difference between closing the journal on the cover (the cover reopens) or closing the journal on the first page (the first page reopens).
Amusingly, I didn't realize it was possible to turn back to the cover in a journal until I was looking at this. For posterity, you can turn …

Journal Page Remembering (Part Deux)

---

Sources/Plasma/Apps/plClient/Mac-Cocoa/PLSView.mm

These are needed to select a player in the StartUp Age by double clicking on its entry in the list.

Add missing double click handler for macOS.

---

Sources/MaxPlugin/MaxMain/GlobalUtility.cpp
Sources/Plasma/FeatureLib/pfConsole/CMakeLists.txt
Sources/Plasma/FeatureLib/pfConsole/pfAudioConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsole/pfAvatarConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommandUtilities.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommandUtilities.h
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsole/pfConsoleCommandsNet.cpp
Sources/Plasma/FeatureLib/pfConsole/pfGameConsoleCommands.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleCmd.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleCmd.h
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleEngine.cpp
Sources/Plasma/FeatureLib/pfConsoleCore/pfConsoleEngine.h

A few declarations and macros were copy-pasted into each console command implementation file. This PR pulls them out into a proper shared header.
Also finally adds a named type for the `PrintFunc`s that get passed all around the console code.

Reduce copy-paste in console command implementation code
