Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/NucleusLib/pnAsyncCoreExe/Private/Win32/pnAceW32Dns.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
cmake/CompilerChecks.cmake
cmake/check_constexpr.cpp
cmake/hsCompilerSpecific.h.cmake

This introduces a safer template-version of arrsize, and fixes a couple of places where it was being used incorrectly in existing code.

Fix incorrect arrsize use

---

Sources/Plasma/FeatureLib/pfCamera/plCameraBrain.cpp
Sources/Plasma/PubUtilLib/plInterp/plController.cpp
Sources/Tools/MaxConvert/plMaxLightContext.h
Sources/Tools/MaxConvert/plRenderGlobalContext.cpp
Sources/Tools/MaxConvert/plRenderGlobalContext.h

Fixes some issues pointed out by Coverity. The biggest change here is that the Max plugin will now produce lightmaps correctly :smile:.

Fix some moar Coverity

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClient.h
Sources/Plasma/Apps/plClient/plClientLoader.cpp
Sources/Plasma/Apps/plClient/plClientLoader.h
Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/CoreLib/hsThread_Win.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientCommInterface.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgr.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp

This moves plClient's init into a thread such that there should no longer be any need to waste time with the "Starting URU... Please wait." dialog under normal usage. Please note that if your logic succeeds before the client is ready, we will still pop up the aforementioned dialog until the client is ready.

Really Fast Client Init

---

Sources/Plasma/PubUtilLib/plAvatar/plSittingModifier.cpp

Observed when linking in on DS: if an avatar sits at a sitting mod, that SO is not loaded yet. Boom!

Fix SittingModifier null dereference

---

Sources/Plasma/FeatureLib/pfCharacter/pfMarkerMgr.cpp
Sources/Plasma/FeatureLib/pfCharacter/pfMarkerMgr.h
Sources/Plasma/FeatureLib/pfPython/pyMarkerMgr.cpp
Sources/Plasma/FeatureLib/pfPython/pyMarkerMgr.h
Sources/Plasma/FeatureLib/pfPython/pyMarkerMgrGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultMarkerGameNode.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultMarkerGameNode.h
Sources/Plasma/FeatureLib/pfPython/pyVaultMarkerGameNodeGlue.cpp
Sources/Plasma/FeatureLib/pfPython/pyVaultNode.cpp
Sources/Plasma/PubUtilLib/plVault/Pch.h
Sources/Plasma/PubUtilLib/plVault/plVaultNodeAccess.cpp
Sources/Plasma/PubUtilLib/plVault/plVaultNodeAccess.h

This is part of #312, it represents all engine changes needed for storage of marker games in the vault. Please note that merging this before the python pull request will break marker games.

Vault marker engine changes

---

Sources/Plasma/NucleusLib/pnFactory/plCreatable.h
Sources/Plasma/NucleusLib/pnMessage/plWarpMsg.h

Missed some overrides in the creatable macros :(

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClient.h
Sources/Plasma/Apps/plClient/plClientLoader.cpp
Sources/Plasma/Apps/plClient/plClientLoader.h
Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgr.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.h
Sources/Plasma/PubUtilLib/plPipeline/DX/plDXPipeline.cpp

Resurrection of #507 (depends on #524). The various bugfix commits have all been squashed. Also fixes some major issues with exception swallowing and inability to attach debuggers to crashing plClients.

Init part deux

---

index.html
style.css

- Update versions and fix broken links.
- Add missing OpenAL SDK requirement.
- Upgrade resources and links to use HTTPS where available.

Update build instructions.

---

Sources/Plasma/PubUtilLib/plNetCommon/plNetMsgScreener.cpp

This has been observed to crash the client

Fix pointless c_str()'ing of an ST::string

---

Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/PubUtilLib/plGImage/plDynamicTextMap.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp

Eliminate implicit conversions from char_buffer to const char_T* for forwards compatibility with string_theory 2.0 (unreleased)

string_theory 2.0 forward compatibility

---

Sources/Plasma/NucleusLib/inc/plCreatableIndex.h
Sources/Plasma/PubUtilLib/plPhysX/CMakeLists.txt
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysical.h
Sources/Plasma/PubUtilLib/plPhysX/plPXSubWorld.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXSubWorld.h
Sources/Plasma/PubUtilLib/plPhysX/plSimulationMgr.cpp
Sources/Tools/MaxMain/plMaxNode.cpp

Adds plPXSubworld.This is exactly the same as plHKSubworld except the class IDs are different. Unfortunately, the gravity specifed only works on dynamic physicals aside from the avatar controllers. No relativity yet. I figure that proper avatar gravity should be deferred for a physics rewrite.

PXSubworld

---

CMakeLists.txt
Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/Apps/plClient/plClientLoader.cpp
Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/winmain.cpp
Sources/Plasma/CoreLib/plFileSystem.cpp
Sources/Plasma/CoreLib/plFileSystem.h
Sources/Plasma/FeatureLib/pfCrashHandler/plCrashSrv.cpp
Sources/Plasma/FeatureLib/pfSurface/plLayerAVI.cpp
Sources/Plasma/PubUtilLib/plFile/plBrowseFolder.cpp
Sources/Plasma/PubUtilLib/plFile/plSecureStream.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp
Sources/Tools/MaxComponent/plAvatarComponent.h
Sources/Tools/MaxConvert/plBitmapCreator.cpp
Sources/Tools/MaxExport/SimpleExport.cpp
Sources/Tools/MaxExport/plExportDlg.cpp
Sources/Tools/MaxMain/plMaxCFGFile.cpp
Sources/Tools/MaxMain/plMaxMenu.cpp

More string_theory 2.0 compatibility

---

CMakeLists.txt
README.md
Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/external/render_svg.py
Sources/Plasma/Apps/plClient/external/scalergba.py
Sources/Tools/CMakeLists.txt
cmake/CompilerChecks.cmake
cmake/FindDirectX.cmake
cmake/FindOpus.cmake
cmake/FindSpeex.cmake

This is a collection of fixes to make building under Appveyor's environment possible/easier, and some general updates to the library usages.

Fix build for Appveyor environment.

---

Sources/Plasma/PubUtilLib/plAvatar/plAvBrainCritter.cpp
Sources/Tools/MaxConvert/hsMaterialConverter.cpp
Sources/Tools/MaxMain/CMakeLists.txt

This fixes some compile/link issues found when using more modern libraries and compilers.

Various Compile Fixes

---

Sources/Plasma/FeatureLib/pfPython/cyAccountManagement.cpp
Sources/Plasma/FeatureLib/pfPython/cyAccountManagement.h
Sources/Plasma/FeatureLib/pfPython/cyAccountManagementGlue.cpp

I'm fairly certain these changes are safe. Considering it seems I managed to break my Dirtsand & Plasma installation while trying to remove a bit too many references, I couldn't test it.

Remove references to visitors

---

Sources/Plasma/PubUtilLib/plAudio/plVoiceChat.cpp

Added the memory library for std::make_unique
`#include <memory>`

Include header needed for std::make_unique

---

Sources/Plasma/FeatureLib/pfJournalBook/pfJournalBook.cpp

Caused Yessha Book pages to be blank https://cdn.discordapp.com/attachments/282045216221822978/643491894743007242/unknown.png

Fix PBML parsing errors introduced in #595.

---

README.md
prepare_env.ps1

Update build instructions and devlibs for VS 2015

---

index.html

This updates the gh-pages branch to reflect #613 and #614

Update SDK and devlibs links

---

Sources/Plasma/Apps/plClient/winmain.cpp

This fixes a crash reported at https://forum.guildofwriters.org/viewtopic.php?p=73814#p73814

Accept unicode characters in the login dialog.

---

.github/workflows/linux-ci.yml

since v1 is [apparently](https://github.com/actions/checkout/issues/23) [broken](https://github.com/H-uru/Plasma/pull/596#issuecomment-623196094)

Update to checkout v2

---

.gitignore

Die, die, die!
(The, the, the!)

Ignore items generated by MSVC cmake integration.

---

Scripts/Python/xOptionsMenu.py

Fix another deprecated list.sort().

---

Scripts/Python/ki/xKIChat.py
Scripts/Python/ki/xKIExtChatCommands.py

Migrated from https://github.com/H-uru/moul-scripts/pull/77

Add /r as a short version of /reply

---

Sources/Plasma/CoreLib/hsAlignedAllocator.hpp

This was causing me compiler errors on Linux with clang

Add <limits> to hsAlignedAllocator

---

prepare_env.ps1

Check PowerShell version and attempt to use more modern commands if they are available. Also don't assume Windows path separators.
This runs (to the point of failing to detect CMake) on Powershell for Linux.
Also ensure CMake generates projects that target Win32 instead of Win64.

prepare_env script improvements

---

Scripts/Python/ki/xKIConstants.py

Fixes Ae'gura GoMe Pub's /look text to better flow with the existing script.

Fix GoMePubNew look command text

---

Scripts/Python/jlakField.py
Scripts/Python/xAvatarCustomization.py

change python 2 `file` to python 3 `open`

---

Scripts/Python/islmMemorialImager.py

More fallout from python3, sigh.

Fix Ae'gura Memorial Imager.

---

Sources/Plasma/CoreLib/hsWindows.h
Sources/Plasma/PubUtilLib/plAudio/plAudioEndpointVolume.cpp

This crash was reported in IRC by a user running French Windows. The client would crash almost immediately upon the login dialog becoming visible. Upon investigation, string_theory was throwing an exception from formatting an `std::string` coming from `std::error_category::message()`. As best I can tell, the MSVCRT implementation of this facility is returning the error message encoded in the current codepage -- or windows-1252 in the case of French Windows. This works OK on English Windows, but we need to use proper unicode for other variants.

Fix a crash when writing error messages to the log.

---

Scripts/Python/xOptionsMenu.py

The keybindings were only ever loaded on our first visit to Relto. When using the -Age command line switch, we will completely bypass Relto, forcing the default keybindings. This turns on "Go To Where I Click" when using Korman's "Test Age" button. If you have never had this misfortune of using "Go To Where I Click", congratulations. You have won.

Fix "Go To Where I Click" when using Korman's Test Age.

---

Sources/Plasma/NucleusLib/pnMessage/CMakeLists.txt
Sources/Plasma/NucleusLib/pnMessage/plSDLModifierMsg.cpp

Remove unused plSDL references from pnMessage

---

Sources/Plasma/CoreLib/hsRefCnt.h

Fix typo in recently added hsWeakRef.

---

Sources/Tools/MaxConvert/hsMaterialConverter.cpp

Apparently MSVC is not smart enough to figure out this brain buster.

Fix ambiguous type error.

---

Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp

Fix "Dammit GCC"

---

Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp

This fixes the issue where Zandi might still be listening to Peter Gabriel instead of Mozart. In other words, this fixes the initially downloaded version of the sound playing instead of the updated version.

Decompress audio files on download.

---

Sources/Plasma/Apps/plClient/CMakeLists.txt
Sources/Plasma/Apps/plClient/external/render_svg.py

Fix cursor resolution (#795)

---

.github/workflows/windows-ci.yml

Unintentionally broken by #798.

Fix CI artifact upload.

---

Sources/Plasma/PubUtilLib/plNetGameLib/Intern.h
Sources/Plasma/PubUtilLib/plNetGameLib/Pch.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGame.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGateKeeper.cpp

I've been digging deep into the networking code, planning its refactor into something a bit more modern and cross-platform. This is one of the low-hanging fruits from my notes. I am disappointed that the deletions didn't make it to 1k LOC, but oh well.

De-duplicate lots of `NetTransRecv` code with modern C++.

---

Sources/Tools/MaxComponent/plResponderComponent.cpp

Fix bad override in MyRemapDir.

---

Sources/Plasma/CoreLib/hsBitVector.h
Sources/Plasma/CoreLib/hsBounds.h
Sources/Plasma/CoreLib/hsStream.cpp
Sources/Plasma/CoreLib/hsStream.h
Sources/Plasma/CoreLib/hsStringTokenizer.cpp
Sources/Plasma/CoreLib/hsWide.h
Sources/Plasma/CoreLib/plFileSystem.cpp

These pop up when building on Linux with `-Wall`

Fix some more minor CoreLib warnings

---

Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/Apps/plUruLauncher/winmain.cpp
Sources/Plasma/CoreLib/hsWindows.cpp
Sources/Plasma/CoreLib/hsWindows.h
Sources/Plasma/PubUtilLib/plAudio/plAudioEndpointVolume.cpp

This is an alternate fix for #822.

Only initialize COM when and where it's needed.

---

Sources/Plasma/NucleusLib/pnTimer/plTimerCallbackManager.cpp
Sources/Plasma/PubUtilLib/plScene/plRelevanceMgr.cpp

This tripped an assertion in debug mode. The looping was dumb anyway -- just use a properly managed type.

Remove reverse iterator in CSV parser.

---

Sources/Tools/CMakeLists.txt
Sources/Tools/plFontConverter/CMakeLists.txt
Sources/Tools/plFontConverter/plFontConverter.cpp
Sources/Tools/plLocalizationEditor/CMakeLists.txt
Sources/Tools/plLocalizationEditor/plAddDlgs.cpp
Sources/Tools/plLocalizationEditor/plEditDlg.cpp
Sources/Tools/plResBrowser/CMakeLists.txt
Sources/Tools/plResBrowser/plResBrowser.cpp
Sources/Tools/plResBrowser/plResTreeView.cpp

This cleans up some moc warnings and makes the CMake files cleaner.

Use CMake's AUTO{MOC,RCC,UIC} instead of manual wrapping of sources.

---

Sources/Plasma/PubUtilLib/plPipeline/DX/hsGDirect3D.cpp

Who wrote this junk? *Checks git blame...* Moving right along...

Don't leak the TnLEnum.

---

cmake/Dependencies.cmake

This was missing, as pointed out by @Deledrius in #846

Add package description for libwebm

---

cmake/Findlibwebm.cmake

Fixes finding libwebm on Linux

Also search for Unix-compatible libwebm library names.

---

.github/workflows/ci.yml

Archive Win64 builds for ease of download/testing

---

cmake/Dependencies.cmake

* Use https where possible
* Update a couple of domains to their newer values

Update dependency URLs:

---

Sources/Plasma/Apps/plUruLauncher/winmain.cpp

This fixes getting junk data in plProduct in plUruLauncher.exe

Fix static initialization order issue in plClientLauncher.

---

Scripts/Python/Vothol.py
Scripts/SDL/Vothol.sdl
Scripts/dat/Vothol.age
Scripts/dat/Vothol.fni

Adds the .age, .fni, .sdl and .py files for Vothol Gallery

Add Vothol Gallery to MOULa

---

Scripts/Python/Serene.py
Scripts/Python/xLinkingBookDefs.py
Scripts/SDL/Serene.sdl
Scripts/dat/Serene.age
Scripts/dat/Serene.fni

AGE, FNI, PY and SDL files for the Age of Serene for MOULa.

Add Serene to MOULa

---

Sources/Plasma/PubUtilLib/plDrawable/plDrawableGenerator.cpp
Sources/Plasma/PubUtilLib/plDrawable/plDrawableGenerator.h
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXPhysicalControllerCore.h
Sources/Plasma/PubUtilLib/plPhysical/plPhysicalProxy.cpp

This fixes the avatar physical proxy. The capsule generation code was derived from the same in libcinder. If you would like to contribute a better capsule generator, be my guest :smile:

Fix avatar physical proxy.

---

Sources/Plasma/PubUtilLib/plMessage/plLOSHitMsg.h
Sources/Plasma/PubUtilLib/plPhysX/plLOSDispatch.cpp
Sources/Plasma/PubUtilLib/plPhysX/plLOSDispatch.h
Sources/Plasma/PubUtilLib/plPhysX/plPXLOSDispatch.cpp
Sources/Plasma/PubUtilLib/plPhysX/plPXSimDefs.h

Fixes [goofy camera LOS issues](https://www.youtube.com/watch?v=voxqgP6VrPs) that are way more apparent with @DoobesURU's camera regions in Vothol.

Fix goofy camera LOS issues.

---

.gitmodules

Update gtest submodule to 1.11.0

---

Scripts/Python/kdshGlowInTheDark.py

This fixes the issue reported by CalumTraveler in OU#Dev
Calum entered the Kadish Elevator at the bottom and tried to leave before it started to rise.
He was prevented from leaving.

Removes Kadish Moon Elevator subworld from interacting with player

---

Scripts/dat/Serene.age

Re-adds Serene's snow and bugs. Fix by Ehren.

Add Serene Particle Effects

---

Scripts/Python/grsnGearRide.py

In response to reports on OpenUru#dev...
The regions are goofed up somehow such that we get ambiguous notifications. So, we keep track of what's open and enter/exit as appropriate. As a bonus, because the stupid animation is not properly synchronized between players (needs a PRP fix), don't net force the regions being enabled/disabled.

Fix improper warp when exiting the Garrison gear.

---

Scripts/Python/xDynTextLoc.py
Scripts/Python/xDynaTextBoy.py

Adds xDynTextLoc.py, a reimplementation of xDynTextObj,py that does not use a hardcoded lookup table. Also fixes an attribute type problem in xDynaTextBoy.py.

Korman 0.12 Localization Stuff

---

Sources/Tools/MaxConvert/plRenderGlobalContext.cpp

Fixes #934.
Can't repro #933 yet...

Fix reported crashes in 3ds Max plugin.

---

Sources/Plasma/FeatureLib/pfLocalizationMgr/pfLocalizedString.cpp

Fix #1021.

---

Scripts/Python/ki/__init__.py

#959 Seems to address the remaining H'uru-base issue @Hoikas mentioned in this ticket

Ensure KI chat fade timer won't start while the user is in chat mode

---

Sources/Plasma/PubUtilLib/plAudioCore/plWavFile.cpp
Sources/Tools/MaxComponent/plAudioComponents.cpp
Sources/Tools/MaxComponent/plAudioComponents.h
Sources/Tools/MaxComponent/plMaxWaveUtils.cpp
Sources/Tools/MaxComponent/plMaxWaveUtils.h
Sources/Tools/MaxExport/plExportDlg.cpp

I'm happy to drop the third and fourth commits if you prefer them not to be included. The fourth one in particular probably needs more investigation to figure out what to do (otoh, it happens on exit, so leaking memory maybe isn't a concern?)

Fix PlasmaMax sound component crashes

---

.github/workflows/ci.yml

See https://github.com/actions/upload-artifact/issues/281#issuecomment-991165471

Fix CI Failures.

---

Scripts/Python/krelPodium.py
Scripts/SDL/Neighborhood.sdl
Scripts/SDL/Neighborhood02.sdl

Adds 1 new SDL variable "nb01CmnRmAudio" to neighborhood.sdl and neighborhood02.sdl
Changes made to krelPodium.py to allow multiple audio messages to play one after another.

Changes made for Podium Audio in hoods to work

---

Scripts/Python/Serene.py

Takes out unneeded and glitchy calendar code mess for holiday deco.

Remove unruly calendar code

---

Scripts/SDL/VeeTsah.sdl

Re-adding the Veelay SDL change for the new Relto page...since I erroneously deleted the other one while cleaning house. 😊

Add Relto Page Vis state

---

Scripts/SDL/Kveer.sdl

Adds new SDL states for Atrus clothing item.

K'veer Update August 2021

---

Scripts/Python/Tiam.py
Scripts/Python/Vothol.py
Scripts/Python/trebivdil.py

Squelch script ID warnings in 3ds Max.

---

Sources/Tools/MaxComponent/plAutoUIBase.cpp
Sources/Tools/MaxComponent/plPythonFileComponent.cpp

Fixes crashes observed when closing 3ds Max 2022 when Python files have been loaded.

Fix max crash on exit.

---

Sources/Plasma/Apps/plClient/winmain.cpp
Sources/Plasma/FeatureLib/pfPatcher/pfPatcher.cpp
Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNcCli.cpp
Sources/Plasma/NucleusLib/pnNetCli/pnNetCli.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2Auth/pnNpCli2Auth.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2File/pnNpCli2File.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/Protocols/Cli2GateKeeper/pnNpCli2GateKeeper.h
Sources/Plasma/NucleusLib/pnNetProtocol/Private/pnNpCommon.cpp
Sources/Plasma/NucleusLib/pnNetProtocol/Private/pnNpCommon.h
Sources/Plasma/NucleusLib/pnUtils/pnUtStr.cpp
Sources/Plasma/NucleusLib/pnUtils/pnUtStr.h
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.h
Sources/Plasma/PubUtilLib/plNetCommon/plNetServerSessionInfo.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglFile.h
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglGateKeeper.cpp

... instead of assuming the size of `wchar_t` is 16-bit (hint: it isn't on most *nix platforms).

Use `char16_t` over the wire protocols.

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUITextBoxMod.cpp
Sources/Plasma/PubUtilLib/plDrawable/plInterMeshSmooth.cpp

Fix missing `#include <memory>` in a few places

---

Sources/Plasma/FeatureLib/pfPasswordStore/pfPasswordStore_Apple.cpp

The keychain support could create a keychain item, but it couldn't update it, that's a separate API. This change checks for a duplicate item error, and then updates the item.
The keychain API changed in macOS 10.10, but the old API is not deprecated as far as I can tell. I wrote the update function in the newer API because it had the most current documentation I could refer to.
My plan is to keep trickling in these changes to reduce review burden on the bigger pull requests, and reduce the amount of drift I have from the master branch.

Add support for updating keychain on macOS

---

Scripts/SDL/Dereno.sdl
Scripts/dat/Dereno.age
Scripts/dat/Ercana.age

Assets for this are located here - https://github.com/H-uru/moul-assets/pull/100

Files for Backpack and Backpack2 collectibles

---

Scripts/Tests/xGamePythonReview.py

Fixes false positives in recent PRs #1137, #1136, #1130.

Fix missing module problem in scripts review.

---

Scripts/Python/islmRegisterNexusLink.py
Scripts/Python/nxusBookMachine.py

I believe these should be set for the H'uru side of things given the scripts are different from MOULa, but they should probably get another look just in case.

Update Nexus Scripts for public GoMePubNew

---

Scripts/Python/xDynTextDefs.py

Companion to https://github.com/H-uru/moul-assets/pull/157.

Increase font size on AtrusNote for better resolution

---

Sources/Plasma/CoreLib/hsSystemInfo.cpp

Xcode identified these as potential problems.

Fixup some macOS warnings

---

Sources/Tests/CMakeLists.txt

https://github.com/google/googletest/releases/tag/release-1.12.1

Update gtest to 1.12.1

---

Sources/Plasma/NucleusLib/pnUtils/pnUtStr.cpp
Sources/Plasma/NucleusLib/pnUtils/pnUtStr.h

Fix truncation warnings in StrCopy.

---

Scripts/SDL/ChisoPreniv.sdl
Scripts/dat/ChisoPreniv.age

* Add new Page/PRP to .age file
* Add Version 2 to .sdl file

Update Chiso scripts

---

Scripts/SDL/Tiam.sdl

Update Tiam to latest version.

Tiam Q2 2022 Update

---

Scripts/SDL/GoMePubNew.sdl
Scripts/dat/GoMePubNew.age

* Adds new SDL variables for new microphone in alcove 2 (Fil's Mic)
* Updates comments for gmpnHolidayVis defs
* Adds definition for new Mysterium PRP to .age file

Update GoMePubNew Q2 2022

---

Scripts/dat/FahetsHighgarden.age
Scripts/dat/FahetsHighgarden.fni

Adds the .age and .fni scripts for Fahets-Highgarden.
Age by Keith "Tweek" Lord.

Add Highgarden AGE and FNI

---

Scripts/SDL/Nexus.sdl

Update Nexus SDL to match MOULa.

---

Sources/Plasma/PubUtilLib/plPipeline/plTextFont.cpp

Mac font rendering has been improved and I'm trying to stream the changes in incrementally as best I can.
I've made a few improvements:
- Antialiasing has been disabled. The font textures go through a 1 bit pass which isn't compatible with antialiasing and produces a really bold look.
- macOS supports resolution independent font rendering. In theory - Windows on a HiDPI display would double the font size for double DPI. On macOS I can keep the font size constant - but double the resolution of the graphics context. I can then scale the x/y units down by half so the font will render the same - with double the pixels.
There probably still needs to be a fix so that the scale is passed through properly  - and fonts know if they need to render at a higher DPI.

Improving Mac Font Rendering

---

Sources/Plasma/PubUtilLib/plPipeline/plPlates.cpp
Sources/Plasma/PubUtilLib/plPipeline/plPlates.h
Sources/Plasma/PubUtilLib/plStatGather/plProfileManagerFull.cpp

Take over the world some moar with `std::move()`.

Move that thang.

---

Sources/Plasma/PubUtilLib/plClipboard/plClipboard.cpp

If you already have data in a different format in the clipboard, such as an image, copying text into the clipboard without clearing it can result in interesting results when attempting to paste. If the application you're pasting into accepts both images and text (eg discord), in my testing, the image is pasted instead of the newly copied text, leading to confusing UX with reports of the copy button not working. Therefore, we explicitly clear the clipboard content but only if there is an active window on the calling thread (if there isn't one, bad things happen per MSDN).

Fix problem with copying not working reliably.

---

Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIEditBoxMod.cpp

refs #1123 - see commit message for details

Fix missing last character when pasting into single-line edit boxes

---

Scripts/Python/ahnyPressurePlates.py
Scripts/Python/ahnyTrees.py
Scripts/Python/tldnBucketBrain.py
Scripts/Python/xIniHelper.py

Get rid of manually-incremented indexes in for-loops in several places. I ran a couple of these past @Hoikas and he provided better/faster replacements than I was going to use. (Thanks!)

Use more pythonic ways of looping in various files

---

Scripts/SDL/ahnonaycathedral.sdl

* Add new SDL bool variable for double doors for better multiplayer

Ahnonay Cathedral Q3 2022 Update

---

Scripts/Python/grsnMainWallPython.py
Scripts/Python/grsnNexusBookMachine.py
Scripts/Python/grsnWallPython.py

Removed forced camera call in maintainer nexus (Hopefully fixes camera weirdness sometimes experienced)
Blocker panel should be much more responsive with lots of players in the same age
Added clothing removal check when you use quit button or win region
Panel buttons should only respond to player sitting down now
Player sitting down now sets sdl for Panel blockers
Solo Mode added - panel on one side will duplicate itself to other side - will only work when your the only player in the age
Blocker count can be changed at any time before both sides have confirmed the count
Panel lights and blocker wall wont flash anymore when blocker count is changed after confirmation

Improvements to Wall Game code

---

Scripts/SDL/ChisoPreniv.sdl

* Update SDL to Version 3 for podium audio

Chiso Preniv Q3-4 2022 Update

---

Scripts/Python/xLinkingBookDefs.py
Scripts/Python/xLinkingBookGUIPopup.py

PRP needed - https://github.com/H-uru/moul-assets/pull/200
Adds code so that you can use a bookmark from the linking book itself to reset the age back to default.

Code for age reset mechanic from books

---

Sources/Plasma/PubUtilLib/plAvatar/plAvBrainHuman.cpp

This was only noticeable when disabling unity builds.

Add missing plgDispatch.h include

---

Sources/Plasma/FeatureLib/pfPython/cyPythonInterface.h
Sources/Plasma/FeatureLib/pfPython/pyGlueHelpers.h
Sources/Plasma/FeatureLib/pfPython/pyVaultAgeInfoNode.cpp

Edit: I'm realizing now that the `Py_RETURN_NONE` change will cause merge conflicts for all open PRs that touch the Python glue...

Miscellaneous simple pfPython cleanups

---

Sources/Plasma/PubUtilLib/plDrawable/plDrawableGenerator.cpp

The Cleft has a physical proxy that produces more than 32,000 indices. Therefore, we need to dice that up into multiple geometry spans to prevent bad things from happening.

Fix the Cleft physical proxies crashing.

---

Scripts/Python/xLinkingBookGUIPopup.py

Reverts https://github.com/H-uru/Plasma/pull/730
Did not actually fix the animations for others linking out

Reverts #730

---

Sources/Plasma/CoreLib/HeadSpin.cpp
Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIMenuItem.cpp
Sources/Plasma/PubUtilLib/plGImage/plDynamicTextMap.cpp
Sources/Plasma/PubUtilLib/plGImage/plDynamicTextMap.h
Sources/Tools/MaxExport/plExportDlg.cpp
Sources/Tools/MaxMain/plMaxCFGFile.cpp
Sources/Tools/MaxMain/plMaxMenu.cpp

Begone, legacy wide string handling!

Remove last uses of `hsStringToWString` and `hsWStringToString`

---

Sources/Plasma/FeatureLib/pfPython/Pch.h
Sources/Plasma/FeatureLib/pfPython/cyMisc.cpp
Sources/Plasma/FeatureLib/pfPython/cyMisc.h
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue2.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue3.cpp
Sources/Plasma/FeatureLib/pfPython/cyMiscGlue4.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonConvert.h
Sources/Plasma/FeatureLib/pfPython/plPythonFileMod.cpp
Sources/Plasma/FeatureLib/pfPython/plPythonPack.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvatarMgr.cpp
Sources/Plasma/PubUtilLib/plAvatar/plAvatarMgr.h
Sources/Plasma/PubUtilLib/plMessage/plCCRMsg.h
Sources/Plasma/PubUtilLib/plNetClient/plNetClientMgrSend.cpp

This should be the final `ST::string`ification PR for pfPython. See #1361 for a list of the few things that I'm intentionally not converting to `ST::string`.

Migrate cyMisc to `ST::string`

---

Scripts/Python/xOpeningSequence.py
Scripts/SDL/Personal.sdl

Data files - https://github.com/H-uru/moul-assets/pull/218

Fan Relto video to replace Yeesha Intro

---

Scripts/SDL/ChisoPreniv.sdl

* Update SDL to version 4 for Kalamee shirt SDL

Chiso Preniv Update 2.03.2023

---

Scripts/SDL/GoMePubNew.sdl

* Update SDL to version 13 for TCT and future GoMe shirts

GoMePubNew Update 2.03.2023

---

Scripts/Python/clftYeeshaPage08.py
Scripts/Python/xYeeshaPages.py

Makes python when you click on relto pages support up to 99 pages

Support up to 99 relto pages

---

Sources/Plasma/FeatureLib/pfPython/plPythonCallable.h

Close #1392, which is [incorrect](https://github.com/H-uru/Plasma/pull/1392#discussion_r1186771527).

Avoid using `_PyObject_CallOneArg()` on Python 3.8

---

Sources/Plasma/CoreLib/HeadSpin.h
Sources/Plasma/CoreLib/hsSystemInfo.cpp
Sources/Plasma/CoreLib/hsThread_Unix.cpp
Sources/Plasma/CoreLib/plFileSystem.h
Sources/Plasma/NucleusLib/pnNetCommon/CMakeLists.txt
Sources/Plasma/NucleusLib/pnUUID/CMakeLists.txt
Sources/Plasma/NucleusLib/pnUUID/pnUUID_Unix.cpp
Sources/Plasma/PubUtilLib/plPipeline/CMakeLists.txt
Sources/Tools/plFilePatcher/main.cpp

Not to set expectations too high, but with these changes I was able to compile the majority of the engine on an OpenIndiana (Solaris) virtual machine.
Tested and working:
* `test_CoreLib`
* `test_pnEncryption`
* `test_plUnifiedTime`
* `test_plLocalization`
* `test_pfPython`
* `plSystemInfo`
* `plFilePatcher`
* `plPageInfo`

Improve compatibility with some unix systems

---

.github/PRERELEASE_NOTES.md
.github/workflows/ci.yml
.github/workflows/publish-artifacts.yml

Prerelease publishing

---

Sources/Plasma/PubUtilLib/plAvatar/plArmatureEffects.cpp
Sources/Plasma/PubUtilLib/plAvatar/plArmatureEffects.h
Sources/Tools/MaxComponent/plFootstepComponent.cpp
Sources/Tools/MaxComponent/plResponderLink.cpp

Fix footstep sounds being in Chinese.

---

Sources/Plasma/CoreLib/hsSystemInfo.cpp

macOS doesn't support CPUID, so previously all macOS CPUs were being reported as "Unknown".
On newer versions, we can get the CPU vendor string from `sysctl`, and on very old versions we can look it up from the mach host info.
---
Results of plSystemInfo on Ventura:
```
OS: macOS 13.4.1
CPU: Apple M1 Pro
RAM: 16384 MiB
User Data Path: /Users/dpogue/Library/Application Support/Uru Live
```
Results of plSystemInfo on Catalina:
```
OS: Mac OS X 10.15.7
CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
RAM: 8192 MiB
User Data Path: /Users/dpogue/Library/Application Support/Uru Live
```
Results of plSystemInfo on Leopard:
```
OS: Mac OS X 10.5.8
CPU: PowerPC 7400
RAM: 1024 MiB
User Data Path: /Users/dpogue/Library/Application Support/Uru Live
```

Better finding of the macOS CPU Vendor name

---

.github/workflows/publish-artifacts.yml

We have a lot of duplicated ["releases"](https://github.com/H-uru/Plasma/releases). Hopefully this will fix that problem.

Delete the previous release for our "nightlies."

---

vcpkg.json

* **curl:** `8.2.0` -> `8.2.1`
* **openal-soft:** `1.23.0#2` -> `1.23.1`

Update vcpkg to 2023.08.09 tag

---

Sources/Plasma/CoreLib/hsSystemInfo.cpp

Was fixing a warning and saw this could be added

hsSystemInfo: Windows Server 2022 detection

---

.github/workflows/ci.yml
Sources/Tools/MaxComponent/plBipedKiller.cpp
Sources/Tools/MaxConvert/hsControlConverter.cpp
Sources/Tools/MaxConvert/plMaxLightContext.h
Sources/Tools/MaxMain/MaxCompat.h
cmake/Find3dsm.cmake

this set of changes makes the 3ds max plugin load under 2024 however only loading was tested.

max 2024 fixes

---

Sources/Plasma/FeatureLib/pfPython/plPythonPack.cpp
Sources/Plasma/PubUtilLib/plGImage/plMipmap.h

Fix a few more missing includes masked in PCH builds

---

cmake/PythonUtils.cmake

This saves between 2 - 4 seconds for each reconfigure on my system.

Avoid running `pip install -r` on every configure.

---

vcpkg.json

* **asio**
`1.28.2` -> `1.29.0`
* **curl**
`8.5.0` -> `8.6.0#1`
* **expat**
`2.5.0#3` -> `2.6.2`
* **freetype**
`2.12.1#5` -> `2.13.2`
* **libjpeg-turbo**
`3.0.1` -> `3.0.2`
* **libpng**
`1.6.40#1` -> `1.6.43`
* **libvpx**
`1.13.1#2` -> `1.13.1#3`
* **openssl**
`3.2.0#2` -> `3.2.1#1`
* **zlib**
`1.3` -> `1.3.1`

Update vcpkg to 2024.03.25

---

Sources/Tests/CoreTests/test_RAMStream.cpp

Changes and test comments as requested by @Hoikas

Cleanups to the hsRAMStream test

---

vcpkg.json

* **asio**
`1.29.0` -> `1.30.2`
* **curl**
`8.6.0#1` -> `8.8.0#1`
* **freetype**
`2.13.2` -> `2.13.2#1`
* **libpng**
`1.6.43` -> `1.6.43#2`
* **libvorbis**
`1.3.7#2` -> `1.3.7#3`
* **openssl**
`3.2.1#1` -> `3.3.1`
* **opus**
`1.4` -> `1.5.1`

Update vcpkg to 2024.06.15 tag

---

Scripts/Python/grsnNexusBookMachine.py

Issue  https://github.com/H-uru/Plasma/issues/1208
Prevents the OnNotify from running before OnServerInitComplete is done.
Arriving in Gahreesen from the Bahro Pole in Relto seems to run through the entryTrigger region and triggers the subworld entry.
This causes the avatar to fall out of the world because they are not anywhere with solid ground.

Hack to prevent issue #1208 in Gahreesen age

---

Scripts/Python/city.py
Scripts/dat/city.age

Assets - https://github.com/H-uru/moul-assets/pull/242
Script changes needed to make the city library doors work

Adds changes for city library doors to work

---

Sources/MaxPlugin/MaxConvert/plBitmapCreator.cpp

Fix max plugin debug build.

---

Sources/Plasma/Apps/plClient/plClient.cpp
Sources/Plasma/FeatureLib/pfDXPipeline/plDXPipeline.cpp
Sources/Plasma/NucleusLib/inc/plProfile.h

This adds some RAII helpers for guarded versions of the common `plProfile` operations. A few uses have been ported over to demonstrate the improvement.

Add some RAII helpers for profiling.

---

Sources/Plasma/FeatureLib/pfMetalPipeline/plMetalDevice.h

if -> ifdef change that didn't make it in before the merge.

Metal iOS Fixes - Continued

---

Sources/Plasma/FeatureLib/pfGameScoreMgr/pfGameScoreMgr.cpp
Sources/Plasma/PubUtilLib/plNetClientComm/plNetClientComm.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.cpp
Sources/Plasma/PubUtilLib/plNetGameLib/Private/plNglAuth.h

Follow-up to #1539, part 4 (and hopefully the last). This covers the remaining auth server callbacks that haven't been done yet. Nothing really interesting here - mostly just boring busywork.

Lambda-ify the remaining auth server callbacks

---

cmake/CMakeDetermineMetalCompiler.cmake
cmake/MetalShaderSupport.cmake

Pulling in updates and fixes from https://github.com/dpogue/CMake-MetalShaderSupport

Fix CMake Metal support for CMake 4.x

---

Scripts/Python/ahnyPressurePlates.py

These messages were very annoying/spammy while debugging #1724. Move them to debug dump level and improve the code with f-strings.

Hide ahnoying pressure plate messages.
